[ie/LCI] Fix extractor
yt-dlp/yt-dlp pull request #10025
Opened 2024-05-25 16:33 UTC by ocococococ

**IMPORTANT**: PRs without the template will be CLOSED

### LCI web site changed recently and LCI extractor could not work anymore

- So I extended the _VALID_URL regular expression to match the new additional level in URL
- I added code to parse the web page in order to get wat_id from nextjs data (without this, a wrong wat_id for an unrelated video is retrieved)
- I added a test

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-05-25 17:05 UTC, seproDev requested changes

2024-05-25 17:05 UTC, seproDev commented on yt_dlp/extractor/lci.py
> +        return self.url_result('wat:{}'.format(wat_id), 'Wat', wat_id)
How about:
```suggestion
        wat_id = traverse_obj(next_data, (
            'props', 'pageProps', 'page', 'tms', 'videos', {dict.keys}, ..., {int_or_none}, any))

        return self.url_result(f'wat:{wat_id}', WatIE, wat_id)
```
Also do any pages exist with multiple videos, in which case we should return this as a playlist?

2024-05-25 17:05 UTC, seproDev commented on yt_dlp/extractor/lci.py
> +from ..utils.traversal import traverse_obj
```suggestion
from .wat import WatIE
from ..utils import int_or_none
from ..utils.traversal import traverse_obj
```

2024-05-26 04:41 UTC, bashonly approved these changes

2024-05-26 04:41 UTC, bashonly commented on yt_dlp/extractor/lci.py
> +    _VALID_URL = r'https?://(?:www\.)?(?:lci|tf1info)\.fr(?:/[^/]+)+/[\w-]+-(?P<id>\d+)\.html'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?(?:lci|tf1info)\.fr/(?:[^/?#]+/)+[\w-]+-(?P<id>\d+)\.html'
```

2024-05-26 04:41 UTC, bashonly commented on yt_dlp/extractor/lci.py
> +            raise ExtractorError('Could not find wat_id')
```suggestion
        next_data = self._search_nextjs_data(webpage, video_id)
        wat_id = traverse_obj(next_data, (
            'props', 'pageProps', 'page', 'tms', 'videos', {dict.keys}, ..., {int_or_none}, any))
        if wat_id is None:
            raise ExtractorError('Could not find wat_id')
```

2024-05-26 04:41 UTC, bashonly commented on yt_dlp/extractor/lci.py
> +        return self.url_result(f'wat:{wat_id}', WatIE, wat_id)
```suggestion
        return self.url_result(f'wat:{wat_id}', WatIE, str(wat_id))
```

2024-05-26 21:33 UTC, merged