[ie/bandcamp] Extract extended user page
yt-dlp/yt-dlp pull request #10328
Opened 2024-07-01 19:44 UTC by quad

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

The user page is lazy-loaded from the JSON embedded in the data-client-items attribute. Let's use it, if it exists.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-07-26 13:06 UTC, quad commented
@bashonly AFAIK this PR is ready to merge. Is there anything else I need to do?

2024-07-26 19:15 UTC, bashonly requested changes
Sorry for the delay in reviewing.

I think we can take a simpler approach, see review comments below.

In addition to my suggestions, you would need to import `functools` and `json`, import `extract_attributes` and `get_element_html_by_id` from `..utils`, and import `traverse_obj` from `..utils.traversal`.

Please also update the tests if their counts have changed, and add a test if the existing tests don't provide coverage for the extended extraction

2024-07-26 19:15 UTC, bashonly commented on yt_dlp/extractor/bandcamp.py
> +            attr + ' data', group=2), video_id, fatal=fatal)
I would instead use a generator method to yield all the url paths
```suggestion
    def _yield_items(self, webpage):
        yield from (
            re.findall(r'<li data-item-id=["\'][^>]+>\s*<a href=["\'](?![^"\'/]*?/merch)([^"\']+)', webpage)
            or re.finditer(r'<div[^>]+trackTitle["\'][^"\']+["\']([^"\']+)', webpage))

        yield from traverse_obj(webpage, (
            {functools.partial(get_element_html_by_id, 'music-grid')}, {extract_attributes},
            'data-client-items', {json.loads}, ..., 'page_url', {str}))
```

2024-07-26 19:15 UTC, bashonly commented on yt_dlp/extractor/bandcamp.py
> +        return self.playlist_from_matches(matches, uploader, f'Discography of {uploader}')
and then do this
```suggestion
        return self.playlist_from_matches(
            self._yield_items(webpage), uploader, f'Discography of {uploader}',
            getter=functools.partial(urljoin, url))
```

2024-07-26 19:15 UTC, bashonly commented on yt_dlp/extractor/bandcamp.py
```suggestion
```

2024-09-12 19:51 UTC, formtapez commented
Any news on this?

2024-09-12 19:55 UTC, formtapez commented
Actual example: `https://traumschallplatten.bandcamp.com`

2024-09-13 06:26 UTC, bashonly approved these changes

2024-09-13 23:02 UTC, merged