Added RTVE play compatibility
yt-dlp/yt-dlp pull request #10388
Opened 2024-07-08 18:10 UTC by meGAmeS1

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Added RTVE Play compatibility. I reverse engineered the Javascript from the website to adapt the download from RTVE player

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-07-08 18:54 UTC, bashonly commented
Thanks for the PR.

Initial review:
Don't subclass from a concrete IE class. RTVPlay doesn't even need to be its own extractor if all it's doing is adding a `_VALID_URL` pattern; instead you can just add the pattern to `RTVEALaCartaIE._VALID_URL` (it can be a list of patterns). Check the code with ruff and autopep8; see the [developer instructions in the contributing guide](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

2024-07-08 18:55 UTC, bashonly commented
Does this fix #1346 ?

2024-07-08 19:00 UTC, meGAmeS1 commented
> Thanks for the PR.
> 
> Initial review:
> 
> * Don't subclass from a concrete IE class. RTVEPlay doesn't even need to be its own extractor if all it's doing is adding a `_VALID_URL` pattern; instead you can just add the pattern to `RTVEALaCartaIE._VALID_URL` (it can be a list of patterns).
> * Don't replace tests. Add a new test for a play URL
> * Check the code with ruff and autopep8; see the [developer instructions in the contributing guide](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

Okay thank you for the suggestions and the developer guide. I'll fix that and follow the rules





> Does this fix #1346 ?

Actually, yes! I just tested with the first video from https://www.rtve.es/play/videos/comando-actualidad/ (linked in the OP issue)

2024-07-10 11:21 UTC, meGAmeS1 commented
So I managed to follow your advices, I removed an old IE subclass that was only here to add regex and did the same for the subclass I previously created.

I also edited every tests from this extractor in order to fix and pass them (some previously linked videos were now unavailable so I found other ones)

And I reformatted the code to match the desired style

2024-07-10 16:01 UTC, bashonly commented
Why did you remove `RTVEInfantilIE` ?

2024-07-10 19:22 UTC, meGAmeS1 commented
Because, as it was a subclass only defined to add a regex, I grouped it in the main class. Should I revert that?

2024-07-10 19:25 UTC, bashonly commented
Yes please. I was only referring to the class you were adding.

2024-07-10 21:17 UTC, meGAmeS1 commented
Ok sorry about that then, I reverted it back (but with the change of test to make it work)

2024-07-16 21:23 UTC, meGAmeS1 commented
@bashonly Hi, do you consider the PR as ready to be merged or should I add something else? Thanks in advance :)

2024-07-22 04:38 UTC, oowowaee commented
Does this only work with old shows as per this comment? https://github.com/yt-dlp/yt-dlp/issues/1346#issuecomment-951204695. I had tried with a newer show (https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419) and got stuck in an endless redirect loop.

2024-07-22 06:12 UTC, oowowaee commented
@meGAmeS1 I'm not sure if I'm doing something wrong then, I don't have a play+ account but get stuck in

```
[redirect] Following redirect to https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
```

2024-07-22 06:16 UTC, meGAmeS1 commented
> @meGAmeS1 I'm not sure if I'm doing something wrong then, I don't have a play+ account but get stuck in
> 
> ```
> [redirect] Following redirect to https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
> ```

And when you are accessing the page from your browser, what do you see? I see that for me:
!
[image](https://github.com/user-attachments/assets/cced6c1c-fc7c-45fd-961b-9e842961e96a)

Also, just to check, in what country are you? I'm in France, so maybe I have a different behaviour

2024-07-22 06:29 UTC, oowowaee commented
@meGAmeS1 I see what you see without a Spanish VPN, the content isn't restricted from inside Spain, there's a modal that pops up that you can close to watch the episode.  I can try again without using a VPN, the other prs I was testing earlier needed that.

2024-07-22 07:24 UTC, meGAmeS1 commented
> @meGAmeS1 I see what you see without a Spanish VPN, the content isn't restricted from inside Spain, there's a modal that pops up that you can close to watch the episode. I can try again without using a VPN, the other prs I was testing earlier needed that.

Oh I see, so indeed the content is freely available with a VPN in Spain. But it completely works with my PR:
```
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419
[rtve.es:alacarta] 16160419: Downloading JSON metadata
[rtve.es:alacarta] 16160419: Downloading url information
[rtve.es:alacarta] 16160419: Downloading m3u8 information
[rtve.es:alacarta] 16160419: Downloading MPD manifest
[rtve.es:alacarta] 16160419: Downloading subtitles info
[info] 16160419: Downloading subtitles: es
[info] 16160419: Downloading 1 format(s): hls-1211
[info] Writing video subtitles to: Episodio 384 [16160419].es.vtt
[download] Destination: Episodio 384 [16160419].es.vtt
[download] 100% of   77.12KiB in 00:00:00 at 358.40KiB/s 
[SubtitlesConvertor] Converting subtitles
Deleting original file Episodio 384 [16160419].es.vtt (pass -k to keep)
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 648
[download] Destination: Episodio 384 [16160419].mp4
[download]  33.0% of ~ 468.59MiB at    4.51MiB/s ETA 01:03 (frag 215/648)[download] Got error: <urllib3.connection.HTTPSConnection object at 0x1070db2e0>: Failed to establish a new connection: [Errno 61] Connection refused. Retrying (1/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x1070a8070>: Failed to establish a new connection: [Errno 61] Connection refused. Retrying (2/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x1070abc10>: Failed to establish a new connection: [Errno 61] Connection refused. Retrying (3/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x1070a8e50>: Failed to establish a new connection: [Errno 61] Connection refused. Retrying (4/10)...
[download] 100% of  464.76MiB in 00:01:28 at 5.24MiB/s                   
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Episodio 384 [16160419].mp4"
[VideoConvertor] Not converting media file "Episodio 384 [16160419].mp4"; already is in target format mp4
[EmbedSubtitle] Embedding subtitles in "Episodio 384 [16160419].mp4"

Process finished with exit code 0
```

Are you sure you are using the code of my PR? Because indeed, if I use the current release of yt-dlp, I get an infinite loop:
```
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419
[generic] 16160419: Downloading webpage
[redirect] Following redirect to https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
[generic] 16160419: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 16160419: Extracting information
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/episodio-384/16160419/#__youtubedl_smuggle=%7B%22force...%2F16160419%2F%22%7D
[generic] 16160419: Downloading webpage
[redirect] Following redirect to https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/#__youtubedl_smuggle...3A+%2216160419%22%7D
[generic] 16160419: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 16160419: Extracting information
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/episodio-384/16160419/#__youtubedl_smuggle=%7B%22force...%2F16160419%2F%22%7D
[generic] 16160419: Downloading webpage
[redirect] Following redirect to https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/
[generic] Extracting URL: https://www.rtve.es/play/videos/la-promesa/temporada-3-episodio-384/16160419/#__youtubedl_smuggle...3A+%2216160419%22%7D
[generic] 16160419: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
```

2024-07-22 13:16 UTC, oowowaee commented
@meGAmeS1 Yes, I'm sorry I had something weird with my env yesterday and it wasn't picking up the changes at first.  I tested after and it works, and with the VPN everything works.  Thank you so much for fixing this, I was about to give up yesterday on this and then saw your pr at the last moment :)

2024-07-23 08:14 UTC, meGAmeS1 reviewed
@bashonly Ready for review

2024-10-13 13:27 UTC, wydengyre commented
I checked out this branch and rebased it on `master`. Verified that it works with this very recent (yesterday) RTVE page: https://www.rtve.es/play/videos/somos-cine/colon-adn-verdadero-origen/16281015/

Nice work!

```
mleon@Matthews-MacBook-Air yt-dlp % ./yt-dlp.sh 'https://www.rtve.es/play/videos/somos-cine/colon-adn-verdadero-origen/16281015/'
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/somos-cine/colon-adn-verdadero-origen/16281015/
[rtve.es:alacarta] 16281015: Downloading JSON metadata
[rtve.es:alacarta] 16281015: Downloading url information
[rtve.es:alacarta] 16281015: Downloading m3u8 information
[rtve.es:alacarta] 16281015: Downloading MPD manifest
[rtve.es:alacarta] 16281015: Downloading url information
[rtve.es:alacarta] 16281015: Downloading m3u8 information
[rtve.es:alacarta] 16281015: Downloading MPD manifest
[info] 16281015: Downloading 1 format(s): hls-4976
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1274
[download] Destination: Colón ADN. Su verdadero origen [16281015].mp4
```

2024-10-13 15:21 UTC, meGAmeS1 commented
Glad it could help someone else again @wydengyre, thanks for me letting me know.

Just to keep that branch up-to-date to the master branch I did the rebase too here

@bashonly Could you please remove the pending-fixes tag ?

2024-10-13 15:36 UTC, meGAmeS1 commented
Glad it could help someone else again @wydengyre, thanks for me letting me know.

Just to keep that branch up-to-date to the master branch I did the rebase too here

@bashonly Could you please remove the pending-fixes tag ?

2024-11-13 23:09 UTC, pachulo commented
I'm being hitted by this problem; how can I help so that this is merged?

2025-02-28 16:39 UTC, mixpc commented
Hi,

I  just cloned, compiled and run your version. I don't think there was an error while compiling.

```
user@ubuntu-server-development:~/yt-dlp$ ./yt-dlp --version
2024.07.07
```

```
user@ubuntu-server-development:~/yt-dlp$ ./yt-dlp.sh https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
[generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
[generic] 6641981: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6641981: Extracting information
[generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/el-perro-de-terracota/6641981/#__youtubed...a%2F6641981%2F%22%7D
[generic] 6641981: Downloading webpage
[redirect] Following redirect to https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
[generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/#__youtubedl_smug...%3A+%226641981%22%7D
[generic] 6641981: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
```

Also, the video has dual audio, would yt-dlp pick the two audio tracks? Thank you in advance!

2025-03-31 09:58 UTC, meGAmeS1 commented
Hello @mixpc, sorry for the late reply

> Hi,
> 
> I just cloned, compiled and run your version. I don't think there was an error while compiling.
> 
> ```
> user@ubuntu-server-development:~/yt-dlp$ ./yt-dlp --version
> 2024.07.07
> ```
> 
> Endless loop:
> 
> ```
> user@ubuntu-server-development:~/yt-dlp$ ./yt-dlp.sh https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
> [generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
> [generic] 6641981: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] 6641981: Extracting information
> [generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/el-perro-de-terracota/6641981/#__youtubed...a%2F6641981%2F%22%7D
> [generic] 6641981: Downloading webpage
> [redirect] Following redirect to https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
> [generic] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/#__youtubedl_smug...%3A+%226641981%22%7D
> [generic] 6641981: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> ```

Are you sure you cloned my repo ? ([git@github.com:meGAmeS1/yt-dlp.git](https://github.com/meGAmeS1/yt-dlp.git)) And are you on the right branch (`add-rtve-play`) ? Because the error `Falling back on generic information extractor` means your URL doesn't match the RTVE Extractor you provided, but when I test on my machine it does match the URL and download the file correctly

> Also, the video has dual audio, would yt-dlp pick the two audio tracks? Thank you in advance!

With yt-dlp you can list available formats (audio and video tracks) with the `-F` argument:
```
yt_dlp -F https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/ 
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/
[rtve.es:alacarta] 6641981: Downloading JSON metadata
[rtve.es:alacarta] 6641981: Downloading url information
[rtve.es:alacarta] 6641981: Downloading m3u8 information
[rtve.es:alacarta] 6641981: Downloading MPD manifest
[rtve.es:alacarta] 6641981: Downloading url information
[rtve.es:alacarta] 6641981: Downloading m3u8 information
[rtve.es:alacarta] 6641981: Downloading MPD manifest
[info] Available formats for 6641981:
ID                  EXT RESOLUTION FPS |   FILESIZE   TBR PROTO | VCODEC        VBR ACODEC      ABR ASR MORE INFO
----------------------------------------------------------------------------------------------------------------------------
dash-audio=194477-0 m4a audio only     | ~142.46MiB  194k dash  | audio only        mp4a.40.2  194k 48k DASH audio, m4a_dash
dash-audio=194477-1 m4a audio only     | ~142.46MiB  194k dash  | audio only        mp4a.40.2  194k 48k DASH audio, m4a_dash
2                   mp4 unknown        |                  http  | unknown           unknown
3                   mp4 unknown        |                  http  | unknown           unknown
dash-video=2766000  mp4 1280x720    25 | ~  1.98GiB 2766k dash  | avc1.640029 2766k video only          DASH video, mp4_dash
hls-3139            mp4 1280x720    25 | ~  2.25GiB 3139k m3u8  | avc1.640029 2766k mp4a.40.2  194k
dash-video=4520000  mp4 1920x1080   25 | ~  3.23GiB 4520k dash  | avc1.640029 4520k video only          DASH video, mp4_dash
hls-4998            mp4 1920x1080   25 | ~  3.58GiB 4998k m3u8  | avc1.640029 4520k mp4a.40.2  194k
```

As you can see, both of the audio tracks are listed. I don't know which one it will download by default but yes with yt-dlp you can tell it to download both tracks by doing something like this : `yt_dlp --audio-multistreams -f bestvideo+dash-audio=194477-0+dash-audio=194477-1 https://www.rtve.es/play/videos/el-comisario-montalbano/perro-terracota/6641981/` (note how I selected the bestvideo tracks and both audio tracks with their IDs : `bestvideo+dash-audio=194477-0+dash-audio=194477-1`)

2025-03-31 11:13 UTC, seproDev requested changes
Sorry this took so long. Here an initial review.

2025-03-31 11:13 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +                yield quality_str, url
Looking at the sites JS I would have said this is a more accurate implementation:
```suggestion
                data = bytes(filter(None, data))
                alphabet_data, _, url_data = data.partition(b'#')
                quality_str, _, url_data = url_data.rpartition(b'%%')
                quality_str = quality_str.decode() or ''
                alphabet = RTVEALaCartaIE._get_alfabet(alphabet_data)
                url = RTVEALaCartaIE._get_url(alphabet, url_data)
                yield quality_str, url
```
Do you have any examples where `%%` is in the data?

2025-03-31 11:13 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +        title = self._html_extract_title(webpage)
Inline below

2025-03-31 20:15 UTC, mixpc commented
@meGAmeS1 Thank you! I downloaded from your repo but missed the branch...

Please, note the two audios are the same audio in Spanish. So the Italian audio is missing. Strange.

Take
`https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/`

If you watch it online, you can select and listen to the two audio streams in Spanish and Italian.

But I have downloaded the two audio streams:

```
me@ubuntu-server:~/rtve/yt-dlp-add-rtve-play$ ./yt-dlp.sh -F  https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] 6641872: Downloading JSON metadata
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[info] Available formats for 6641872:
ID                  EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
dash-audio=193464-0 m4a audio only     │ ~154.36MiB  193k dash  │ audio only        mp4a.40.2  193k 48k DASH audio, m4a_dash
dash-audio=193464-1 m4a audio only     │ ~154.36MiB  193k dash  │ audio only        mp4a.40.2  193k 48k DASH audio, m4a_dash
2                   mp4 unknown        │                  http  │ unknown           unknown
3                   mp4 unknown        │                  http  │ unknown           unknown
dash-video=2766000  mp4 1280x720    25 │ ~  2.16GiB 2766k dash  │ avc1.640029 2766k video only          DASH video, mp4_dash
hls-3138            mp4 1280x720    25 │ ~  2.44GiB 3138k m3u8  │ avc1.640029 2766k mp4a.40.2  193k
dash-video=4519000  mp4 1920x1080   25 │ ~  3.52GiB 4519k dash  │ avc1.640029 4519k video only          DASH video, mp4_dash
hls-4996            mp4 1920x1080   25 │ ~  3.89GiB 4996k m3u8  │ avc1.640029 4519k mp4a.40.2  193k
me@ubuntu-server:~/rtve/yt-dlp-add-rtve-play$ ./yt-dlp.sh -f dash-audio=193464-0 https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] 6641872: Downloading JSON metadata
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[info] 6641872: Downloading 1 format(s): dash-audio=193464-0
[dashsegments] Total fragments: 3348
[download] Destination: La forma del agua [6641872].m4a
[download] 100% of  156.24MiB in 00:02:03 at 1.26MiB/s
[FixupM4a] Correcting container of "La forma del agua [6641872].m4a"
[FixupDuplicateMoov] Fixing duplicate MOOV atoms of "La forma del agua [6641872].m4a"
me@ubuntu-server:~/rtve/yt-dlp-add-rtve-play$ mv La\ forma\ del\ agua\ \[6641872\].m4a audio0.m4a
me@ubuntu-server:~/rtve/yt-dlp-add-rtve-play$ ./yt-dlp.sh -f dash-audio=193464-1 https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/
[rtve.es:alacarta] 6641872: Downloading JSON metadata
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[rtve.es:alacarta] 6641872: Downloading url information
[rtve.es:alacarta] 6641872: Downloading m3u8 information
[rtve.es:alacarta] 6641872: Downloading MPD manifest
[info] 6641872: Downloading 1 format(s): dash-audio=193464-1
[dashsegments] Total fragments: 3348
[download] Destination: La forma del agua [6641872].m4a
[download] 100% of  156.24MiB in 00:03:51 at 692.20KiB/s
[FixupM4a] Correcting container of "La forma del agua [6641872].m4a"
[FixupDuplicateMoov] Fixing duplicate MOOV atoms of "La forma del agua [6641872].m4a"
me@ubuntu-server:~/rtve/yt-dlp-add-rtve-play$ mv La\ forma\ del\ agua\ \[6641872\].m4a audio1.m4a

```
and audio0.mp4 and audio1.m4a are both in Spanish. So maybe code in rtve has changed?

2025-03-31 20:20 UTC, bashonly commented
@mixpc  to download both audio streams and merge them into the same file you'd need to do this:
```
./yt-dlp.sh --audio-multistreams -f "bv+mergeall[vcodec=none]" "https://www.rtve.es/play/videos/el-comisario-montalbano/forma-agua/6641872/"
```

2025-04-13 22:59 UTC, seproDev commented on yt_dlp/extractor/rtve.py
>      def _real_initialize(self):
I decided to hard code this, as it was only dependent on the user agent.

2025-04-13 22:59 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +        for manager in (self._manager, 'rtveplayw'):
Ah for https://www.rtve.es/infantil/serie/agus-lui-churros-crafts/video/gusano/7048976/ `rtveplayw` return 1080p, while `default` returns 720p. Keeping both.

2025-04-13 23:13 UTC, seproDev approved these changes

2025-04-14 16:31 UTC, meGAmeS1 commented
@seproDev Well done for the cleanup. As suggested in a comment on an other issue, I said I could look on how to add playlist support (to be able to download a whole directly instead of doing video by video manually, so for exemple pass this URL `https://www.rtve.es/play/videos/masterchef/` to download each video of the show).

Your work motivated me and I've done it, should I push it here or should it be on its own PR after this one is merged ? (the code isn't very long, it's about 40 lines of code)

2025-04-14 16:34 UTC, seproDev commented
Let's do that in a separate PR after this one is merged.

2025-04-18 19:54 UTC, bashonly requested changes

2025-04-18 19:54 UTC, bashonly commented on yt_dlp/extractor/rtve.py
> +        self._merge_subtitles(self.extract_subtitles(video_id), target=subtitles)
Does this actually work? I would think we'd need to pass `subtitles` to `extract_subtitles` and merge them inside `_get_subtitles`

2025-04-18 19:54 UTC, bashonly commented on yt_dlp/extractor/rtve.py
> +        is_infantil = urllib.parse.urlparse(url).path.startswith('/infantil/')
could also make this a capture group in `_VALID_URL` and set the var at the beginning of `_real_extract`

2025-04-18 19:54 UTC, bashonly commented on yt_dlp/extractor/rtve.py
> +            'title': self._html_extract_title(webpage),
what does the title look like? we don't need to perform any string surgery like the old code did?

2025-04-18 19:54 UTC, bashonly commented on yt_dlp/extractor/rtve.py
> +            r'<div[^>]+class="[^"]*videoPlayer[^"]*"[^>]*data-setup=\'',
they single quote the json and don't escape html special chars (`"`=>`&quot;`)?

2025-04-18 20:28 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +        self._merge_subtitles(self.extract_subtitles(video_id), target=subtitles)
I don't see why not. We always extract the m3u8/mpd subs, but only call the dedicated api if subtitles were requested by the user.

2025-04-18 20:41 UTC, bashonly commented on yt_dlp/extractor/rtve.py
> +        self._merge_subtitles(self.extract_subtitles(video_id), target=subtitles)
ah true, just looked at the `extract_subtitles` code and nvm

2025-04-18 20:49 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +            'title': self._html_extract_title(webpage),
Yes, they are just providing the full title now. I have improved the extractor a bit by adding more metadata and support the new type URLs

2025-04-18 20:56 UTC, seproDev commented on yt_dlp/extractor/rtve.py
> +            r'<div[^>]+class="[^"]*videoPlayer[^"]*"[^>]*data-setup=\'',
Yes
```html
      <div class="ima f16x9 videoPlayer" 
      data-setup='{
        "id":1,
        "idAsset":"1688877",
        "isLive": "true",
        "segment": false,
        "imagen": "https://img2.rtve.es/resources/thumbslive/H_1688877.jpg",
        "hasDRM": false,
        "idLicencia": null,
        "requireLogged": true
      }'>
```

2025-04-18 23:42 UTC, bashonly approved these changes

2025-04-18 23:47 UTC, merged