feat: adjust domain matching and tests
yt-dlp/yt-dlp pull request #10399
Opened 2024-07-09 16:27 UTC by infanf

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADN (Animation Digital Network) changed their domain to animationdigitalnetwork.com and removed local domains .fr and .de

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-07-09 16:27 UTC, infanf commented
The new domain will go live tomorrow, will test if everything works and if needed fix accordingly then

2024-07-11 22:15 UTC, Deluvi commented
Hi, your PR does not quite solve the issue yet, as the ADN's URLs does not include a `/fr/` (at least in France)

I opened a PR on your fork with the changes I made to download some content on my side. Feel free to get the changes you need and close it: https://github.com/infanf/yt-dlp/pull/1

2024-07-11 22:31 UTC, infanf commented
> I opened a PR on your fork with the changes I made to download some content on my side. Feel free to get the changes you need and close it: [infanf#1](https://github.com/infanf/yt-dlp/pull/1)

Thank for the fix, but this will break the German site. Yesterday .com redirected to .com/de when in Austria/Germany and to .com/fr otherwise, which is why I made these changes. Looks like the German content is under .com/de and the French under .com only. Adjusted accordingly.

2024-07-12 20:18 UTC, Deluvi commented
Works well, cheers

2024-07-14 00:51 UTC, bashonly requested changes

2024-07-14 00:51 UTC, bashonly commented on yt_dlp/extractor/adn.py
> +    _VALID_URL = r'https?://(?:www\.)?(?:animation|anime)digitalnetwork\.com/((?P<lang>de)/)?video/[^/?#]+/(?P<id>\d+)'
non-capturing group for the outer group
```suggestion
    _VALID_URL = r'https?://(?:www\.)?(?:animation|anime)digitalnetwork\.com/(?:(?P<lang>de)/)?video/[^/?#]+/(?P<id>\d+)'
```

2024-07-14 00:51 UTC, bashonly commented on yt_dlp/extractor/adn.py
> +    _VALID_URL = r'https?://(?:www\.)?(?:animation|anime)digitalnetwork\.com/((?P<lang>de)/)?video/(?P<id>[^/?#]+)/?(?:$|[#?])'
same as above
```suggestion
    _VALID_URL = r'https?://(?:www\.)?(?:animation|anime)digitalnetwork\.com/(?:(?P<lang>de)/)?video/(?P<id>[^/?#]+)/?(?:$|[#?])'
```

2024-07-14 00:51 UTC, bashonly commented on yt_dlp/extractor/adn.py
>                      ADNIE, episode_id)
```py
                yield self.url_result(join_nonempty(
                    'https://animationdigitalnetwork.com', lang, 'video',
                    video_show_slug, episode_id, delim='/'), ADNIE, episode_id)
```

2024-07-14 00:51 UTC, bashonly commented on yt_dlp/extractor/adn.py
> +            lang = 'fr'
```suggestion
```

2024-07-14 00:51 UTC, bashonly commented on yt_dlp/extractor/adn.py
> +            lang = 'fr'
```suggestion
```

2024-07-14 00:54 UTC, bashonly commented on yt_dlp/extractor/adn.py
> +                baseurl = 'https://animationdigitalnetwork.com' + ('/' + lang if lang != 'fr' else '')
```suggestion
```

2024-07-14 00:57 UTC, bashonly approved these changes
I applied some changes, please test them and let me know what you think

2024-07-14 09:32 UTC, infanf commented
Treated them, works great. Thanks

2024-07-14 15:58 UTC, merged