Bugfix for #10407: Alternative way to access room_id for TikTok lives
yt-dlp/yt-dlp pull request #10408
Opened 2024-07-09 23:14 UTC by mokrueger

### Fixes https://github.com/yt-dlp/yt-dlp/issues/10407

Adds the described (backwards compatible) way to access the room_id for TikTok lives.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-07-09 23:18 UTC, bashonly requested changes

2024-07-09 23:18 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                         or traverse_obj(music_info, ('duration', {int_or_none}))),
revert
```suggestion
                or traverse_obj(music_info, ('duration', {int_or_none}))),
```

2024-07-09 23:18 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
>                         or room_id)
```suggestion
            room_id = (
                traverse_obj(data, ((
                    ('LiveRoom', 'liveRoomUserInfo', 'user'),
                    ('UserModule', 'users', ...)), 'roomId', {str}, any))
                or self._search_regex(r'snssdk\d*://live\?room_id=(\d+)', webpage, 'room ID', default=room_id))
```

2024-07-09 23:22 UTC, bashonly approved these changes

2024-07-09 23:27 UTC, merged

2024-07-09 23:39 UTC, mokrueger commented
@bashonly thanks for the quick update. And apologies for the minor formatting issues

2024-07-10 03:19 UTC, bashonly commented
@mokrueger all good, thanks for the PR