Fix Epidemic Sound SFX unsupported url
yt-dlp/yt-dlp pull request #10436
Opened 2024-07-12 11:47 UTC by iancmy

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Fixed Epidemic Sound SFX unsupported url pattern (https://www.epidemicsound.com/sound-effects/tracks/2f02f54b-9faa-4daf-abac-1cfe9e9cef69/)

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-07-13 17:21 UTC, bashonly requested changes
Thanks for the PR. Please see review comments, and also please add a test for the new url format

2024-07-14 03:55 UTC, iancmy reviewed
Thanks for the review! @bashonly 
- Implemented changes based on review
- Added test for the new url format

2024-07-14 04:00 UTC, bashonly requested changes

2024-07-14 04:00 UTC, bashonly commented on yt_dlp/extractor/epidemicsound.py
> +        json_data = self._download_json(join_nonempty('https://www.epidemicsound.com/json/track', is_sfx and 'kosmos-id', video_id, delim='/'), video_id)
line too long
```suggestion
        json_data = self._download_json(join_nonempty(
            'https://www.epidemicsound.com/json/track'
            is_sfx and 'kosmos-id', video_id, delim='/'), video_id)
```

2024-07-14 04:02 UTC, bashonly commented on yt_dlp/extractor/epidemicsound.py
> +            'https://www.epidemicsound.com/json/track'
```suggestion
            'https://www.epidemicsound.com/json/track',
```

2024-07-14 04:11 UTC, bashonly commented on yt_dlp/extractor/epidemicsound.py
> -    }, {
test passes too

2024-07-14 04:17 UTC, bashonly approved these changes

2024-07-14 04:52 UTC, merged