Added Support for .eu and .global extentions for chaturbate
yt-dlp/yt-dlp pull request #10595
Opened 2024-07-29 14:40 UTC by manavchaudhary1

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [ x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ x] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>
Fix #10594

2024-07-29 14:55 UTC, bashonly requested changes
add tests for the newly supported domains please (they can be `only_matching`)

2024-07-29 14:55 UTC, bashonly commented on yt_dlp/extractor/chaturbate.py
> +    _VALID_URL = r'https?://(?:[^/]+\.)?chaturbate\.(?P<domain>com|eu|global)/(?:fullvideo/?\?.*?\bb=)?(?P<id>[^/?&#]+)'
```suggestion
    _VALID_URL = r'https?://(?:[^/]+\.)?chaturbate\.(?P<tld>com|eu|global)/(?:fullvideo/?\?.*?\bb=)?(?P<id>[^/?&#]+)'
```

2024-07-29 14:55 UTC, bashonly commented on yt_dlp/extractor/chaturbate.py
> +        domain = mobj.group('domain')
```suggestion
        video_id, tld = self._match_valid_url(url).group('id', 'tld')
```

2024-07-29 14:55 UTC, bashonly commented on yt_dlp/extractor/chaturbate.py
> +            f'https://chaturbate.{domain}/{video_id}/', video_id,
```suggestion
            f'https://chaturbate.{tld}/{video_id}/', video_id,
```

2024-07-29 14:59 UTC, manavchaudhary1 commented
Ok i'll add tests

2024-08-08 13:44 UTC, manavchaudhary1 commented
@bashonly should i rewrite the tests ?

2024-11-11 22:40 UTC, bashonly approved these changes

2024-11-11 22:41 UTC, merged