[ie/rtp] Add support for zigzag subdomain
yt-dlp/yt-dlp pull request #10787
Opened 2024-08-18 16:09 UTC by Demon000

On the zigzag subdomain, the file property for the RTPPlayer constructor object is inlined, as opposed to being declared before the RTPPlayer instantiation. Add support for this.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-08-18 16:21 UTC, bashonly requested changes

2024-08-18 16:21 UTC, bashonly commented on yt_dlp/extractor/rtp.py
> +            f = config.get('file')
if we flip-flop the order of JSON parsing we can simplify this
```suggestion
        config = self._parse_json(
            config, video_id,
            lambda data: self.__unobfuscate(data, video_id=video_id))
        f = config.get('file') if not f else self._parse_json(
            f, video_id,
            lambda data: self.__unobfuscate(data, video_id=video_id))
```

2024-08-18 16:21 UTC, bashonly commented on yt_dlp/extractor/rtp.py
> +                (var\s+f\s*=\s*(?P<f>".*?"|{[^;]+?});\s*)?
non-capturing group
```suggestion
                (?:var\s+f\s*=\s*(?P<f>".*?"|{[^;]+?});\s*)?
```

2024-08-18 16:21 UTC, bashonly commented on yt_dlp/extractor/rtp.py
> +    _VALID_URL = r'https?://(?:www\.)?rtp\.pt/play(/zigzag)?/p(?P<program_id>[0-9]+)/(?P<id>[^/?#]+)/?'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?rtp\.pt/play/(?:zigzag/)?p(?P<program_id>[0-9]+)/(?P<id>[^/?#]+)/?'
```

2024-08-19 10:36 UTC, seproDev requested changes
Please don't force push in the future

2024-08-19 10:36 UTC, seproDev commented on yt_dlp/extractor/rtp.py
> +    _VALID_URL = r'https?://(?:www\.)?rtp\.pt/play/(?:zigzag/)?p(?P<program_id>[0-9]+)/(?P<id>[^/?#]+)/?'
Can you add `estudoemcasa` and `palco` as well?
```suggestion
    _VALID_URL = r'https?://(?:www\.)?rtp\.pt/play/(?:(?:estudoemcasa|palco|zigzag)/)?p(?P<program_id>[0-9]+)/(?P<id>[^/?#]+)'
```
Please also add appropriate tests. match_only is fine.
 - https://www.rtp.pt/play/estudoemcasa/p7776/portugues-1-ano
 - https://www.rtp.pt/play/palco/p13785/l7nnon

2024-08-19 11:44 UTC, seproDev approved these changes

2024-08-19 17:19 UTC, bashonly approved these changes

2024-08-26 20:38 UTC, bashonly commented on yt_dlp/extractor/rtp.py
> +        f = config.get('file') if not f else self._parse_json(
```suggestion
        f = config['file'] if not f else self._parse_json(
```

2024-09-13 23:09 UTC, merged