Make extended attribute writing more robust against filesystem limits.
yt-dlp/yt-dlp pull request #11115
Opened 2024-09-28 16:33 UTC by eric321

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Some filesystems limit the size of extended attributes (e.g., 4kB on ext4). The description can easily get close to or exceed this. By writing it last, we avoid missing out on the other ones.

Also catch each write_xattr() failure individually, so we can report which attributes were not written.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-09-28 16:57 UTC, Grub4K requested changes
No reason to change it to a list, dicts are ordered

2024-09-28 17:56 UTC, eric321 commented
done

2024-09-28 18:09 UTC, Grub4K commented
Try to avoid force pushing, prs will be squashed on merge, so take as many commits as you want

2024-09-28 23:42 UTC, bashonly approved these changes

2024-09-28 23:42 UTC, bashonly commented on yt_dlp/postprocessor/xattrpp.py
>          # 'user.xdg.comment': 'description',
I know this is old/dead code but let's move this down to the end of the dict
```suggestion
```

2024-09-28 23:42 UTC, bashonly commented on yt_dlp/postprocessor/xattrpp.py
> +        'user.dublincore.description': 'description',
```suggestion
        'user.dublincore.description': 'description',
        # 'user.xdg.comment': 'description',
```

2024-09-28 23:42 UTC, bashonly commented on yt_dlp/postprocessor/xattrpp.py
> +                        f'Extended attribute {xattrname} was not written.')
```suggestion
                        f'Extended attribute "{xattrname}" was not written.')
```

2024-09-28 23:42 UTC, bashonly commented on yt_dlp/postprocessor/xattrpp.py
> +                    self.report_warning(f'Unable to write extended attribute {xattrname} due to too long values.')
```suggestion
                    self.report_warning(f'Unable to write extended attribute "{xattrname}" due to too long values.')
```

2024-09-29 07:53 UTC, Grub4K approved these changes

2024-10-07 23:17 UTC, merged