[CBC Gem] Fix 1080p detection after URL format change
yt-dlp/yt-dlp pull request #11196
Opened 2024-10-08 18:20 UTC by DavidSkrundz

### Description

Fix 1080p stream detection for CBC Gem, and remove obsolete function.

The URL format the CBC uses has changed and is a lot simpler.  `_find_secret_formats` is no longer required and can be replaced with a single `re.sub` that removes the `manifestType=` filter.

The change was tested with `https://gem.cbc.ca/media/murdoch-mysteries/sXXeXX` for a number of seasons and episodes.

##### Before
```
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/murdoch-mysteries/s18e01
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading m3u8 information
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading secret XML
WARNING: [gem.cbc.ca] murdoch-mysteries/s18e01: Failed to parse XML: syntax error: line 1, column 0
[info] Available formats for murdoch-mysteries/s18e01:
ID                                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio_0-English__Descriptive_ m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_0-English               m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-651                           mp4 416x234     30 │ ~203.39MiB  651k m3u8  │ avc1.42C00D  651k video only
hls-871                           mp4 640x360     30 │ ~272.10MiB  871k m3u8  │ avc1.42C01E  871k video only
hls-1311                          mp4 640x360     30 │ ~409.52MiB 1311k m3u8  │ avc1.42C01E 1311k video only
hls-2191                          mp4 960x540     30 │ ~684.36MiB 2191k m3u8  │ avc1.4D401F 2191k video only
hls-2961                          mp4 1280x720    30 │ ~924.83MiB 2961k m3u8  │ avc1.4D401F 2961k video only
hls-3951                          mp4 1280x720    30 │ ~  1.21GiB 3951k m3u8  │ avc1.4D401F 3951k video only
```

##### After
```
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/murdoch-mysteries/s18e01
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading m3u8 information
[info] Available formats for murdoch-mysteries/s18e01:
ID                                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio_0-English__Descriptive_ m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_1-English__Descriptive_ m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_2-English__Descriptive_ m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English (Descriptive)
hls-audio_0-English               m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_1-English               m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-audio_2-English               m4a audio only     │                  m3u8  │ audio only        mp4a.40.2  [eng] English
hls-321                           mp4 416x234     10 │ ~100.31MiB  321k m3u8  │ avc1.42C00C  321k video only
hls-431                           mp4 416x234     15 │ ~134.68MiB  431k m3u8  │ avc1.42C00C  431k video only
hls-651                           mp4 416x234     30 │ ~203.39MiB  651k m3u8  │ avc1.42C00D  651k video only
hls-871                           mp4 640x360     30 │ ~272.10MiB  871k m3u8  │ avc1.42C01E  871k video only
hls-1311                          mp4 640x360     30 │ ~409.52MiB 1311k m3u8  │ avc1.42C01E 1311k video only
hls-2191                          mp4 960x540     30 │ ~684.36MiB 2191k m3u8  │ avc1.4D401F 2191k video only
hls-2961                          mp4 1280x720    30 │ ~924.83MiB 2961k m3u8  │ avc1.4D401F 2961k video only
hls-3951                          mp4 1280x720    30 │ ~  1.21GiB 3951k m3u8  │ avc1.4D401F 3951k video only
hls-6811                          mp4 1920x1080   30 │ ~  2.08GiB 6811k m3u8  │ avc1.640028 6811k video only
```

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-10-20 23:26 UTC, bashonly commented
do you have any example URLs that aren't authwalled?

when running the PR branch this happens to me (instead of the "login required" error I get with master):

```
[gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/murdoch-mysteries/s18e01
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
[gem.cbc.ca] murdoch-mysteries/s18e01: Downloading JSON metadata
ERROR: expected string or bytes-like object, got 'NoneType'
```

2024-10-21 03:06 UTC, bashonly requested changes

2024-10-21 03:06 UTC, bashonly commented on yt_dlp/extractor/cbc.py
> +        m3u8_url = re.sub(r'(manifestType=)[\w_-]+(&)', r'\1\2', m3u8_info.get('url'))
this line should be moved below the error handling (and import `update_url_query` from utils)
```suggestion
        m3u8_url = update_url_query(m3u8_info['url'], {'manifestType': ''})
```

2024-10-21 04:54 UTC, bashonly approved these changes

2024-10-21 15:49 UTC, seproDev approved these changes

2024-10-21 18:56 UTC, merged