PBS/thirteen.org fixes
yt-dlp/yt-dlp pull request #11191
Opened 2024-10-07 22:17 UTC by rohieb

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

* Fix existing tests for PBSIE
* Rework support for thirteen.org, whose URLs look a lot like pbs.org, but its HTML is a bit different. Not sure if the existing video.thirteen.org still matches something in the real world, but let's keep it for now. It might that https://github.com/yt-dlp/yt-dlp/issues/10728#issuecomment-2285626550 applies here too, and we should maybe just try to match all _STATIONS instead of `pbs.org` as well…?

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-12-19 16:36 UTC, rohieb commented
Any comments on this one? Seems to work flawlessly for me for 2 months now.

2025-01-11 12:55 UTC, rohieb commented
Nobody? (I just keep rebasing on master)

2025-01-28 10:39 UTC, rohieb commented
Thanks to #11514 this just got easier! :)

2025-01-28 14:46 UTC, bashonly requested changes

2025-01-28 14:46 UTC, bashonly commented on yt_dlp/extractor/pbs.py
> +                r'.*class="passportcoveplayer"[^>]+data-media="(\d+)',  # https://www.thirteen.org/programs/the-woodwrights-shop/who-wrote-the-book-of-sloyd-fggvvq/
```suggestion
                r'\bclass="passportcoveplayer"[^>]+\bdata-media="(\d+)',  # https://www.thirteen.org/programs/the-woodwrights-shop/who-wrote-the-book-of-sloyd-fggvvq/
```

2025-01-28 22:26 UTC, rohieb commented
@bashonly thanks for the review, I've included it

2025-01-28 22:32 UTC, bashonly commented on yt_dlp/extractor/pbs.py
> +        (r'(www\.)?thirteen\.org', 'Thirteen (WNET'),  # https://thirteen.org
make it a non-capturing group
```suggestion
        (r'(?:www\.)?thirteen\.org', 'Thirteen (WNET'),  # https://thirteen.org
```

2025-01-28 22:34 UTC, bashonly requested changes

2025-01-28 22:34 UTC, bashonly commented on yt_dlp/extractor/pbs.py
>          },
add this as a new test, don't replace the existing test. if the existing test's link is dead, then add a `skip` field to the test dict

2025-01-28 23:08 UTC, rohieb commented on yt_dlp/extractor/pbs.py
>          },
Hmm. I did this, but `hatch test PBSIE` now seems to skip all tests in the dict, not only the single one…? (If I try to produce errors in the other tests, the test run still doesn't report errors, only "SKIPPED 1 test")

2025-01-28 23:10 UTC, bashonly commented on yt_dlp/extractor/pbs.py
>          },
`hatch test PBS` only runs the first test case. use `PBS_all` or `PBS_1`, `PBS_2` etc

and don't force-push please

2025-01-28 23:18 UTC, rohieb commented on yt_dlp/extractor/pbs.py
>          },
Well, I somehow had to amend my first commit, can't do that without force pushing.

Thanks for the `PBS_all` hint… unfortunately several more tests now fail, and I don't know how to deal with that… so I'm inclined just to leave out the first commit about repairing the tests at all… 🙃

2025-01-28 23:20 UTC, bashonly commented on yt_dlp/extractor/pbs.py
>          },
all commits are squashed upon merge anyways; in the master branch nobody will see how many commits you made or your commit messages

2025-01-28 23:23 UTC, bashonly commented on yt_dlp/extractor/pbs.py
>          },
as far as the other tests, run them without your changes. if they still fail without your changes, you don't need to worry about them. we'd only need to be concerned if your changes broke the tests, or if the urls aren't matched anymore

2025-01-28 23:28 UTC, rohieb commented on yt_dlp/extractor/pbs.py
>          },
OK. In that case, I don't see any errors for the test that I've added (`PBS_2`), and fixing the rest is still better than before.

2025-01-28 23:28 UTC, bashonly approved these changes

2025-01-28 23:38 UTC, merged

2025-01-29 00:30 UTC, dirkf commented on yt_dlp/extractor/pbs.py
> +                r'.*class="passportcoveplayer"[^>]+data-media="(\d+)',  # https://www.thirteen.org/programs/the-woodwrights-shop/who-wrote-the-book-of-sloyd-fggvvq/
FWIW `\b` is not fully reliable for finding `attr=value`, because there may be another element with, say, `data-foo-attr=other_value`. `(?<!-)\b` is one possible solution, or include `\s` explicitly if that must be present. I think `-` is the only character from `\W` that needs to be considered.

Here both the above formulations are relevant:
```diff
-                r'\bclass="passportcoveplayer"[^>]+\bdata-media="(\d+)',  # https://www.thirteen.org/programs/the-woodwrights-shop/who-wrote-the-book-of-sloyd-fggvvq/
+                r'(?<!-)\bclass="passportcoveplayer"[^>]*\sdata-media="(\d+)',  # https://www.thirteen.org/programs/the-woodwrights-shop/who-wrote-the-book-of-sloyd-fggvvq/
```
But that still relies on the site sending the matched attributes in that order, in a  context where order isn't significant. AFAIK there isn't really a better solution than including a pattern for each order.