[Gettr] Add new extractor
yt-dlp/yt-dlp pull request #1120
Opened 2021-09-28 22:37 UTC by i6t

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
(closes https://github.com/ytdl-org/youtube-dl/issues/29589)

2021-09-28 22:53 UTC, pukkandan requested changes

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +            title = re.sub(r'\s*https?://[^\s]+', '', title)
dont think this is needed

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +            or user_data.get('username')
dict_get

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +            raise ExtractorError("There's no video in this post.")
Use single quotes everywhere

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +                'preference': 0
set increased `quality` and `source_preference`, not `preference`

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +                entry_protocol='m3u8_native', m3u8_id='hls'))
```suggestion
        formats = self._extract_m3u8_formats(
            urljoin(self._MEDIA_BASE_URL, vid), post_id, 'mp4',
            entry_protocol='m3u8_native', m3u8_id='hls')) if vid else []
```

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +        duration = float_or_none(post_data.get('vid_dur'))
since these are not used anywhere, move them closer to the return, or even better, remove the variables for them entirely

2021-09-28 22:53 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +        user_data = try_get(api_data, lambda x: x['result']['aux']['uinf'][post_data.get('uid')]) or {}
```suggestion
        user_data = try_get(api_data, lambda x: x['result']['aux']['uinf'][post_data['uid']]) or {}
```
no point using `.get` inside `try_get`

2021-09-28 23:34 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +            raise ExtractorError("There's no video in this post.")
oh, sorry. I didnt notice the quote inside the string 🤦

We dont currently have any strict policy for those, so I guess either is fine for now

2021-09-28 23:37 UTC, pukkandan approved these changes

2021-09-28 23:37 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +                entry_protocol='m3u8_native', m3u8_id='hls') if vid else []
```py
        formats = []

        if vid:
            ...
```

The point was to get rid of this part

```suggestion
        vid = post_data.get('vid')
        ovid = post_data.get('ovid')

        formats = self._extract_m3u8_formats(
            urljoin(self._MEDIA_BASE_URL, vid), post_id, 'mp4',
            entry_protocol='m3u8_native', m3u8_id='hls') if vid else []
```

2021-09-28 23:39 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +                'quality': 0
Yes, this is technically correct, but is misleading

```suggestion
                'source_preference': 1,
                'quality': 1,
```

2021-09-29 06:06 UTC, FayasNoushad approved these changes

2021-09-29 10:23 UTC, merged