[ie/Soop] Add support for Soop. Remove AfreecaTV.
yt-dlp/yt-dlp pull request #11266
Opened 2024-10-16 17:51 UTC by 63427083

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Removed AfreecaTV.
Added Soop.
No "Sooplive" to keep consistency with streamlink.

Fixes #11253

**Preword:**
I had some errors running 'hatch', predominately "EOFError: marshal data too short" for reasons i have yet to figure out.
The code itself works as intended though, most of it is just copy-paste anyway.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))

</details>

2024-10-16 17:55 UTC, bashonly commented
are the extractors basically the same as AfreecaTV but with different domains? are the same VOD IDs that were available on AfreecaTV now available on Soop?

2024-10-16 18:01 UTC, 63427083 commented
> are the extractors basically the same as AfreecaTV but with different domains? are the same VOD IDs that were available on AfreecaTV now available on Soop?

Yes.

2024-10-16 18:02 UTC, bashonly commented
do afreecatv URLs now redirect to sooplive?

2024-10-16 18:06 UTC, jouven commented
To clear any possible confusion afreecatv.com redirects to sooplive.co.kr. sooplive.com is something else (international version¿), anyway sooplive.com and sooplive.co.kr are different..

2024-10-16 18:10 UTC, bashonly commented
The way this should be handled is that we keep the `afreecatv.py` module and we keep the `AfreecaTV` extractors; and only update the `IE_NAME`, `IE_DESC`, `_VALID_URL`s and relevant code

2024-10-16 18:13 UTC, 63427083 commented
> do afreecatv URLs now redirect to sooplive?

Yes and no.
Most do, basically all the with basedomain sooplive. 
Some kept some weird "afreeca" shortcuts.
Yes, i tested those regarding logins, as i asked myself the same question.

 

> To clear any possible confusion afreecatv.com redirects to sooplive.co.kr. sooplive.com is something else (international version¿), anyway sooplive.com and sooplive.co.kr are different..

This is for sooplive.co.kr. _the_ afreecatv successor. 



> The way this should be handled is that we keep the `afreecatv.py` module and we keep the `AfreecaTV` extractors; and only update the `IE_NAME`, `IE_DESC`, `_VALID_URL`s and relevant code. Do not duplicate / add new `Soop` extractors
> 
> Ideally the `_VALID_URL`s would match both domains for now
> 
> We may need to do a cookie scope fix workaround like we did for Twitter=>X

I'd have to look into that.

2024-10-16 18:15 UTC, bashonly commented
> We may need to do a cookie scope fix workaround like we did for Twitter=>X

Don't worry about this for now, I can add a more specific suggestion for it after my other requested changes have been addressed

2024-10-21 06:31 UTC, bashonly requested changes
I partially reverted your initial commit to comply with my request. It should be pretty easy to finish this one up now. I do have some questions / further suggestions though

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +    _NETRC_MACHINE = 'soop'
not sure about changing this

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
>                              )\?.*?\bnTitleNo=|
do links like these even exist anymore? it seems like all VODs are on the `vod` subdomain now, no?

if we want to keep this part of the regex pattern for legacy reasons or something, we should turn back the clock on the domain name here too
```suggestion
                            (?:(?:live|afbbs|www)\.)?afreecatv.\com(?::\d+)?
                            (?:
                                /app/(?:index|read_ucc_bbs)\.cgi|
                                /player/[Pp]layer\.(?:swf|html)
                            )\?.*?\bnTitleNo=|
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +                            vod\.sooplive\.co\.kr/(PLAYER/STATION|player)/
```suggestion
                            vod\.(?:sooplive\.co\.kr|afreecatv\.com)/(?:PLAYER/STATION|player)/
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +        'url': 'http://live.sooplive.co.kr:8079/app/index.cgi?szType=read_ucc_bbs&szBjId=dailyapril&nStationNo=16711924&nBbsNo=18605867&nTitleNo=36164052&szSkin=',
Revert; changing dead URLs to non-existent URLs doesn't make sense. If this type of URL doesn't exist anymore then we should just remove these tests entirely

```suggestion
        'url': 'http://live.afreecatv.com:8079/app/index.cgi?szType=read_ucc_bbs&szBjId=dailyapril&nStationNo=16711924&nBbsNo=18605867&nTitleNo=36164052&szSkin=',
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +            'thumbnail': 're:^https?://(?:video|st)img.sooplive.co.kr/.*$',
should not be changing dead tests
```suggestion
            'thumbnail': 're:^https?://(?:video|st)img.afreecatv.com/.*$',
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +        'url': 'http://afbbs.sooplive.co.kr:8080/app/read_ucc_bbs.cgi?nStationNo=16711924&nTitleNo=36153164&szBjId=dailyapril&nBbsNo=18605867',
same as above
```suggestion
        'url': 'http://afbbs.afreecatv.com:8080/app/read_ucc_bbs.cgi?nStationNo=16711924&nTitleNo=36153164&szBjId=dailyapril&nBbsNo=18605867',
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +            'thumbnail': 're:^https?://(?:video|st)img.sooplive.co.kr/.*$',
```suggestion
            'thumbnail': 're:^https?://(?:video|st)img.afreecatv.com/.*$',
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +        'url': 'http://www.sooplive.co.kr/player/Player.swf?szType=szBjId=djleegoon&nStationNo=11273158&nBbsNo=13161095&nTitleNo=36327652',
```suggestion
        'url': 'http://www.afreecatv.com/player/Player.swf?szType=szBjId=djleegoon&nStationNo=11273158&nBbsNo=13161095&nTitleNo=36327652',
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +    _VALID_URL = r'https?://vod\.sooplive\.co\.kr/player/(?P<id>\d+)/catchstory'
```suggestion
    _VALID_URL = r'https?://vod\.(?:sooplive\.co\.kr|afreecatv\.com)/player/(?P<id>\d+)/catchstory'
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +    _VALID_URL = r'https?://play\.sooplive\.co\.kr/(?P<id>[^/]+)(?:/(?P<bno>\d+))?'
```suggestion
    _VALID_URL = r'https?://play\.(?:sooplive\.co\.kr|afreecatv\.com)/(?P<id>[^/?#]+)(?:/(?P<bno>\d+))?'
```

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +        'gs_cdn_pc_web',  # pc-web.stream.sooplive.co.kr
are all these CDN domains confirmed?

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +        'kt_cdn',  # kt.stream.sooplive.co.kr (HTTP Error 400)
same question here

2024-10-21 06:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +    _VALID_URL = r'https?://ch\.sooplive\.co\.kr/(?P<id>[^/]+)/vods/?(?P<slug_type>[^/]+)?'
```suggestion
    _VALID_URL = r'https?://ch\.(?:sooplive\.co\.kr|afreecatv\.com)/(?P<id>[^/?#]+)/vods/?(?P<slug_type>[^/?#]+)?'
```

2024-10-21 06:34 UTC, bashonly commented
cc @hui1601 would you like to take a look at this?

2024-10-21 07:07 UTC, hui1601 commented
> No “Sooplive” to keep consistency with streamlink.

In my opinion, there is already a PR (#10136) to add `SoopGlobal` extractor, so I think it should be changed to `SoopKorea` or `Soop` or something like that, for future code management.
Is there any reason why we need to match the name of the streamlink?

2024-10-21 22:16 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +                            (?:(?:live|afbbs|www)\.)?afreecatv.\com(?::\d+)?
```suggestion
                            (?:(?:live|afbbs|www)\.)?afreecatv\.com(?::\d+)?
```

2024-10-21 22:31 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +    _NETRC_MACHINE = 'soop'
```suggestion
    _NETRC_MACHINE = 'afreecatv'
```
we can change in the future, for now let's keep it the same to not break users' netrc files

2024-10-21 22:35 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +            'thumbnail': 're:https?://(?:video|st)img\.sooplive\.co\.kr/.+',
```suggestion
            'thumbnail': r're:https?://(?:video|st)img\.sooplive\.co\.kr/.+',
```

2024-10-21 22:35 UTC, bashonly commented on yt_dlp/extractor/afreecatv.py
> +            'thumbnail': 're:https?://(?:video|st)img\.sooplive\.co\.kr/.+',
```suggestion
            'thumbnail': r're:https?://(?:video|st)img\.sooplive\.co\.kr/.+',
```

2024-10-21 22:54 UTC, bashonly approved these changes
I think this looks good now. As for the `IE_NAME`, we can adjust that as needed when finishing up and merging the soopglobal PR. It's not a big deal to change the `IE_NAME`, not like how changing the extractor class name is

2024-10-21 23:34 UTC, seproDev approved these changes

2024-10-21 23:38 UTC, bashonly commented
Also, I'm not implementing a cookies migration domain-switch workaround like we did for Twitter because I have faith in this site having a higher competency level than Twitter. If we get reports of problems, then we can add the domain switch hack

2024-10-21 23:42 UTC, merged

2025-06-11 02:19 UTC, NormanMises commented
请问有支持 sooplive.com 的计划吗？我想下载上面的视频，比如 https:www.sooplive.com/video/121620

Is there a plan to support sooplive.com? I want to download videos from there, for example https:www.sooplive.com/video/121620

2025-06-11 02:24 UTC, hui1601 commented
> 请问有支持 sooplive.com 的计划吗？我想下载上面的视频，比如 https:www.sooplive.com/video/121620
> 
> Is there a plan to support sooplive.com? I want to download videos from there, for example https:www.sooplive.com/video/121620
> @NormanMises 
There is already an issue about this.
See #10066.

2025-06-11 02:27 UTC, NormanMises commented
> > 请问有支持 sooplive.com 的计划吗？我想下载上面的视频，比如 https:www.sooplive.com/video/121620
> > Is there a plan to support sooplive.com? I want to download videos from there, for example https:www.sooplive.com/video/121620
> > @NormanMises
> 
> There is already an issue about this. See #10066.

thanks！！！ Truly Need it！！！