[ie/yle_areena] Fix live events
yt-dlp/yt-dlp pull request #11358
Opened 2024-10-26 12:14 UTC by CounterPillow

Fixes extraction of manifests for live events.

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Previously, YLE live events like the [pupper stream](https://areena.yle.fi/1-72251830) would fail extraction with the following traceback:
```
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/yle_areena.py", line 118, in _real_extract
    video_data['data']['ongoing_ondemand']['manifest_url'], video_id, 'mp4', m3u8_id='hls')
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'ongoing_ondemand'
```

This change fixes it.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-10-26 13:16 UTC, bashonly requested changes

2024-10-26 13:16 UTC, bashonly commented on yt_dlp/extractor/yle_areena.py
> +                ongoing = video_data['data']['ongoing_event']
I'd do this, and then also set `is_live = False` before the `if is_podcast:` line up above, as well as returning `'is_live': is_live` in the info dict below
```suggestion
            if traverse_obj(video_data, ('data', 'ongoing_ondemand', 'manifest_url', {url_or_none})):
                manifest_url = video_data['data']['ongoing_ondemand']['manifest_url']
            elif traverse_obj(video_data, ('data', 'ongoing_event', 'manifest_url', {url_or_none})):
                manifest_url = video_data['data']['ongoing_event']['manifest_url']
                is_live = True
            else:
                raise ExtractorError('Unable to extract manifest URL')
```

really the whole extractor could use a good refactoring (e.g. we don't access anything outside of the `'data'` branch in the `video_data` JSON, etc), but that's not necessary now

2024-10-26 13:17 UTC, bashonly commented on yt_dlp/extractor/yle_areena.py
> +                ongoing['manifest_url'], video_id, 'mp4', m3u8_id='hls')
```suggestion
                'manifest_url', video_id, 'mp4', m3u8_id='hls', live=is_live)
```

2024-10-26 13:18 UTC, bashonly commented
could you also add `https://areena.yle.fi/1-72251830` as a test?

2024-10-26 16:03 UTC, CounterPillow commented
> could you also add `https://areena.yle.fi/1-72251830` as a test?

That would make very little sense as that test would break/change behaviour as soon as the stream is no longer live.

2024-10-26 16:05 UTC, bashonly commented
You can mark it skip. I just want to have 1 livestream case in there. This is common among all extractors that support livestreams

2024-10-27 21:42 UTC, CounterPillow commented
Sure, made your changes and added a test case, I didn't mark it skip though because all the other tests are also failing anyway so what's another one that'll be broken in a few days time.

2024-10-28 04:17 UTC, bashonly approved these changes

2024-10-31 23:23 UTC, merged