[ie/atresplayer] Fixed AtresPlayer extractor
yt-dlp/yt-dlp pull request #11424
Opened 2024-11-01 11:22 UTC by meGAmeS1

### Description of your *pull request* and other information

Fixed how the authentication was done and how extraction was made

Fixes #996

I saw the PR #1165 but it was too outdated and it seems to work better with what I did (for example I tried the URL mentioned [in this comment](https://github.com/yt-dlp/yt-dlp/pull/1165#issuecomment-1780591654) and it worked)

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)

</details>

2025-04-13 21:00 UTC, acrilique commented
I have just tested this and it does fix downloading from the current atresplayer website with the following steps:
```bash
git clone https://github.com/yt-dlp/yt-dlp/
gh pr checkout 11424
./yt-dlp.sh -u user@example.com -p secret https://www.atresplayer.com/...
```
Would love to see it merged

2025-04-13 21:13 UTC, meGAmeS1 commented
@acrilique Thank you for the verification, please feel free to add a reaction to the initial post of this PR to give it more visibility

2025-04-13 21:18 UTC, seproDev commented
The current code does not work on all videos. I would also rather fix the subtitle extraction than just dropping in entirely. Let me push something.

2025-04-13 21:22 UTC, meGAmeS1 commented
Feel free to take the PR back with your code, it's not a site I can test very easily if I remember well.

And thank you for looking into it (sorry if I didn't come back yet on my other PR about RTVE, personal life took me a bit of my free time these days)

2025-04-13 21:25 UTC, seproDev commented
All good, I will just take over this PR. I think I found enough free videos to test with.

2025-04-13 22:28 UTC, acrilique commented
Something's wrong with this last 2 commits, just tested with the same video as before and the audio track it's trying to fetch is named incorrectly it seems. 

with [f36c8a7](https://github.com/yt-dlp/yt-dlp/pull/11424/commits/f36c8a726fe5ccc7b97e1b40dee7237fca35c847)
```
[AtresPlayer] Logging in
[AtresPlayer] Extracting URL: https://www.atresplayer.com/lasexta/programas/lo-de-evole/temporada-6/gabriel-rufian_67c1d03956a8c60007739390/
[AtresPlayer] 67c1d03956a8c60007739390: Downloading JSON metadata
[AtresPlayer] 67c1d03956a8c60007739390: Downloading m3u8 information
WARNING: [AtresPlayer] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[AtresPlayer] 67c1d03956a8c60007739390: Downloading MPD manifest
WARNING: [AtresPlayer] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] 67c1d03956a8c60007739390: Downloading 1 format(s): dash-p0va0br1637372+dash-p0aa0br128000
[dashsegments] Total fragments: 1669
[download] Destination: Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0va0br1637372.mp4
[download] 100% of  652.53MiB in 00:01:01 at 10.53MiB/s
[dashsegments] Total fragments: 1669
[download] Destination: Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0aa0br128000.m4a
[download] 100% of   53.71MiB in 00:00:52 at 1.02MiB/s
[Merger] Merging formats into "Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].mp4"
Deleting original file Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0va0br1637372.mp4 (pass -k to keep)
Deleting original file Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0aa0br128000.m4a (pass -k to keep)
```
note it's fetching p0va0br for video and p0aa1br for audio

however with the last commits:
```
[AtresPlayer] Logging in
[AtresPlayer] Extracting URL: https://www.atresplayer.com/lasexta/programas/lo-de-evole/temporada-6/gabriel-rufian_67c1d03956a8c60007739390/
[AtresPlayer] 67c1d03956a8c60007739390: Downloading API Endpoint Data
[AtresPlayer] 67c1d03956a8c60007739390: Downloading JSON metadata
[AtresPlayer] 67c1d03956a8c60007739390: Downloading video data
[AtresPlayer] 67c1d03956a8c60007739390: Downloading m3u8 information
[AtresPlayer] 67c1d03956a8c60007739390: Downloading MPD manifest
[AtresPlayer] 67c1d03956a8c60007739390: Downloading m3u8 information
[AtresPlayer] 67c1d03956a8c60007739390: Downloading MPD manifest
[info] 67c1d03956a8c60007739390: Downloading 1 format(s): dash-p0va0br1637372-1+dash-p0aa1br128000
[dashsegments] Total fragments: 1669
[download] Destination: Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0va0br1637372-1.mp4
[download] 100% of  652.53MiB in 00:01:08 at 9.54MiB/s
[dashsegments] Total fragments: 1669
[download] Destination: Gabriel Rufián (Parte 1) [67c1d03956a8c60007739390].fdash-p0aa1br128000.m4a
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 404: Not Found. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
```
the audio file is called differently `p0aa1br` instead of `p0aa0br` and it does not find it

2025-04-13 22:36 UTC, seproDev commented
Thanks for reporting. Seem like in `application/dashvo+xml` dashvo means video only and the audio formats in the mpd just 404 🙃
I added a commit to skip those formats.

2025-04-13 23:13 UTC, seproDev approved these changes

2025-04-14 20:00 UTC, acrilique commented
That has fixed the issue on my end, and there's no warning about subtitles. I should note that, for the video I tested which has a subtitle track available on the website, the program isn't able to extract any subtitle tracks.

2025-04-15 04:15 UTC, seproDev commented
Can you please share an example URL? Testing with https://www.atresplayer.com/flooxer/series/biara-proyecto-lazarus/temporada-1/capitulo-3-supervivientes_67a6038b64ceca00070f4f69/ the subtitles download fine for me.

2025-04-16 10:20 UTC, acrilique commented
Here you go @seproDev https://www.atresplayer.com/lasexta/programas/lo-de-evole/temporada-6/gabriel-rufian_67c1d03956a8c60007739390/

2025-04-16 10:54 UTC, acrilique commented
Adding the --write-subs flag did the trick. Sorry for the confusion, I'm not a regular user of the tool and I thought subtitles worked like audio/video.

2025-04-18 19:41 UTC, bashonly requested changes

2025-04-18 19:41 UTC, bashonly commented on yt_dlp/extractor/atresplayer.py
> +    _VALID_URL = r'https?://(?:www\.)?atresplayer\.com/[^/?#]+/[^/?#]+/[^/?#]+/[^/?#]+/(?P<display_id>.+?)_(?P<id>[0-9a-f]{24})'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?atresplayer\.com/(?:[^/?#]+/){4}(?P<display_id>.+?)_(?P<id>[0-9a-f]{24})'
```

2025-04-18 19:41 UTC, bashonly commented on yt_dlp/extractor/atresplayer.py
> +                'timestamp': ('publicationDate', {float_or_none(scale=1000)}),
```suggestion
                'timestamp': ('publicationDate', {int_or_none(scale=1000)}),
```

2025-04-18 19:41 UTC, bashonly commented on yt_dlp/extractor/atresplayer.py
> +                'Logging in', data=urlencode_postdata({
```suggestion
                'Logging in', 'Failed to log in', data=urlencode_postdata({
```

2025-04-18 19:41 UTC, bashonly commented on yt_dlp/extractor/atresplayer.py
> +        metadata = self._download_json(url_data['href'], video_id)
```suggestion
        metadata_url = self._download_json(
            self._API_BASE + 'client/v1/url', video_id, 'Downloading API endpoint data',
            query={'href': urllib.parse.urlparse(url).path})['href']
        metadata = self._download_json(metadata_url, video_id)
```

2025-04-18 19:41 UTC, bashonly commented on yt_dlp/extractor/atresplayer.py
> +            video_data = self._download_json(metadata['urlVideo'], video_id, note='Downloading video data')
```suggestion
            video_data = self._download_json(metadata['urlVideo'], video_id, 'Downloading video data')
```

2025-04-18 20:03 UTC, seproDev commented on yt_dlp/extractor/atresplayer.py
> +    float_or_none,
```suggestion
```

2025-04-18 20:07 UTC, bashonly approved these changes

2025-04-18 20:12 UTC, merged