[cleanup] Deprecate more compat functions
yt-dlp/yt-dlp pull request #11439
Opened 2024-11-02 22:26 UTC by seproDev

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Some minor cleanup work

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-11-05 04:44 UTC, grqz commented
<details><summary>patch:

lets also deprecate `yt_dlp.utils.compiled_regex_type`
</summary>

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 623121d76..a198be4a8 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -312,6 +312,7 @@ banned-from = [
 "yt_dlp.compat.compat_urllib_parse_urlencode".msg = "Use `urllib.parse.urlencode` instead."
 "yt_dlp.compat.compat_urllib_parse_urlparse".msg = "Use `urllib.parse.urlparse` instead."
 "yt_dlp.compat.compat_shlex_quote".msg = "Use `yt_dlp.utils.shell_quote` instead."
+"yt_dlp.utils.compiled_regex_type".msg = "Use `re.Pattern` instead."
 "yt_dlp.utils.error_to_compat_str".msg = "Use `str` instead."
 "yt_dlp.utils.bytes_to_intlist".msg = "Use `list` instead."
 "yt_dlp.utils.intlist_to_bytes".msg = "Use `bytes` instead."
diff --git a/yt_dlp/utils/_legacy.py b/yt_dlp/utils/_legacy.py
index d65b135d9..b64331fdd 100644
--- a/yt_dlp/utils/_legacy.py
+++ b/yt_dlp/utils/_legacy.py
@@ -16,6 +16,7 @@
 from ..networking._urllib import HTTPHandler
 
 # isort: split
+from re import Pattern as compiled_regex_type  # noqa: F401
 from .networking import escape_rfc3986  # noqa: F401
 from .networking import normalize_url as escape_url
 from .networking import random_user_agent, std_headers  # noqa: F401
diff --git a/yt_dlp/utils/_utils.py b/yt_dlp/utils/_utils.py
index 7fd0ed2a4..c5396789f 100644
--- a/yt_dlp/utils/_utils.py
+++ b/yt_dlp/utils/_utils.py
@@ -54,9 +54,6 @@
 
 __name__ = __name__.rsplit('.', 1)[0]  # noqa: A001: Pretend to be the parent module
 
-# This is not clearly defined otherwise
-compiled_regex_type = type(re.compile(''))
-
 
 class NO_DEFAULT:
     pass
```

</details>

2024-11-11 17:39 UTC, bashonly commented
> 6b293bbeb368e50ade03d6fdff9f1c8a75c6d412 [Only warn for deprecated not legacy](https://github.com/yt-dlp/yt-dlp/pull/11439/commits/6b293bbeb368e50ade03d6fdff9f1c8a75c6d412)

IMO revert this. Devs should be warned for both via linter. Only legacy should warn during runtime

2024-11-12 01:03 UTC, bashonly requested changes

2024-11-12 01:03 UTC, bashonly commented on yt_dlp/extractor/adn.py
>          }))
this is wrong
```suggestion
        message = list(json.dumps({
            'k': self._K,
            't': token,
        }).encode())
```

2024-11-12 01:03 UTC, bashonly commented on yt_dlp/extractor/anvato.py
> +            list(input_data[:64]), list(self._AUTH_KEY)))
this is wrong, throws now

2024-11-12 01:09 UTC, bashonly commented
This was just what I notcied, but I think all of the `bytes_to_intlist` and `intlist_to_bytes` replacements need to be scrutinized more closely

2024-11-12 22:26 UTC, bashonly commented on yt_dlp/extractor/anvato.py
> +            list(input_data[:64]).encode(), list(self._AUTH_KEY)))
still wrong, need to ecode the data being cast to list, not encode the list
```suggestion
            list(input_data[:64].encode()), list(self._AUTH_KEY)))
```

2024-11-16 22:04 UTC, bashonly approved these changes

2024-11-16 23:00 UTC, bashonly approved these changes

2024-11-16 23:12 UTC, bashonly approved these changes

2024-11-16 23:12 UTC, bashonly commented on yt_dlp/extractor/shemaroome.py
> +        iv = bytes([0] * 16)
```suggestion
        iv = bytes(16)
```

2024-11-16 23:16 UTC, Grub4K approved these changes

2024-11-16 23:24 UTC, merged