Bilibili add subtitle converter
yt-dlp/yt-dlp pull request #1144
Opened 2021-10-02 09:20 UTC by u-spec-png

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes #1015, code taken from https://github.com/y2361547758/bcc2ass.

2021-10-02 09:54 UTC, Ashish0804 commented
How can you be the original author as well as not the original author? 
Fix it please.

2021-10-02 11:48 UTC, pukkandan commented
@Ashish0804 He wrote some of it, while other parts are from another repo

2021-10-02 17:00 UTC, pukkandan requested changes

2021-10-02 17:19 UTC, u-spec-png commented on yt_dlp/extractor/bilibili.py
> +            video_info = vid.get('stream_info', {})
Isn't this the same as `or`?  [docs](https://docs.python.org/3/library/stdtypes.html#dict.get)

2021-10-02 17:25 UTC, pukkandan commented on yt_dlp/extractor/bilibili.py
> +            video_info = vid.get('stream_info', {})
Try running `{'key': None}.get('key', 'default')` and `{'key': None}.get('key') or 'default'` to see the difference

2021-10-02 18:52 UTC, pukkandan commented on yt_dlp/extractor/bilibili.py
> +            sub_data = self._download_json(sub_url, ep_id)
you didnt add note

2021-10-02 18:53 UTC, pukkandan commented
btw, is there any code remaining from https://github.com/y2361547758/bcc2ass now? It looks to me like you completely rewrote everything

2021-10-02 19:54 UTC, u-spec-png commented
> btw, is there any code remaining from https://github.com/y2361547758/bcc2ass now? It looks to me like you completely rewrote everything

no

2021-10-04 18:37 UTC, merged

2021-10-06 07:56 UTC, riyuejz commented
yt-dlp -F --cookies '/home/lynx/ytdlp/cookies.txt' https://www.biliintl.com/en/play/1005426/10499657
[BiliIntl] 10499657: Downloading JSON metadata
[BiliIntl] 10499657: Downloading JSON metadata
[BiliIntl] 10499657: Downloading JSON metadata
[BiliIntl] 10499657: Downloading JSON metadata
ERROR: _parse_json() missing 1 required positional argument: 'video_id'