[ie/patreon] Fix crash (AttributeError) caused by attempting to parse something that isn't actually a comment
yt-dlp/yt-dlp pull request #11530
Opened 2024-11-13 18:06 UTC by jshumphrey

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

The issue appeared to have to do with comments that replied to other comments. These comment objects, in the 'included' block, could be picked up by the traverse_obj call, but were not actually parse-able as comments.

In the attached JSON and screenshot, the string `"153434567"` (the inner red box) is the object referenced by the `comment` variable at the time of the crash, which leads to the `AttributeError` and the crashout. Moving `comment.get('id')` into a `try_call`, and moving the `comment_id is not None` check to the very beginning of the loop body resolved the issue.

Fixes #11483 

![11483](https://github.com/user-attachments/assets/283f79a3-e936-4de1-b3be-84033ffd0d93)
[11483.json](https://github.com/user-attachments/files/17737236/11483.json)

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [X] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-11-13 18:37 UTC, bashonly requested changes

2024-11-13 18:37 UTC, bashonly commented on yt_dlp/extractor/patreon.py
>              for comment in traverse_obj(response, (('data', ('included', lambda _, v: v['type'] == 'comment')), ...)):
The real problem is that the traversal path here is incorrect, thus the filtering it's trying to do is ineffective. Let's change it to this:
```suggestion
            for comment in traverse_obj(response, (('data', 'included'), lambda _, v: v['type'] == 'comment' and v['id'])):
```

2024-11-13 18:37 UTC, bashonly commented on yt_dlp/extractor/patreon.py
> +                attributes = comment.get('attributes') or {}
then this block can be simplified to:
```py
                comment_id = comment['id']
                attributes = traverse_obj(comment, ('attributes', {dict})) or {}
```

2024-11-13 18:39 UTC, bashonly commented on yt_dlp/extractor/patreon.py
> +                attributes = comment.get('attributes') or {}
then:
```suggestion
                comment_id = comment['id']
                attributes = traverse_obj(comment, ('attributes', {dict})) or {}
```

2024-11-13 19:06 UTC, bashonly approved these changes

2024-11-16 19:40 UTC, bashonly commented on yt_dlp/extractor/patreon.py
> +                        'id': 'id',
```suggestion
                        'id': ('id', {str_or_none}),
```

2024-11-16 19:41 UTC, seproDev approved these changes

2024-11-16 20:02 UTC, merged