[ie/ctvnews] Fix extractor failing to find video on certain pages
yt-dlp/yt-dlp pull request #11534
Opened 2024-11-14 00:13 UTC by jshumphrey

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This PR applies [the patch provided by dirkf](https://github.com/yt-dlp/yt-dlp/issues/8689#issuecomment-1835207570) in Issue #8689, and updates the tests accordingly. All tests for this extractor now pass.

Fixes #8689 
May supersede #8892 and allow for its closure.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
  - @dirkf, can you sign off on the use of your patch?

### What is the purpose of your *pull request*?
- [X] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-11-15 21:00 UTC, bashonly approved these changes
just formatting things

2024-11-15 21:00 UTC, bashonly commented on yt_dlp/extractor/ctvnews.py
> +        },
```suggestion
        'info_dict': {
            'id': '1.6665797',
        },
```

2024-11-15 21:00 UTC, bashonly commented on yt_dlp/extractor/ctvnews.py
> +                        re.findall(r'axisId&#34;:&#34;(\d+)', webpage))]
```suggestion
                    entries = [ninecninemedia_url_result(clip_id)
                                    for clip_id in orderedSet(re.findall(r'axisId&#34;:&#34;(\d+)', webpage))]
```

2024-11-17 19:05 UTC, seproDev requested changes
Imo. the `if page_id.isdigit():` path should be removed entirely as it is not accurate and sometimes a page can contain multiple videos.
The VALID_URL regex should also be fixed since URLs such as `https://www.ctvnews.ca/canada/apparent-taylor-swift-ticket-scam-targets-hundreds-who-claim-to-be-out-300k-1.7113362` currently get the id `300`

2024-11-17 19:12 UTC, bashonly commented
`_VALID_URL` / playlist ID extraction fix is in https://github.com/yt-dlp/yt-dlp/pull/8892

2024-11-17 21:03 UTC, seproDev approved these changes

2024-11-17 21:06 UTC, merged