[ie/BunnyCDN] Add extractor
yt-dlp/yt-dlp pull request #11586
Opened 2024-11-20 01:47 UTC by seproDev

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Adds extractor for BunnyCDN Stream

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2025-02-17 00:05 UTC, bashonly requested changes

2025-02-17 00:05 UTC, bashonly commented on yt_dlp/extractor/bunnycdn.py
> +                    'filesize': int_or_none(urlh.headers.get('Content-Length')),
```suggestion
                    'filesize': int_or_none(urlh.get_header('Content-Length')),
```

2025-02-17 00:05 UTC, bashonly commented on yt_dlp/extractor/bunnycdn.py
> +            **self._search_json_ld(webpage, video_id, fatal=False),
do we want the json ld data to overwrite everything else?

2025-02-17 16:36 UTC, seproDev commented on yt_dlp/extractor/bunnycdn.py
> +            **self._search_json_ld(webpage, video_id, fatal=False),
I would trust the json-ld data more than the plyr config to provide accurate data. Though in all cases I found they actually match.

2025-02-21 21:25 UTC, Grub4K approved these changes

2025-02-21 21:39 UTC, merged