[ie/globo] Fix extractor
yt-dlp/yt-dlp pull request #11795
Opened 2024-12-13 01:24 UTC by slipinthedove

### Description of your *pull request* and other information

Fixes the Globo extractor by using the most recent and generally-accepted versions of it's respective APIs, including upgrading the video-session route to a non-deprecated version.

Should (in theory) fix #9512, supercedes #11772 by not needing the `ab-globo` route altogether and generally cleans the extractor logic quite a bit. Takes a more extensive approach to the patch provided by @bashonly in #11541.

<details open><summary>Template</summary>

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)

</details>

2024-12-13 02:05 UTC, bashonly commented on yt_dlp/extractor/globo.py
> -        'only_matching': True,
If we are removing all these tests, does that mean these URL formats are no longer valid? If so, then we should tighten up the `_VALID_URL` regex too

2024-12-13 02:06 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +        if not self.get_param('allow_unplayable_formats') and security['resource'].get('drm_protection_enabled') is True:
we're not doing that unplayable param anymore
```suggestion
        if traverse_obj(video, ('resource', 'drm_protection_enabled', {bool})):
```

2024-12-13 02:08 UTC, bashonly commented on yt_dlp/extractor/globo.py
>          security = self._download_json(
I don't like continuing to name this variable `security` when we've removed all the security hash code. I changed it in my patch for a reason

2024-12-13 02:08 UTC, bashonly commented on yt_dlp/extractor/globo.py
>                  })
IMO we should use `traverse_obj` and `subs_list_to_dict` here

2024-12-13 02:09 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +            headers={'content-type': 'application/json', 'x-platform-id': 'web', 'x-device-id': 'desktop', 'x-client-version': '2024.12-5'})['data']['video']
lines too long. use `query` kwarg instead of putting it all into the url string

2024-12-13 02:09 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +        '''
class constant

2024-12-13 02:10 UTC, bashonly commented
Now that reviewing has commenced, please refrain from force pushing

2024-12-20 22:34 UTC, YoshiTabletopGamer commented
The parameter vsid is actually random hex, as generated from the JS:

          key: 's4',
          value: function () {
            return Math.floor(65536 * (1 + Math.random())).toString(16).substring(1)
          }
        },
        {
          key: 'generate',
          value: function () {
            return ''.concat(this.s4() + this.s4(), '-').concat(this.s4(), '-').concat(this.s4(), '-').concat(this.s4(), '-').concat(this.s4()).concat(this.s4()).concat(this.s4())
          }

So, you can make them random like this `'-'.join(''.join(random.choices(string.hexdigits.lower(), k=n)) for n in [8, 4, 4, 4, 12])`

2024-12-20 22:37 UTC, YoshiTabletopGamer commented
Also, the sources from the JSON response of video-session have fallbacks, which apparently are used if the primary source is down.

2024-12-20 23:12 UTC, YoshiTabletopGamer commented
Yep, [626a901](https://github.com/yt-dlp/yt-dlp/pull/11795/commits/626a9015845779d736e7cf876ae22a2c08d282c7) is now showing 1080p.

> python -m yt_dlp -vU -F --cookies-from-browser Firefox "https://globoplay.globo.com/v/13198311/?s=0s"
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'Firefox', 'https://globoplay.globo.com/v/13198311/?s=0s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (source) 
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: d298693b1 
[debug] Python 3.12.7 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.15 3 Sep 2024) 
[debug] exe versions: ffmpeg 7.1-essentials_build-www.gyan.dev (setts), ffprobe 7.1-essentials_build-www.gyan.dev 
[debug] Optional libraries: brotlicffi-1.1.0.0, certifi-2024.08.30, pycrypto-3.21.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3 
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\[redacted]\AppData\Roaming\Mozilla\Firefox\Profiles\j9el7lul.default-release\cookies.sqlite" 
Extracted 1005 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[Globo] Extracting URL: https://globoplay.globo.com/v/13198311/?s=0s 
[Globo] 13198311: Downloading JSON metadata 
[Globo] 13198311: Downloading resource info for 13198311 
[Globo] 13198311: Downloading m3u8 information 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 13198311: 
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     ABR
───────────────────────────────────────────────────────────────────────────────────
hls-404  mp4 640x360    │ ~130.46MiB  404k m3u8  │ avc1.64001E  251k mp4a.40.2 128k
hls-1050 mp4 854x480    │ ~339.07MiB 1050k m3u8  │ avc1.64001F  861k mp4a.40.2 128k
hls-1914 mp4 1280x720   │ ~618.07MiB 1914k m3u8  │ avc1.64001F 1676k mp4a.40.2 128k
hls-5007 mp4 1920x1080  │ ~  1.58GiB 5007k m3u8  │ avc1.640028 4594k mp4a.40.2 128k

2025-01-15 21:30 UTC, YoshiTabletopGamer commented
Hey, @slipinthedove , how did you find this 8k client? I was thinking of reverse engineering the Android app to find a way to do this, but you have done it! I hadn't found an 8k client on the web client's JavaScript.

2025-01-26 02:59 UTC, bashonly requested changes

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +    _VALID_URL = r'https?://(?!globoplay).+?\.globo\.com/(?:[^/]+/)*(?P<id>[^/.]+)(?:\.html)?'
```suggestion
    _VALID_URL = r'https?://(?!globoplay).+?\.globo\.com/(?:[^/?#]+/)*(?P<id>[^/?#.]+)(?:\.html)?'
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +        if main_source['url'].endswith('mpd'):
```suggestion
        if determine_ext(main_source['url']) == 'mpd':
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +                main_source['url'], video_id, 'mp4', fatal=False)
the 3rd positional argument is `mpd_id` and there's no reason for these to be non-fatal
```suggestion
            formats, subtitles = self._extract_mpd_formats_and_subtitles(main_source['url'], video_id, mpd_id='dash')
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +                main_source['url'], video_id, 'mp4', 'm3u8_native', m3u8_id='hls', fatal=False)
```suggestion
            formats, subtitles = self._extract_m3u8_formats_and_subtitles(main_source['url'], video_id, 'mp4', m3u8_id='hls')
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +        }, all, {subs_list_to_dict})), target=subtitles)
replace `en` if that's not the expected lang of course
```suggestion
            'url': ('subtitle', 'srt', 'url', {url_or_none}),
        }, all, {subs_list_to_dict(lang='en'})), target=subtitles)
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +                                         lambda x: f'Bearer {x["GLBID"].value}') or '',
weird that this is in the payload instead of the headers?

but anyways, maybe call `filter_dict` on the whole payload dict to just remove `Authorization` if the value is `None`?

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +                'variables': f'{{"videoId":{video_id}}}',
maybe overkill but I really hate trying to decipher the `}}}`s

use `separators` param if the default whitespace is a problem for the graphql

```suggestion
                'variables': json.dumps({'videoId': video_id}),
```

2025-01-26 02:59 UTC, bashonly commented on yt_dlp/extractor/globo.py
> +    _VALID_URL = r'(?:globo:|https?://.+?\.globo\.com/(?:[^/]+/))(?P<id>\d{7,})'
```suggestion
    _VALID_URL = r'(?:globo:|https?://[^/?#]+?\.globo\.com/(?:[^/?#]+/))(?P<id>\d{7,})'
```

2025-01-26 20:16 UTC, YoshiTabletopGamer commented on yt_dlp/extractor/globo.py
> +        }, all, {subs_list_to_dict})), target=subtitles)
Hmm, of course, while Globo is Brazilian (Portuguese), some content might have subtitles in multiple languages.

2025-01-27 18:16 UTC, bashonly approved these changes

2025-01-27 18:16 UTC, bashonly commented on yt_dlp/extractor/globo.py
>                                           lambda x: f'Bearer {x["GLBID"].value}') or '',
```suggestion
                                         lambda x: f'Bearer {x["GLBID"].value}'),
```

2025-01-29 23:55 UTC, merged