[soundcloud] Add playlist uploader and uploader_id info
yt-dlp/yt-dlp pull request #11945
Opened 2024-12-29 19:06 UTC by 7x11x13

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Adds `uploader` and `uploader_id` information when extracting SoundCloud playlists.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2025-01-04 04:38 UTC, 7x11x13 commented
Added some more fields that were missing

2025-01-04 05:18 UTC, 7x11x13 commented
Actually I'm confused - is the `album` field supposed to be set on the playlist info, or does it only make sense in each track entry? I see in the Bandlab extractor the field is set on the playlist, but the output template documentation seems to suggest otherwise. If that's the case, is there an easy way to set the field on each of the track entries during the playlist extraction process?

2025-01-25 18:14 UTC, bashonly requested changes

2025-01-25 18:14 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            'track': info.get('title'),
can we move this up so it's below `title` since they are using the same value

2025-01-25 18:14 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            **(traverse_obj(playlist, {
```suggestion
            **traverse_obj(playlist, {
```

2025-01-25 18:14 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            })),
```suggestion
            }),
```

2025-01-25 18:15 UTC, bashonly commented
> Actually I'm confused - is the album field supposed to be set on the playlist info, or does it only make sense in each track entry? I see in the Bandlab extractor the field is set on the playlist, but the output template documentation seems to suggest otherwise. If that's the case, is there an easy way to set the field on each of the track entries during the playlist extraction process? It seems difficult because the playlist extractor gives a list of URL entries for each track.

It can be set for the playlist and for the track. If you want to pass through the album info available at the playlist stage to each entry, then they need to be `url_transparent` results

2025-01-25 20:56 UTC, 7x11x13 commented
> If you want to pass through the album info available at the playlist stage to each entry, then they need to be `url_transparent` results

Exactly what I was looking for, thanks

2025-01-25 21:04 UTC, bashonly approved these changes
can you test my changes please

2025-01-25 21:06 UTC, bashonly approved these changes

2025-01-25 21:06 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {str}),
maybe we also wanna do this...
```suggestion
            'album_type': ('set_type', {str}, filter),
```

2025-01-25 21:06 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': '',
...so that we don't end up with this
```suggestion
```

2025-01-25 21:06 UTC, 7x11x13 commented
> can you test my changes please

Yeah that works

2025-01-25 21:09 UTC, 7x11x13 commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {str}),
IMO this is fine because this is the 'album type' according to SoundCloud - they use the empty string for 'playlist' type sets; it's not really the absence of an album type, just their way of telling playlists apart from albums.

2025-01-25 21:12 UTC, 7x11x13 commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {str}),
I guess it mainly depends on how other extractors use the 'album_type' field, I'm not too sure if there's a standard

2025-01-25 21:18 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {str}),
There's only one other extractor that currently returns the field afaik. I think keeping an empty string is useless and possibly confusing to anyone who doesn't know the workings of the soundcloud API

I'd either filter, or do something like this:

```suggestion
            'album_type': ('set_type', {str}, lambda x: x or 'album'),
```
```suggestion
            'album_type': ('set_type', {str}, lambda x: x or 'lp'),
```
etc

2025-01-25 21:46 UTC, bashonly approved these changes

2025-01-25 21:46 UTC, bashonly commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {lambda x: x or 'playlist'}),
still wanna type check though
```suggestion
            'album_type': ('set_type', {str}, {lambda x: x or 'playlist'}),
```

2025-01-25 21:46 UTC, 7x11x13 commented on yt_dlp/extractor/soundcloud.py
> +            'album_type': ('set_type', {str}),
I made it explicitly return 'playlist' for album type if its empty

2025-01-25 22:52 UTC, merged