[ie/digiteka] Fix extractor
yt-dlp/yt-dlp pull request #11958
Opened 2024-12-30 22:22 UTC by ElDonad

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Apparently Digiteka has stopped filling the video url in the json "deliver info" directly. With this PR the extractor can now fetch the video URL from the iframe content.

Currently tested only on the [boursorama.com](https://boursorama.com) website, I don't know of any other website using the Digiteka technology, but given that the test urls have stopped working as well, I assume this is a global change. Still, I've kept the legacy method as the first option, maybe it's still being used elsewhere...

This is my first PR to yt-dlp, I hope I didn't botch anything, I'd be happy to oblige if anything needs to be corrected.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-12-30 22:45 UTC, ElDonad commented
From what I can gather of the iframe content, it should also be possible to get the hsl stream urls from the inline javascript at the different provided resolutions. I could try to work on that if needed, but I'd like to know first if the new behaviour is consistent for other websites using the digiteka technology. Please let me know if you use or know of any other.

2025-01-05 13:42 UTC, pukkandan requested changes

2025-01-05 13:42 UTC, pukkandan commented on yt_dlp/extractor/digiteka.py
> +    ]
WIP?

2025-01-05 13:42 UTC, pukkandan commented on yt_dlp/extractor/digiteka.py
> +        video_thumbnail = self._search_regex(VIDEO_THUMBNAIL_REGEX, iframe_content, 'thumbnail')
Use `self._og_search_title` etc

2025-01-05 13:42 UTC, pukkandan commented on yt_dlp/extractor/digiteka.py
> +            # Apparently some video's deliver_info are not accessible this way anymore
```suggestion
```
unnecessary

2025-01-05 13:42 UTC, pukkandan commented on yt_dlp/extractor/digiteka.py
> +            return self._fallback_to_iframe_content(url, video_id)
```suggestion
        if not formats:
            return self._fallback_to_iframe_content(url, video_id)
```

2025-01-05 13:42 UTC, pukkandan commented on yt_dlp/extractor/digiteka.py
> +        })
?

2025-01-05 17:28 UTC, ElDonad commented
Thank you for your review ! I've done the necessary modifications (and also found how to run the tests from the CONTRIBUTING.md file which I had skimmed through a bit too hastily... sorry for the waste of time :/ )

Now everything should be in order.

2025-04-05 10:57 UTC, mickael9 commented
This PR seems to work fine and passes tests. Can it be merged?
I would like to do propose additional changes on top of it.

2025-04-05 17:40 UTC, bashonly requested changes

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
> +        )
revert the unnecessary formatting change; don't autoformat
```suggestion
            video_id)
```

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
>          for source in jwconf['playlist'][0]['sources']:
```suggestion
        formats = []
        for source in traverse_obj(jwconf, ('playlist', 0, 'sources', lambda _, v: url_or_none(v['file']))):
```

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
> +                )
```suggestion
            formats.append({
                'url': source['file'],
                'format_id': source.get('label'),
            })
```

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
> +        }
If there's only a single format, you can return the format info the root of the info dict (no need for a `formats` list). Don't bother extracting the `ext` from the format url; core code already does this. Inline as much as you can in the return

```suggestion
    def _fallback_to_iframe_content(self, url, video_id):
        webpage = self._download_webpage(url, video_id)
        return {
            'id': video_id,
            'url': self._og_search_video_url(webpage),
            'title': self._og_search_title(webpage),
            'thumbnail': self._og_search_thumbnail(webpage),
        }
```

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
> +        {
revert formatting change

2025-04-05 17:40 UTC, bashonly commented on yt_dlp/extractor/digiteka.py
> +        r'<(?:iframe|script)(?:(?!>)[\s\S])*(?:data-)?src=["\'](?P<url>(?:https?:)?//(?:www\.)?(?:digiteka\.net|ultimedia\.com)/deliver/(?P<embed_type>generic|musique)(?:/[^/]+)*/(?:src|article)/(?P<
what is the point of the `embed_type` capture group?

2025-04-13 09:51 UTC, ElDonad commented on yt_dlp/extractor/digiteka.py
> +        r'<(?:iframe|script)(?:(?!>)[\s\S])*(?:data-)?src=["\'](?P<url>(?:https?:)?//(?:www\.)?(?:digiteka\.net|ultimedia\.com)/deliver/(?P<embed_type>generic|musique)(?:/[^/]+)*/(?:src|article)/(?P<
It was already there when I started working on this. From what I understand there seems to be a separate endpoint for music, this capture group is used to determine the `video_type` when doing the _real_extract. I do not have any example of an URL using the music endpoint instead of the generic one so I can't test.

2025-04-13 10:01 UTC, ElDonad commented on yt_dlp/extractor/digiteka.py
> +        {
I think you meant to highlight the change the autoformatter made to the regex above ? Sorry about the autoformatting, I have turned it off now...

2026-08-15 11:03 UTC, ElDonad commented
It's been some time and this PR is not up to date anymore with the current upstream. I also don't know if the fix still works for the only website I've tested (still doesn't work with the current version of yt-dlp though, so there is still something to be fixed). I'm closing this PR for now as I have another fix I'd like to submit first, might revisit later.

2026-08-15 11:03 UTC, closed without merging