[Youmaker][generic] add extractor for youmaker.com
yt-dlp/yt-dlp pull request #1234
Opened 2021-10-11 12:20 UTC by flashdagger

### Before submitting a *pull request* I you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Adding extractor for the [Youmaker video platform](https://youmaker.com/) (Closes #1223)
* support live streams, subtitles and embedded videos
* playlist support for channels and channel playlists
* based on JSON API
* estimate filesize of hls downloads

2021-11-05 17:34 UTC, pukkandan requested changes

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        return url
This is the same as `self.proto_relative_url`

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        self._protocol = parsed_url.scheme
Something I noticed across your various PR. Do not use class/instance variables for this. They should only be used when the property is meant to be shared b/w runs. If user passes 2 urls of same extractor, they are handled by the same instance of the extractor. So if it is being set in `_real_extract`, it most likely should just be a normal variable

Also, for this specific case, the protocol shouldn't depend on what user gave. Most extractors just use https, but if you want the user to have an option, obey `--prefer-insecure` using `self.http_scheme`

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                raise ExtractorError(msg, video_id=uid, expected=isinstance(status, str))
`fatal=False` shouldn't raise error no matter what

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        return self._fix_url(f'//live.youmaker.com/{video_id}/playlist.m3u8')
Unnecessary functions. These should just be inlined or normal variables. Definitely they shouldn't be `property`

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        return categories
I dont get this. Can you explain what you are trying to do here?

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                {'url': f'{self._asset_url}/{url}'})
```suggestion
        subs_list = self._call_api(
            system_id, 'video/subtitle', what='subtitle info',
            query={'systemid': system_id}, fatal=False)

        subtitles = {}
        for item in subs_list or []:
            subtitles.setdefault(item.get('language_code'), []).append(
                {'url': f'{self._asset_url}/{item.get("url")}'})
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +            raise ExtractorError(f'{exc!s} not found in video metadata')
```suggestion
        video_uid, title = info['video_uid'], info['title']
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                    f"Missing m3u8 info. Trying alternative server ({count})")
```suggestion
                    f'Missing m3u8 info. Trying alternative server ({count})')
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                entry_protocol='m3u8' if is_live else 'm3u8_native',
```suggestion
                live=is_live,
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        formats = list(format_mapping.values())
`self._remove_duplicate_formats`

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        self._sort_formats(formats)
sort after doing any manual adjustments

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                item['filesize_approx'] = 128 * tbr * duration
this is done by core code

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +                item['format_id'] = f'{height}p'
is this even needed?

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +            height = try_get(item, itemgetter('height'), int)
it will be int if it exists
```suggestion
            height = item.get('height')
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +            formats, playlist_subtitles = self._extract_m3u8_formats_and_subtitles(
confusing name
```suggestion
            formats, m3u8_subtitles = self._extract_m3u8_formats_and_subtitles(
```

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +        info = (self._cache.get(uid)
I dont understand the use of this cache. Can u explain?

2021-11-05 17:34 UTC, pukkandan commented on yt_dlp/extractor/youmaker.py
> +            raise ExtractorError(f'unsupported {self.ie_key()} url', expected=True)
This seems exactly like what having different extractors with different `_VALID_URLS` automatically achieve. I dont see any reason why you are simulating the same behaviour in this way and making it unnecessarily complex

2021-11-06 16:09 UTC, flashdagger commented
This PR is no longer necessary, since I am able to release it as my own plugin.
Nevertheless thanks for the feedback.

2021-11-06 16:09 UTC, closed without merging