[mediaset] Added playlist support
yt-dlp/yt-dlp pull request #1463
Opened 2021-10-28 19:19 UTC by nixxo

### Before submitting a *pull request* make sure you have:
- [ x At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Improvement

---

### Description of your *pull request* and other information

Add playlist support to the Mediaset extractor as requested in #1372

2021-10-29 19:11 UTC, nixxo commented
learned something new...

2021-10-29 19:15 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +            self._BY_SUBBRAND % (sb, ll, ul), sb)
what's with these variable names? Use readable names

2021-10-29 19:19 UTC, pukkandan requested changes

2021-10-29 19:19 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +    _BY_SUBBRAND = _FEED_URL + 'mediaset-prod-all-programs-v2?byCustomValue={subBrandId}{%s}&sort=:publishInfo_lastPublished|desc,tvSeasonEpisodeNumber|desc&range=%d-%d'
_BY_SUBBRAND is long, so it is justified making it a seperate variable. But the other two doesnt need to be. They are only used in a single place. Better to just put them there

2021-10-29 19:19 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +                )
```suggestion
                    playlist_title=entry['mediasetprogram$subBrandDescription'])
```

2021-10-29 19:21 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +    _BY_SUBBRAND = _FEED_URL + 'mediaset-prod-all-programs-v2?byCustomValue={subBrandId}{%s}&sort=:publishInfo_lastPublished|desc,tvSeasonEpisodeNumber|desc&range=%d-%d'
```suggestion
    _BY_SUBBRAND = 'https://feed.entertainment.tv.theplatform.eu/f/PR1GhC/mediaset-prod-all-programs-v2?byCustomValue={subBrandId}{%s}&sort=:publishInfo_lastPublished|desc,tvSeasonEpisodeNumber|desc&range=%d-%d'
```

2021-10-29 19:21 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +        if len(content.get('entries')) > 0:
```suggestion
        if content.get('entries'):
```

2021-10-29 19:21 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +            entries = [self.url_result(urljoin(self._HOST, url))
```suggestion
            entries = [self.url_result(urljoin('https://www.mediasetplay.mediaset.it', url))
```

2021-10-29 19:24 UTC, pukkandan approved these changes

2021-10-29 19:24 UTC, pukkandan commented on yt_dlp/extractor/mediaset.py
> +                    playlist_title=entry['mediasetprogram$subBrandDescription'])
```suggestion
        for entry in content.get('entries') or []:
            yield self.url_result(
                'mediaset:' + entry['guid'],
                playlist_title=entry['mediasetprogram$subBrandDescription'])
```

2021-10-29 19:37 UTC, nixxo commented
yes, everything is ok

2021-10-29 19:39 UTC, merged

2022-11-24 06:53 UTC, Heros99 commented
debug: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences.
is it possible to add it to KnownDRMIE or change apikey?
Thank you very much

2022-11-24 07:09 UTC, nixxo commented
Can you provide a url?

2022-11-24 11:49 UTC, Heros99 commented
> Can you provide a url?

https://mediasetinfinity.mediaset.it/video/leduefaccedellamore/episodio-1-e-lamore-che-ti-sceglie_F302632502000101

2022-11-24 12:33 UTC, nixxo commented
ok, this will require a bit of rewriting of the extractor because Mediaset put everything in mediasetinfinity and there are free content and payed content on the same website and it requires some extra better drm/login detection. I'll look into it.

2022-11-24 19:04 UTC, Heros99 commented
> ok, this will require a bit of rewriting of the extractor because Mediaset put everything in mediasetinfinity and there are free content and payed content on the same website and it requires some extra better drm/login detection. I'll look into it.

Thank you very much

2022-11-29 07:08 UTC, Heros99 commented
C:\Users\******\Desktop\yt-dlp download>yt-dlp.exe -Uv --cookies-from-browser firefox https://mediasetinfinity.mediaset.it/video/leduefaccedellamore/episodio-1-e-lamore-che-ti-sceglie_F302632502000101
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', 'https://mediasetinfinity.mediaset.it/video/leduefaccedellamore/episodio-1-e-lamore-che-ti-sceglie_F302632502000101']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched/yt-dlp version 2022.11.29.40298 [fd90e3d] (win_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106564-gd6d46a2c50-20220411 (setts), ffprobe N-106564-gd6d46a2c50-20220411
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\******\AppData\Roaming\Mozilla\Firefox\Profiles\*******.default-release\cookies.sqlite"
[Cookies] Extracted 2531 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1730 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/yt-dlp/releases/latest
Latest version: 2022.11.29.40298, Current version: 2022.11.29.40298
yt-dlp is up to date (2022.11.29.40298)
[debug] [Mediaset] Extracting URL: https://mediasetinfinity.mediaset.it/video/leduefaccedellamore/episodio-1-e-lamore-che-ti-sceglie_F302632502000101
[Mediaset] F302632502000101: Downloading JSON metadata
[Mediaset] F302632502000101: Downloading MPEG4 SMIL data
[Mediaset] F302632502000101: Downloading M3U SMIL data
ERROR: [Mediaset] F302632502000101: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
  File "yt_dlp\extractor\common.py", line 678, in extract
  File "yt_dlp\extractor\mediaset.py", line 248, in _real_extract
  File "yt_dlp\extractor\mediaset.py", line 230, in _real_extract
  File "yt_dlp\extractor\theplatform.py", line 45, in _extract_theplatform_smil

**always the same**

2022-11-29 13:18 UTC, nixxo commented
@Heros99 you are not using the version with the improvements... 

```
❯ ydpm https://mediasetinfinity.mediaset.it/video/leduefaccedellamore/episodio-1-e-lamore-che-ti-sceglie_F302632502000101 -F
[Mediaset] F302632502000101: Downloading JSON metadata
[Mediaset] F302632502000101: Downloading MPEG4 SMIL data
[Mediaset] F302632502000101: Downloading MPEG-DASH SMIL data
[Mediaset] F302632502000101: Downloading M3U SMIL data
ERROR: [Mediaset] F302632502000101: Content behind paywall and DRM
```