[servustv] add new extractor
yt-dlp/yt-dlp pull request #1498
Opened 2021-10-31 14:22 UTC by flashdagger

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
related to #1490
Current servustv.com platform seems to have an API which is easy to implement.
Since I don't know the old one I left the ServusIE class untouched.

Open questions:
- video and audio streams are separated - can we provide a default merge?

2021-10-31 14:40 UTC, pukkandan commented
> can we provide a default merge?

wdym? We already merge the best video and audio together assuming ffmpeg is available

2021-10-31 14:48 UTC, flashdagger commented
> > can we provide a default merge?
> 
> wdym? We already merge the best video and audio together assuming ffmpeg is available

Just realized it myself. Very smart! But for the test I had to specify a format, otherwise it says 'url field is missing' which made me puzzled.

2021-10-31 14:49 UTC, pukkandan commented
for the test, specify `bestvideo` as format

2021-10-31 14:51 UTC, flashdagger commented
Another thing. The JSON API requires a timezone in the query. Something like `Europe/Berlin`.  It also seems to work with invalid stuff line `XX`. You guys have any experience with that?

2021-10-31 15:07 UTC, pukkandan commented
Only site that I know needs it is tiktok. There, we have just hardcoded it to New York. Assuming it doesn't actually affect the extraction, ig you can similarly hardcode any timezone

2021-11-04 03:18 UTC, pukkandan requested changes
PS: the code is all over the place and really hurts readability. if possible, try to reorganize it to have a more linear flow

2021-11-04 03:18 UTC, pukkandan commented on yt_dlp/extractor/servus.py
> +            raise ExtractorError(exc.msg, video_id=video_id, expected=True)
```suggestion
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(
            info['videoUrl'], video_id, 'mp4', live=is_live, errnote=False)
        if not formats:
            raise ExtractorError('Stream not available', video_id=video_id, expected=True)
```

2021-11-04 03:18 UTC, pukkandan commented on yt_dlp/extractor/servus.py
> +        errors = ", ".join(info.get('playabilityErrors', ()))
use single quotes everywhere

2021-11-04 03:18 UTC, pukkandan commented on yt_dlp/extractor/servus.py
> +        return None
this shouldnt even be a function
```suggestion
    def _page_id(json_obj):
        return traverse_obj(json_obj, ('source', 'data', ..., 'id'))
```

2021-11-04 03:18 UTC, pukkandan commented on yt_dlp/extractor/servus.py
> +              '/personal_computer/chrome/de/de_DE/playlist.m3u8',
read contributing guidelines. It specifically says DO NOT split literals like this
```suggestion
        'AT': 'https://dms.redbull.tv/v4/destination/stv/stv-linear/personal_computer/chrome/at/de_AT/playlist.m3u8',
        'DE': 'https://dms.redbull.tv/v4/destination/stv/stv-linear/personal_computer/chrome/de/de_DE/playlist.m3u8',
```

also, it appears only the language code in the URL is different. In that case, a mapping like this is unnecessary

2021-11-12 11:07 UTC, flashdagger commented
implemented as separate plugin

2021-11-12 11:07 UTC, closed without merging

2021-11-12 13:51 UTC, pukkandan commented
Making me review the PR and then closing it is not appreciated. If you don't intend to address reviews, don't make a PR in the first place

2021-11-15 13:19 UTC, MuenchenSued commented
> implemented as separate plugin

Hello flashdagger, I feel disappointed, that you've decided to fork this project and implement a solution for yourself instead of contributing here with your knowledge. A couple of people are waiting for a solution and it is no good idea to install a separate tool or plugin for each website. I would appreciate if you could adapt your solution according pukkandan recommendations to make yt-dlp better and better.

2021-11-15 17:43 UTC, flashdagger commented
> > implemented as separate plugin
> 
> Hello flashdagger, I feel disappointed, that you've decided to fork this project and implement a solution for yourself instead of contributing here with your knowledge. A couple of people are waiting for a solution and it is no good idea to install a separate tool or plugin for each website. I would appreciate if you could adapt your solution according pukkandan's recommendations to make yt-dlp better and better.

A plugin is not a fork. You just extend the official yt-dlp installation with additional extractors and still benefit from all improvements of the core library. That way other developers can provide extractors which the yt-dlp team doesn't have to maintain.

2022-01-19 22:07 UTC, chrizilla commented
@flashdagger: You seem to have a working extractor for servustv.com. Could you offer your code to the yt-dlp team?

2022-01-20 01:06 UTC, flashdagger commented
> @flashdagger: You seem to have a working extractor for servustv.com. Would you be willing to share your code with the yt-dlp team?

Sure. It's Unlicense anyway.

2022-01-20 20:48 UTC, chrizilla commented
ok, sry I wasn't clear, I meant giving pukkandan a link to your code.