[Amazon] Add extractor
yt-dlp/yt-dlp pull request #1512
Opened 2021-11-01 18:10 UTC by Ashish0804

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes https://github.com/yt-dlp/yt-dlp/issues/1509

2021-11-01 18:48 UTC, u-spec-png commented on yt_dlp/extractor/amazon.py
> +                    'thumbnail': video.get('thumb') or video.get('thumbUrl'),
```suggestion
                    'thumbnail': video.get('thumbUrl') or video.get('thumb'),
```

2021-11-01 18:49 UTC, u-spec-png commented on yt_dlp/extractor/amazon.py
> +                    'thumbnail': video.get('thumb') or video.get('thumbUrl'),
`thumbUrl` has beater quality so `thumb` shoud be used as fall back.

2021-11-02 23:57 UTC, pukkandan requested changes

2021-11-02 23:57 UTC, pukkandan commented on .gitignore
> +gentest.py
```suggestion
```

2021-11-02 23:57 UTC, pukkandan commented on yt_dlp/utils.py
> +        if codec in ('avc1', 'avc2', 'avc3', 'avc4', 'vp9', 'vp8', 'hev1', 'hev2', 'h263', 'h264', 'mp4v', 'hvc1', 'av01', 'theora', 'dvh1', 'dvhe', 'vp09'):
```suggestion
```

2021-11-02 23:57 UTC, pukkandan commented on yt_dlp/extractor/amazon.py
> +                })
```suggestion
        entries = [{
            'id': video['marketPlaceID'],
            'url': video['url'],
            'title': video.get('title'),
            'thumbnail': video.get('thumbUrl') or video.get('thumb'),
            'duration': video.get('durationSeconds'),
            'height': int_or_none(video.get('videoHeight')),
            'width': int_or_none(video.get('videoWidth')),
        } for video in data_json.get('videos') or [] if video.get('isVideo') and video.get('url')]
```

2021-11-03 00:30 UTC, nyuszika7h requested changes

2021-11-03 00:30 UTC, nyuszika7h commented on yt_dlp/extractor/amazon.py
> +    _VALID_URL = r'(?:https?://)(?:www\.)?amazon\.(?:[a-z]{2,3})(?:\.[a-z]{2})?/[^/]*/?dp/(?P<id>[^/&#$?]+)'
```suggestion
    _VALID_URL = r'(?:https?://)(?:www\.)?amazon\.(?:[a-z]{2,3})(?:\.[a-z]{2})?/[^/]*/?(?:dp|gp/product)/(?P<id>[^/&#$?]+)'
```

2021-11-05 21:44 UTC, closed without merging