[Steam] Fix extractor
yt-dlp/yt-dlp pull request #2029
Opened 2021-12-17 17:19 UTC by u-spec-png

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes #1992

2021-12-17 21:03 UTC, pukkandan requested changes

2021-12-17 21:03 UTC, pukkandan commented on yt_dlp/extractor/steam.py
> +        playlist_id = gameID
```suggestion
        playlist_id = self._match_valid_url(url).group('gameID')
```

what ae the other groups in the VALID_URL for?

2021-12-17 21:03 UTC, pukkandan commented on yt_dlp/extractor/steam.py
> +        videourl = self._VIDEO_PAGE_TEMPLATE % playlist_id
```suggestion
        video_url = self._VIDEO_PAGE_TEMPLATE % playlist_id
```

2021-12-17 21:03 UTC, pukkandan commented on yt_dlp/extractor/steam.py
> +                continue
not needed

2021-12-17 21:03 UTC, pukkandan commented on yt_dlp/extractor/steam.py
> +            entry['formats'] = formats
```suggestion
            self._sort_formats(formats)
            entry['formats'] = formats
```

2021-12-17 22:10 UTC, pukkandan commented on yt_dlp/extractor/steam.py
> -        https?://(?:www\.)?steamcommunity\.com/sharedfiles/filedetails/\?id=(?P<fileID>[0-9]+)
I was not asking to blindly add it back. I see that you have removed the test for this...

Please communicate. Don't make me have to guess your intend

2021-12-18 11:40 UTC, u-spec-png commented on yt_dlp/extractor/steam.py
> -        https?://(?:www\.)?steamcommunity\.com/sharedfiles/filedetails/\?id=(?P<fileID>[0-9]+)
Test was dead and couldn't find any link that sent me to a videos, so I thought that links were no longer valid.

2021-12-18 11:43 UTC, u-spec-png commented on yt_dlp/extractor/steam.py
> -        https?://(?:www\.)?steamcommunity\.com/sharedfiles/filedetails/\?id=(?P<fileID>[0-9]+)
They still work but they're all YouTube embedded.

2021-12-24 22:25 UTC, merged