[afreecatv] Add support for livestreams
yt-dlp/yt-dlp pull request #2097
Opened 2021-12-24 00:15 UTC by wlritchi

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

AfreecaTV is a platform for both prerecorded and live video content. Until now, `yt-dlp` has only supported downloading VODs from AfreecaTV. This PR adds a new extractor for live video from AfreecaTV. The new extractor inherits from the existing AfreecaTV extractor in order to reuse its authentication logic.

2021-12-24 03:12 UTC, Ashish0804 commented on supportedsites.md
> + - **afreecatv:live**: afreecatv.com
this is done automatically....u can remove this
```suggestion
```

2021-12-24 03:14 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +        # TODO do we need to consider other stream key types for different formats?
if this is not done then mark this PR as draft, else remove this

2021-12-24 03:14 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +        # the rest, including the query param, is just to keep parity with the website
not needed

2021-12-24 03:14 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +            'from_api': 0,
try to minimize the required fields

2021-12-24 03:16 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +                        # for now we can get away with ignoring it
`time.time()*1000` maybe 🤔

2021-12-24 03:17 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +            self.report_warning('Failed to look up extra metadata: ' + error_to_compat_str(e))
no need for this to be in try-except block.
Just let it be `None` if extraction failed

2021-12-24 03:18 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +            self.report_warning('Failed to look up extra metadata: ' + error_to_compat_str(e))
Remove all these and then inline the info dict

2021-12-24 05:10 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +            'from_api': 0,
No.
Use the bare minimum.

2021-12-24 05:13 UTC, Ashish0804 commented on yt_dlp/extractor/afreecatv.py
> +                continue
remove try-except here aswell.

set `fatal=False` for api requests and then use `.get` or `try_get` to get the fields.
As of making sure shit is not appended to formats, make a check for all the necessary keys and only append if they are not None

2022-01-05 09:59 UTC, pukkandan requested changes
Also, please make sure I didn't break anything

2022-01-05 09:59 UTC, pukkandan commented on yt_dlp/extractor/afreecatv.py
> +    _VALID_URL = r'https?://play\.afreeca(?:tv)?\.com(?::\d+)?/(?P<id>[^/]+)(?:/(?P<bno>\d+))?'
Add tests for the other URL patterns. `only_matching` tests are sufficient

2022-01-07 01:07 UTC, wlritchi commented
Everything looks to be working after the cleanup :)

Optimization question: The extractor needs to make a couple of API calls per format in order to get the M3U8 URLs for each. Is there a way to do these calls lazily, or some other optimization the extractor can apply, so that e.g. with `-f best` we only fetch the URL for the highest quality?

2022-01-07 01:28 UTC, pukkandan commented
> The extractor needs to make a couple of API calls per format in order to get the M3U8 URLs for each. Is there a way to do these calls lazily,

No

> or some other optimization the extractor can apply, so that e.g. with -f best we only fetch the URL for the highest quality?

You can create an `--extractor-args` to let the user specify which formats to fetch

2022-01-07 12:11 UTC, pukkandan commented
I am merging this. You can add extractor args in another PR if needed

2022-01-07 12:12 UTC, merged

2022-01-07 15:03 UTC, wlritchi commented
:+1: I think in this case it's probably not worth it; it's a minor optimization that probably isn't really worth my time learning about the custom extractor args. Maybe I'll come back to it in the future if a refactor adds a common way to do it. :)