[TikTok] Extract auto captions
yt-dlp/yt-dlp pull request #2185
Opened 2021-12-31 10:24 UTC by MinePlayersPE

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.
Closes https://github.com/yt-dlp/yt-dlp/issues/2184
Drafted because no tests yet + no text positioning info

2022-01-16 15:12 UTC, pukkandan commented
this can be merged even without position info imo.

How did you implement this without being able to test?

2022-01-17 11:25 UTC, MinePlayersPE commented
@pukkandan Okay to merge?

2022-01-19 22:19 UTC, pukkandan requested changes
Ive had this review written for a while, but never submitted 😓

2022-01-19 22:34 UTC, MinePlayersPE commented on yt_dlp/extractor/tiktok.py
> +            'subtitles': subtitles,
Since former is more common, i'll just use that ¯\\\_(ツ)_/¯

2022-01-19 22:35 UTC, merged