[Tennistv] Rewrite
yt-dlp/yt-dlp pull request #2324
Opened 2022-01-13 11:19 UTC by zenerdi0de

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Rewrite cause site got updated and no longer uses the older API endpoints.

2022-02-12 23:52 UTC, pukkandan requested changes

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            return
make non-fatal

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +    def token_util(self, video_id, payload):
token_util? did u mean get_token?

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                                                '')
```suggestion
            login_page = self._download_webpage(BASE_URL, None, query={
                'client_id': 'tennis-tv-web',
                'redirect_uri': 'https://tennistv.com',
                'response_mode': 'fragment',
                'response_type': 'code',
                'scope': 'openid'
            }))
```
etc

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            _, handle = self._download_webpage_handle(update_url_query(BASE_URL, {'client_id': 'tennis-tv-web',
_request_webpage

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                                        fatal=False) or self._og_search_title(webpage)
```suggestion
        title = self._html_search_regex((r'<title>(.+?)</title>', *self._og_regexes('title')),
                                        webpage, 'Title', fatal=False)
```

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            self.to_screen(session_json['ErrorMessage'])
report_warning?

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +        formats, subtitles = self._extract_m3u8_formats_and_subtitles(f'https://open.http.mp.streamamg.com/p/{self.PARTNER_ID}/sp/{self.PARTNER_ID}00/playManifest/entryId/{entryid}/format/applehttp/p
too long. the URL can be seperated out
```py
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(
            self._FORMAT_URL.format(partner=self.PARTNER_ID, entry=entryid, session=k_session), video_id)
```

2022-02-12 23:52 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            'description': self._html_search_regex(r'<span itemprop="description" content=["\'](.+?)["\']>', webpage, 'description', fatal=False) or self._og_search_description(webpage),
line too long

2022-03-24 08:35 UTC, pukkandan requested changes

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +from ..compat import compat_urlparse
```suggestion
import urllib.parse
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +    def _login(self):
See the new documentation on adding login support. The merge conflict should disappear once this is fixed
https://github.com/yt-dlp/yt-dlp/blob/ae6a1b95857c7ba1392e37be99b9ee2b66b14b1d/yt_dlp/extractor/common.py#L437-L443

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            self.report_warning('Site requires a subscribed account. Either pass in the cookies or login credentials.')
If all videos need subscription, better to `self.raise_login_required`

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            self.report_warning('Site requires a subscribed account. Either pass in the cookies or login credentials.')
```suggestion
        if cookies.get('access_token') and cookies.get('refresh_token'):
            self.ACCESS_TOKEN = cookies['access_token'].value
            self.REFRESH_TOKEN = cookies['refresh_token'].value
        else:
            self.raise_login_required()
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                '', headers=self.headers)
```py
            handle = self._request_webpage(BASE_URL, query=..., headers=self.headers)
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                'code': compat_urlparse.parse_qs(handle.geturl()).get('code')[-1],  # There can be multiple, always use the last one
```suggestion
                'code': compat_urlparse.parse_qs(handle.geturl()).get('code')[-1],
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            'description': self._html_search_regex((r'<span itemprop="description" content=["\'](.+?)["\']>', *self._og_regexes('description')), webpage, 'description', fatal=False),
```suggestion
            'description': self._html_search_regex(
                (r'<span itemprop="description" content=["\']([^"\']+)["\']>', *self._og_regexes('description')),
                webpage, 'description', fatal=False),
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            'timestamp': unified_timestamp(self._html_search_regex(r'<span itemprop="description" content=["\'](.+?)["\']>', webpage, 'upload time')),
```suggestion
            'timestamp': unified_timestamp(self._html_search_regex(
                r'<span itemprop="description" content=["\']([^"\']+)["\']>', webpage, 'upload time')),
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +        formats, subtitles = self._extract_m3u8_formats_and_subtitles(self._FORMAT_URL.format(partner=self.PARTNER_ID, entry=entryid, session=k_session), video_id)
```suggestion
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(
            self._FORMAT_URL.format(partner=self.PARTNER_ID, entry=entryid, session=k_session), video_id)
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                                   video_id, 'Downloading ksession token', 'Failed to download ksession token', headers=self.headers)
```suggestion
        return self._download_json(
            f'https://atppayments.streamamg.com/api/v1/session/ksession/?lang=en&apijwttoken={self.ACCESS_TOKEN}&entryId={entryid}',
            video_id, 'Downloading ksession token', 'Failed to download ksession token', headers=self.headers)
```

2022-03-24 08:35 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                                  data=urlencode_postdata(payload))
```suggestion
        res = self._download_json('https://sso.tennistv.com/auth/realms/TennisTV/protocol/openid-connect/token',
                                  video_id, 'Fetching tokens', 'Unable to fetch tokens',
                                  headers=self.headers, data=urlencode_postdata(payload))
```

2022-03-30 04:29 UTC, Bricio commented
Old code returns city, season and round.
![image](https://user-images.githubusercontent.com/216170/160751242-33a00da7-c253-4669-91b4-202c3fc3443f.png)

https://github.com/yt-dlp/yt-dlp/blob/e7870111e83033e0ac728d5a2d565d1eb146c335/yt_dlp/extractor/tennistv.py#L110-L112

You can still collect that info, in attribute values of the same div that you are collecting description now.
![image](https://user-images.githubusercontent.com/216170/160750801-f889701a-864b-4441-8bc7-a1e5142e2e26.png)

It will be good to return same data.

2022-03-30 10:28 UTC, pukkandan requested changes
partial review

2022-05-28 23:33 UTC, pukkandan approved these changes

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +
```suggestion
import urllib.parse

from .common import InfoExtractor
```

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +    random_uuidv4,
```suggestion
    random_uuidv4,
    unified_timestamp,
    urlencode_postdata,
```

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +        post_url = self._html_search_regex(r'action=["\'](.+?)["\']\s+?method=["\']post["\']', login_page, None)
```suggestion
        post_url = self._html_search_regex(r'action=["\']([^"\']+?)["\']\s+method=["\']post["\']', login_page, None)
```

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +    }
```suggestion
    access_token, refresh_token = None, None
    _FORMAT_URL = 'https://open.http.mp.streamamg.com/p/{partner}/sp/{partner}00/playManifest/entryId/{entry}/format/applehttp/protocol/https/a.m3u8?ks={session}'
    HEADERS = {
        'origin': 'https://www.tennistv.com',
        'referer': 'https://www.tennistv.com/',
        'content-Type': 'application/x-www-form-urlencoded'
    }
```
normally, caps are used for constants

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +            'code': urllib.parse.parse_qs(handle.geturl()).get('code')[-1],
```suggestion
            'code': urllib.parse.parse_qs(handle.geturl())['code'][-1],
```

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +        BASE_URL = 'https://sso.tennistv.com/auth/realms/TennisTV/protocol/openid-connect/auth'
makes more sense to put `https://sso.tennistv.com/auth/realms/TennisTV/protocol` in a class var instead imo. This is also used in `get_token`

2022-05-28 23:33 UTC, pukkandan commented on yt_dlp/extractor/tennistv.py
> +                webpage, 'Title', fatal=False),
```suggestion
            'title': self._html_extract_title(webpage) or self._og_search_title(webpage),
```

2022-05-28 23:34 UTC, pukkandan commented
and merge with master

2022-06-23 02:01 UTC, merged