[daftsex] Add new extractors
yt-dlp/yt-dlp pull request #2379
Opened 2022-01-18 15:51 UTC by k3ns1n

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

New extractor

2022-01-18 16:00 UTC, Lesmiscore commented on yt_dlp/extractor/daftsex.py
> +class DAFTSEXIE(InfoExtractor):
Only the first character of each word must be upper case.
```suggestion
class DaftsexIE(InfoExtractor):
```

2022-01-19 07:39 UTC, pukkandan requested changes

2022-01-19 07:39 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +
utils.parse_count

2022-01-19 07:39 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +                                                            extra_quality_data),
use fstring here

2022-01-19 07:39 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +            headers={'Referer': url})
```suggestion
            'https://daxab.com/player/%s?color=%s' % (player_hash, player_color),
            video_id, headers={'Referer': url})
```

2022-01-19 07:39 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +
```suggestion
        player_color = self._search_regex(
            r'DaxabPlayer\.Init\({[\s\S]*color:\s*"([0-9a-z]+)"[\s\S]*}',
            webpage, 'player color', fatal=False) or ''

```

2022-01-19 10:46 UTC, pukkandan requested changes

2022-01-19 10:46 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +        server_domain = 'https://' + server_domain
```suggestion
        server_domain = 'https://%s' % compat_b64decode(video_params['server'][::-1]).decode('utf-8')
```

2022-01-19 10:47 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +            url = f'{server_domain}/videos/{id1}/{id2}/{height}.mp4?extra={extra_quality_data}'
```suggestion
        formats = []
        for format_id, format_data in video_params['video']['cdn_files'].items():
            ext, height = format_id.split('_')
            extra_quality_data = format_data.split('.')[-1]
            url = f'{server_domain}/videos/{video_id.replace("_", "/")}/{height}.mp4?extra={extra_quality_data}'
```

2022-01-19 11:07 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +    try_get
sort

2022-01-19 13:42 UTC, merged

2022-02-04 02:15 UTC, Soebb commented
It throws bellow error for some videos (like [this](https://daftsex.com/watch/-145958185_456243473) one)

ERROR:root:ERROR: -145958185_456243473: An extractor error has occurred. (caused by KeyError('cdn_files')); please report this issue on https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U