[mildom] Fixes and improvements (should close #2519 )
yt-dlp/yt-dlp pull request #2533
Opened 2022-01-29 09:45 UTC by lazypete365

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This should deal with issue #2519 , including the improvements I proposed. I have tested the changes in a couple of channels containing the problematic video IDs, plus a few livestreams, and everything seems to work as intended. Regarding the video IDs getting truncated in the download log, I must have misremembered it because I could not reproduce anything like that. The download archive seems to work normally.

* Fixed _VALID_URL regex (now it looks explicitly for an optional third digit block in the video ID)
* Added '__plataform=web' to cloudac queries. Now referers and access token cookies are probably no longer needed, but I do not dare remove the code yet. _Just in case_.
* Added extra metadata: timestamp, duration and thumbnails for VODs, and timestamp (technically stream start time) for live streams.
* Added graceful(-ish) failure if a video or channel is not found or if access is restricted, using raise_no_formats. It now returns a brief error message and the error code found in the json, and hides the exception details unless -v is used.

2022-01-30 13:29 UTC, pukkandan requested changes

2022-01-30 13:29 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +            note='Downloading live metadata', query={'user_id': video_id, '__platform': "web"})
```suggestion
            note='Downloading live metadata', query={'user_id': video_id, '__platform': 'web'})
```
same everywhere

2022-01-30 13:29 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +        timestamp = try_get(enterstudio['live_start_ms'], compat_numeric_types)
```suggestion
        timestamp = float_or_none(enterstudio.get('live_start_ms'), scale=1000)
```

2022-01-30 13:29 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +
same as above

2022-01-30 13:29 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +            'thumbnails': thumbnails,
```suggestion
            'thumbnail': dict_get(autoplay, ('upload_pic', 'video_pic')),
```
OR
```suggestion
            'thumbnail': traverse_obj(autoplay, 'upload_pic', 'video_pic'),
```

2022-01-30 13:29 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
>      def _call_api(self, url, video_id, query={}, note='Downloading JSON metadata', init=False):
Why not just add `__platform` here
```py
def _call_api(self, url, video_id, query=None, note='Downloading JSON metadata', init=False):
    query = query or {}
    if query:
        query['__platform'] = 'web'
```

2022-01-30 13:29 UTC, pukkandan commented
Also, add/update tests

2022-01-30 16:32 UTC, lazypete365 commented
Thanks for your suggestions! I'll try to get it finished later today.

2022-01-31 20:49 UTC, pukkandan requested changes

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +    compat_str
```suggestion
    compat_str,
```
unrelated diff

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
>      def _call_api(self, url, video_id, query={}, note='Downloading JSON metadata', init=False):
```suggestion
    def _call_api(self, url, video_id, query=None, note='Downloading JSON metadata', init=False):
```

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +                'v_id': video_id
?
```suggestion
                'v_id': video_id,
```

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +            'duration': duration,
```suggestion
        return {
            'id': video_id,
            'title': title,
            'description': description,
            'timestamp': float_or_none(autoplay['publish_time'], scale=1000),
            'duration': float_or_none(autoplay['video_length'], scale=1000),
```

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +            'timestamp': timestamp,
```suggestion
        return {
            'id': result_video_id,
            'title': title,
            'description': description,
            'timestamp': float_or_none(enterstudio.get('live_start_ms'), scale=1000),
```

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +                                  % (content['code'], content['message']), expected=True)
```suggestion
            self.raise_no_formats(
                f'Video not found or premium content. {content["code"]} - {content["message"]}',
                expected=True)
```

2022-01-31 20:49 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +                    'limit': '30'
```suggestion
                    'limit': '30',
```

2022-01-31 20:52 UTC, pukkandan requested changes

2022-01-31 20:52 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +    dict_get
sort imports

2022-01-31 20:52 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +        'playlist_mincount': 191,
```suggestion
    }, {
        'url': 'https://www.mildom.com/profile/10882672',
        'info_dict': {
            'id': '10882672',
            'title': 'Uploads from kson組長(けいそん)',
        },
        'playlist_mincount': 191,
```

2022-01-31 20:52 UTC, pukkandan commented on yt_dlp/extractor/mildom.py
> +    }]
```suggestion
    }, {
        'url': 'https://www.mildom.com/playback/10882672/10882672-1597758589870-477',
        'info_dict': {
            'id': '10882672-1597758589870-477',
            'ext': 'mp4',
            'title': '【kson】感染メイズ！麻酔銃で無双する',
            'thumbnail': r're:^https?://.*\.(png|jpg)$',
            'timestamp': 1597759093.0,
            'uploader': 'kson組長(けいそん)',
            'duration': 4302.58,
            'uploader_id': '10882672',
            'description': 'このステージ絶対乗り越えたい',
            'upload_date': '20200818',
        },
    }, {
        'url': 'https://www.mildom.com/playback/10882672/10882672-buha9td2lrn97fk2jme0',
        'info_dict': {
            'id': '10882672-buha9td2lrn97fk2jme0',
            'ext': 'mp4',
            'title': '【kson組長】CART RACER!!!',
            'thumbnail': r're:^https?://.*\.(png|jpg)$',
            'uploader_id': '10882672',
            'uploader': 'kson組長(けいそん)',
            'upload_date': '20201104',
            'timestamp': 1604494797.0,
            'duration': 4657.25,
            'description': 'WTF',
        },
    }]
```

2022-01-31 20:54 UTC, merged