[Gettr] Add `GettrStreamingIE`
yt-dlp/yt-dlp pull request #2661
Opened 2022-02-06 08:35 UTC by i6t

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Add support for gettr /streaming/ url
(closes #2654)

2022-02-06 08:46 UTC, MinePlayersPE requested changes
thanks for the pr ♥

2022-02-06 08:46 UTC, MinePlayersPE commented on yt_dlp/extractor/gettr.py
> +    IE_NAME = 'Gettr:streaming'
`site:type` IE_NAME format usually doesn't have capital letters
since GettrIE doesn't set it's own IE_NAME either,
```suggestion
```

2022-02-06 08:46 UTC, MinePlayersPE commented on yt_dlp/extractor/gettr.py
> +            'duration': int_or_none(live_info.get('duration')),
```suggestion
            'duration': float_or_none(live_info.get('duration'), scale=1000),
```
Duration is given in miliseconds, while info_dict should set `duration` to seconds (

2022-02-06 08:46 UTC, MinePlayersPE commented on yt_dlp/extractor/gettr.py
> +            'timestamp': int_or_none(live_info.get('startAt')),
```suggestion
            'timestamp': float_or_none(live_info.get('startAt'), scale=1000),
```
Same as duration

2022-02-06 08:46 UTC, MinePlayersPE commented on yt_dlp/extractor/gettr.py
> +            entry_protocol='m3u8_native', m3u8_id='hls', fatal=False) if live_url else []
```suggestion
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(
            live_url, video_id, ext='mp4',
            entry_protocol='m3u8_native', m3u8_id='hls', fatal=False) if live_url else ([], {})
```

2022-02-07 02:03 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +    _API_BASE_URL = 'https://api.gettr.com/u/'
Only used in one place, so can be hardcoded

2022-02-07 02:03 UTC, pukkandan commented on yt_dlp/extractor/gettr.py
> +            })
```suggestion
        thumbnails = [{
            'url': urljoin(self._MEDIA_BASE_URL, thumbnail),
        } for thumbnail in try_get(video_info, lambda x: x['postData']['imgs']) or []]
```

2022-02-08 15:20 UTC, Ashish0804 commented on yt_dlp/extractor/gettr.py
> +        video_info = self._call_api('live/join/%s' % video_id, video_id, data={})['result']
make the `_call_api` function return the `['result']`

2022-02-11 18:34 UTC, pukkandan commented
Could you also have a look at #2557?

2022-02-11 18:36 UTC, merged