[daftsex] Fix yt-dlp#2637
yt-dlp/yt-dlp pull request #2757
Opened 2022-02-13 12:25 UTC by Soebb

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Fix daftsex extractor

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

2022-02-13 14:07 UTC, pukkandan commented
What's with the massive try block?

2022-02-14 11:35 UTC, Soebb commented
Please do desired changes yourself if you can.

2022-03-07 11:41 UTC, Soebb commented
> What's with the massive try block? It's not clear from which lines the errors are expected to be from

Sorry about that, can you check again?

2022-03-08 17:05 UTC, pukkandan requested changes
also modify both tests so they pass

2022-03-08 17:05 UTC, pukkandan commented on yt_dlp/extractor/daftsex.py
> +            }
Since the if block returns, else can be removed and the whole thing dedented

2022-03-17 00:44 UTC, merged