[New extractor] telegram and daystar
yt-dlp/yt-dlp pull request #2922
Opened 2022-03-02 04:25 UTC by hatienl0i261299

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Close #2887
Close #2910

2022-03-02 10:14 UTC, pukkandan commented
Split this into 2 PRs

2022-03-02 14:05 UTC, Ashish0804 commented on yt_dlp/extractor/telegram.py
> +                }
Don't inline this

2022-03-02 14:06 UTC, Ashish0804 commented on yt_dlp/extractor/telegram.py
> +            'thumbnail': thumbnail,
inline

2022-03-02 14:06 UTC, Ashish0804 commented on yt_dlp/extractor/telegram.py
> +            'title': 'Europa Press',
add rest of the fields

2022-03-02 14:07 UTC, Ashish0804 commented on yt_dlp/extractor/telegram.py
> +        return {
call sort_formats before returning

2022-03-02 17:45 UTC, pukkandan requested changes
the comments on the other PR also applies here

2022-03-02 17:45 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +                           'invernaderos y viviendas bit.ly/3pRQv9J ',
use md5

2022-03-02 17:45 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +    _VALID_URL = r'https?:\/\/t\.me\/(?P<channel_name>.*?)\/(?P<id>\d+)($|\W)'
```suggestion
    _VALID_URL = r'https?://t\.me/(?P<channel_name>[^/]+)/(?P<id>\d+)'
```

2022-03-02 17:45 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +            'vcodec': 'none'}]
```suggestion
        formats = [{
            'ext': 'mp4',
            'url': self._proto_relative_url(source),
            'vcodec': 'none'
        }]
```

2022-03-03 10:07 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +            'thumbnail': self._search_regex(r'tgme_widget_message_video_thumb"[^>]+background\-image\:url\(\'(.*?)\'\)',
Remove unnecessary escapes
```suggestion
            'thumbnail': self._search_regex(r'tgme_widget_message_video_thumb"[^>]+background-image:url\(\'([^\']+)\'\)',
```

2022-03-03 10:12 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +        webpage_embed = self._download_webpage(f'{url}?embed=1', video_id=video_id)
The URL passed can be `https://t.me/europa_press/613?embed=1`, `https://t.me/europa_press/613?xxx=yyy`, `https://t.me/europa_press/613#abcd` etc. Use urllib to correctly add the embed query

2022-03-03 10:39 UTC, Lesmiscore commented on yt_dlp/extractor/telegram.py
> +        self._sort_formats(formats)
Is `'vcodec': 'none'` is valid btw?

2022-03-03 11:14 UTC, pukkandan commented on yt_dlp/extractor/telegram.py
> +            'vcodec': 'none'
vcoded=none implies the format is audio-only

2022-03-04 11:18 UTC, merged