[gronkh] Improve extractor
yt-dlp/yt-dlp pull request #3337
Opened 2022-04-07 16:10 UTC by hatienl0i261299

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Close #3300

2022-04-24 02:01 UTC, pukkandan requested changes

2022-04-24 02:05 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +                            f'https://gronkh.tv/watch/stream/{item.get("episode")}', GronkhIE, item.get('title'))
```suggestion
    def _entries(self):
        for type_ in ('recent', 'views'):
            info = self._download_json(
                f'https://api.gronkh.tv/v1/video/discovery/{type_}', 'feed', note=f'Downloading {type_} API JSON')
            for item in traverse_obj(info, ('discovery', ...)) or []:
                yield self.url_result(
                        f'https://gronkh.tv/watch/stream/{item.get("episode")}', GronkhIE, item.get('title'))
```

2022-05-02 11:28 UTC, hatienl0i261299 commented on yt_dlp/extractor/gronkh.py
> +            'description': 'feed',
Actualy, this IE only support one type for download a list video newest that author of website uploader, so I don't know which title or description to put :D

2022-05-02 15:39 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +            'description': 'feed',
just id is enough

2022-05-02 21:38 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +            'description': 'feed',
this is unreolved

2022-05-02 21:40 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +            yield self.url_result(f'https://gronkh.tv/watch/stream/{item.get("episode")}', GronkhIE, item.get("episode"), item.get('title'))
```suggestion
            yield self.url_result(f'https://gronkh.tv/watch/stream/{item["episode"]}', GronkhIE, item['episode'], item.get('title'))
```
same issue above

2022-05-06 07:58 UTC, hatienl0i261299 commented
@pukkandan Is it oke for this PR, can we merge?

2022-05-07 08:44 UTC, merged