[Epix] Add new extractor
yt-dlp/yt-dlp pull request #3364
Opened 2022-04-09 04:14 UTC by hatienl0i261299

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Close #3185

2022-04-24 02:38 UTC, pukkandan requested changes
Is the actual content DRM protected?
* If yes, the extractor must raise warning mentioning this and that only trailer is being downloaded
* If not, the trailer IEs should not capture non-trailer URLs

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +
remove (this will fix the merge conflict)

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +        info = self._download_json(f'{self._API_URL}sessions', video_id='access token', data=json.dumps({
```suggestion
        info = self._download_json(f'{self._API_URL}sessions', None, data=json.dumps({
```

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +        })
```py
        info = self._download_json(
            f'{self._API_URL}sessions', None, note='Download access token info',
            headers=self._HEADERS, note= data=json.dumps({
                ...
            }).encode())
        self._HEADERS.update({
            'x-session-token': info[...]
        })
```

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +    IE_DESC = 'epix.com'
this is not sufficient description

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +        formats, subtitles = self._extract_m3u8_formats_and_subtitles(extras_content.get('hlspath'), video_id=video_id)
`_extract_m3u8_formats...` will throw error with None. Also, the video cant be downloaded, and no data can be extracted without `extras_content`. So why use traverse_obj/.get here?

Similar issue below

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +            'thumbnail': traverse_obj(info, ('series', 'images', 'poster', '16_9', 'xlarge')),
too specific. It looks like we can extract all thumbnails instead

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +            'url': traverse_obj(info, ('trailer', 'url')),
format without url is wrong

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +                                                                   video_id=video_id)
indentation

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +            'subtitles': subtitles,
traverse_obj/dict_get

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +            'thumbnail': traverse_obj(info, ('images', 'poster', '16_9', 'xlarge')),
same as above

2022-04-24 02:38 UTC, pukkandan commented on yt_dlp/extractor/epix.py
> +            'series', 'items', int_or_none(season_id) - 1, 'content', 'items', int_or_none(episode_id) - 1, 'content'))
why int_or_none if u r going to do `-1`?

2022-04-25 01:44 UTC, hatienl0i261299 commented on yt_dlp/extractor/epix.py
> +        'user-agent': 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36',
Yes, it needs.

2022-05-02 11:10 UTC, hatienl0i261299 commented
Temporarily close PR until no longer geo-blocked

2022-05-02 11:10 UTC, closed without merging