[niconico] Handle mandatory MFA login
yt-dlp/yt-dlp pull request #3559
Opened 2022-04-26 16:30 UTC by ekangmonyet

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

niconico now requires MFA when logging in using username and password, breaking the current login method.  This patch updates the login flow and prompts user to input the code.

2022-04-26 19:36 UTC, pukkandan requested changes
cc @animelover1984

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                r'(?<=<form action=["\'])(.*?)(?=["\'])', resp_page, 'mfa_submit',
```suggestion
                r'<form action=["\']([^"\'])["\']', resp_page, 'mfa_submit',
```
why use lookahead/behind?

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                fatal=True)
`fatal=True` is default

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                'https://account.nicovideo.jp' + mfa_submit, None,
fstrings preferred over +

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                }).read().decode('utf-8')
why not download_webpage?

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                    '(?<=formError["\']>)(.*?)(?=</div>)', resp_page, 'form_error',
same as above

2022-04-26 19:36 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                    fatal=False, flags=re.DOTALL))
default implies non-fatal

2022-04-27 15:25 UTC, Lesmiscore approved these changes
Good work. It worked with my account.

2022-04-27 15:46 UTC, ekangmonyet commented on yt_dlp/extractor/niconico.py
> +                self.report_warning(f'unable to log in: failed mfa, "{err_msg}"')
That seems better, judging by the current usage, I think I will capitalize both `Unable to log in` messages too.

2022-04-27 16:41 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                })
```suggestion
            page = self._download_webpage(
                urljoin('https://account.nicovideo.jp', post_url), None,
                note='Performing MFA', errnote='Unable to complete MFA',
                data=urlencode_postdata({
                    'otp': self._get_tfa_info('6 digits code')
                }), headers={
                    'Content-Type': 'application/x-www-form-urlencoded',
                })
```

2022-04-27 16:41 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +                'post url', group='url')
```suggestion
        if 'oneTimePw' in page:
            post_url = self._search_regex(
                r'<form[^>]+action=(["\'])(?P<url>.+?)\1', page, 'post url', group='url')
```

2022-04-27 16:41 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +            if mfa_error:
```suggestion
            if 'oneTimePw' in page or 'formError' in page:
```

2022-04-27 16:44 UTC, merged