Update tmz.com extractor tests
yt-dlp/yt-dlp pull request #3654
Opened 2022-05-06 00:27 UTC by diegorodriguezv

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Fix the tests for the tmz.com extractor.
```
$ python -m unittest discover -k TMZ
...
Ran 10 tests in 5.634s

OK
```
They where all failing.
The extractor itself is working fine.

2022-05-06 06:35 UTC, pukkandan commented
Pls see https://github.com/yt-dlp/yt-dlp/pull/3549#issuecomment-1108589347

2022-05-06 13:28 UTC, diegorodriguezv commented
The comment @pukkandan is refering to is:

> The test conditions was recently made stricter. Because of this, many existing extractor tests currently fail. We generally don't bother fixing them until the extractor is being modified. Did you come across this when working on this extractor? If so, you can put this patch as part of the relevant PR
I was planning on fixing it but since it is working okay I ran the tests and saw they needed updating. I can see why in a project like this having some tests fail to save developer time makes sense. I've been working using TDD and having green tests all the time lets you focus on just the task at hand but more importantly it lets you create new features and know that you are not breaking anything else. That is why immediately jump to fix the tests.

2022-05-07 02:11 UTC, pukkandan commented
I don't actually mind merging this. But if you found this while working on the extractor, it is easier to just add this commit to that PR

2022-05-07 11:12 UTC, diegorodriguezv commented
I was going to fix it but it needed no fixing. I tested several new pages (videos) at tmz.com and it worked flawlessly. But the tests weren't working so I fixed them.
I would very much like this PR merged. In fact that is why I decided to contribute here instead of youtube-dl (took a year to merge my PR) or yt-dlc (died).
Besides I saw that "Tests: passing" on the readme and my heart fluttered.

2022-05-07 11:19 UTC, pukkandan requested changes

2022-05-07 11:19 UTC, pukkandan commented on yt_dlp/extractor/tmz.py
> +            )
```suggestion
            match_obj = re.search(r'\.cueVideoById\(\s*(?P<quote>[\'"])(?P<id>.*?)(?P=quote)', webpage)
```

2022-05-07 11:19 UTC, pukkandan commented on yt_dlp/extractor/tmz.py
> +                )
```suggestion
                    blockquote_el)
```

2022-05-07 11:20 UTC, pukkandan commented on yt_dlp/extractor/tmz.py
> +                ],
```suggestion
                "tags": "count:10",
```

2022-05-07 11:21 UTC, merged

2022-05-07 11:22 UTC, pukkandan commented
> Besides I saw that "Tests: passing" on the readme and my heart fluttered.

This is referring to core tests