[Podchaser] Add extractor
yt-dlp/yt-dlp pull request #3665
Opened 2022-05-07 02:44 UTC by connercsbn

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

This adds support for podchaser.com, a podcast aggregator. All the podcast info is grabbed in JSON from Podchaser's API (api.podchaser.com). If multiple episodes are found, it returns a playlist--otherwise, just the one result.

2022-05-07 02:58 UTC, pukkandan requested changes

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +from ..compat import compat_str
use str

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +from ..utils import float_or_none, try_get, str_to_int, unified_timestamp, merge_dicts
split lines and sort

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +from __future__ import unicode_literals
remove

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +from .common import InfoExtractor
move above ..utils

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +            (?P<id>[\d]+))?'''
some of the brackets and indentation don't make sense

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +            'title': "Ep. 285 – freeze me off",
use single quotes everywhere

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +        audio_id, podcast_id = mobj.group('id'), mobj.group('podcast_id')
```suggestion
        audio_id, podcast_id = self._match_valid_url(url).group('id', 'podcast_id')
```

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +        else:
This is better as 2 extractors imo

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +                or try_get(podcast_data, lambda x: x['summary']['categories'], list) or []],
```suggestion
            'categories': traverse_obj(podcast_data, (('summary', None), 'categories', ..., 'text'))
```

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +            'tags': [tag.get('text') for tag in podcast_data.get('tags') or []],
similar to above

2022-05-07 02:58 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +                    episodes.extend(curr_episodes)
should be a paged list

2022-05-09 13:20 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +    _VALID_URL = PodchaserIE._VALID_URL_BASE + r'(?P<id>\d+)'
that doesn't quite work. Probably best to define a `suitable` instead:
```py
@classmethod
def suitable(cls, url):
    return super().suitable(url) and not PodchaserIE.suitable(url)
```

2022-05-09 13:20 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +            self._API_BASE + 'list/episode', podcast_id,
use fstrings instead of `+`. Same everywhere

2022-05-09 13:21 UTC, pukkandan commented on yt_dlp/extractor/podchaser.py
> +        podcast_id = self._match_valid_url(url).group('id')
```suggestion
        podcast_id = self._match_id(url)
```

2022-05-09 21:58 UTC, connercsbn commented
> I am starting to think that my suggestion to split the extractor may have been detrimental...
I'm happy to try whatever you think is best. Pretty new to OOP so this is a learning experience for me

2022-05-15 15:53 UTC, merged