Extract referrer policy and apply the correct header in parse_html5_media_entries
yt-dlp/yt-dlp pull request #3677
Opened 2022-05-08 10:36 UTC by aalsuwaidi

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Currently the `_parse_html5_media_entries` applies the Base URL in the Referer header for all the format entries. This will not set the correct Referer header based on the specified Referrer-Policy.

[Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) 

The pull request adds code to:
- Get the referrer policy from the meta element
- Return the correct Referrer URL based on the extracted policy
- Set Referer header to the correct URL

Points to note:
- The Referrer Policy can be set/extracted from the request header instead of just the meta element
- The policy can also be applied as an [attribute per element](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#integration_with_html)

2022-05-08 15:01 UTC, pukkandan requested changes
* Change all quotes to single
* Can you provide a real test case (URL) for this?

2022-05-08 15:01 UTC, pukkandan commented on test/test_utils.py
> +        # Origin
1. The comments are redundant
2. There are only 3-4 URLs used for all the tests. Put them in variables

2023-02-04 18:10 UTC, aalsuwaidi commented on yt_dlp/utils.py
> +            parsed_url = parsed_url._replace(fragment='')
if the `._replace` is called to replace a nonexistent field it will throw an error. Maybe I misunderstood, what did you have in mind?

2023-02-04 18:13 UTC, pukkandan commented
It seems you messed up the merge. If you can't figure out how to fix it and would like me to do so, just let me know

2023-02-04 18:26 UTC, aalsuwaidi commented
> It seems you messed up the merge. If you can't figure out how to fix it and would like me to do so, just let me know

Must have missed something it’s been a while since I’ve worked on this branch, would appreciate some help on fixing it

2023-02-04 18:32 UTC, aalsuwaidi commented
> * Change all quotes to single
> * Can you provide a real test case (URL) for this?

For example [Streamin](https://streamin.me) hosts the videos on another domain and is not downloadable (HTTP Error 403) unless the correct referrer is set

This is a sample video: [https://streamin.me/v/ed99e8ab](https://streamin.me/v/ed99e8ab)

2023-02-08 21:13 UTC, pukkandan requested changes

2023-02-08 21:13 UTC, pukkandan commented on yt_dlp/utils.py
> +        elif is_tls(referrer_url) and not is_tls(request_url):
unresolved

2023-02-08 21:13 UTC, pukkandan commented on test/test_utils.py
> +        self.assertEqual(get_referrer_url(example_page_url, example_url_insecure, "no-referrer-when-downgrade"), None)
```suggestion

        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'no-referrer'), None)
        self.assertEqual(get_referrer_url(example_page_url, example_url_insecure, 'origin'), example_url)
        
        self.assertEqual(get_referrer_url(example_page_url_with_query, example_page_url_with_query, 'unsafe-url'), example_page_url_with_query)
        self.assertEqual(get_referrer_url(example_page_url_with_query, mozilla_url, 'unsafe-url'), example_page_url_with_query)
        self.assertEqual(get_referrer_url(example_page_url_with_query, example_page_url_with_query, 'unsafe-url'), example_page_url_with_query)
        
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'strict-origin'), example_url)
        self.assertEqual(get_referrer_url(example_page_url, example_org_url_insecure, 'strict-origin'), None)
        self.assertEqual(get_referrer_url(example_page_url, example_url_insecure, 'strict-origin'), None)
        
        self.assertEqual(get_referrer_url(example_page_url, example_otherpage_url, 'strict-origin-when-cross-origin'), example_page_url)
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'strict-origin-when-cross-origin'), example_url)
        self.assertEqual(get_referrer_url(example_page_url, example_otherpage_url_insecure, 'strict-origin-when-cross-origin'), None)
        
        self.assertEqual(get_referrer_url(example_page_url, example_otherpage_url, 'same-origin'), example_page_url)
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'same-origin'), None)
        self.assertEqual(get_referrer_url(example_page_url, example_page_url, 'same-origin'), example_page_url)
        
        self.assertEqual(get_referrer_url(example_page_url, example_otherpage_url, 'origin-when-cross-origin'), example_page_url)
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'origin-when-cross-origin'), example_url)
        self.assertEqual(get_referrer_url(example_page_url, example_page_url_insecure, 'origin-when-cross-origin'), example_url)
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'origin-when-cross-origin'), example_url)
        
        self.assertEqual(get_referrer_url(example_page_url, example_otherpage_url, 'no-referrer-when-downgrade'), example_page_url)
        self.assertEqual(get_referrer_url(example_page_url, mozilla_url, 'no-referrer-when-downgrade'), example_page_url)
        self.assertEqual(get_referrer_url(example_page_url, example_url_insecure, 'no-referrer-when-downgrade'), None)
```

2023-02-08 21:13 UTC, pukkandan commented on yt_dlp/utils.py
> +    is_not_tls_requester = not is_tls(request_url)
```suggestion
    
    referrer_url = strip_url(referrer_source)
    referrer_origin = strip_url(referrer_source, origin_only=True)
    is_origin_only = referrer_origin == strip_url(request_url, True)
    
    # https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy
    def is_tls(url):
        return urllib.parse.urlparse(url).scheme in ('https', 'ftps')

    insecure = is_tls(referrer_url) and not is_tls(request_url)

```

2023-02-08 21:13 UTC, pukkandan commented on yt_dlp/extractor/common.py
> +                referrer = get_referrer_url(base_url, f["url"], referrer_policy)
```suggestion
                referrer = get_referrer_url(base_url, f['url'], referrer_policy)
```

2023-02-08 21:13 UTC, pukkandan commented on yt_dlp/extractor/common.py
> +    xpath_with_ns
```suggestion
    xpath_with_ns,
```

2023-02-08 21:18 UTC, pukkandan commented on yt_dlp/utils.py
> +        referrer_url = referrer_origin
```suggestion

    referrer_origin = strip_url(referrer_source, origin_only=True)
    is_origin_only = referrer_origin == strip_url(request_url, True)
    referrer_url = strip_url(referrer_source)
    if len(referrer_url) > 4096:
        referrer_url = referrer_origin

    # https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy
    def is_tls(url):
        return urllib.parse.urlparse(url).scheme in ('https', 'ftps')

    insecure = is_tls(referrer_url) and not is_tls(request_url)

```

2023-02-08 21:19 UTC, pukkandan commented
> > * Can you provide a real test case (URL) for this?
> 
> For example [Streamin](https://streamin.me) hosts the videos on another domain and is not downloadable (HTTP Error 403) unless the correct referrer is set
> 
> This is a sample video: [streamin.me/v/ed99e8ab](https://streamin.me/v/ed99e8ab)

Add this to generic's _TESTS

2024-04-20 16:17 UTC, closed without merging