[DRTV] Fix extractor to allow for new URL scheme for radio episodes
yt-dlp/yt-dlp pull request #3708
Opened 2022-05-11 12:58 UTC by vertan

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information
DR have changed their URL scheme for radio episodes from `https://www.dr.dk/radio/` to `https://www.dr.dk/lyd/`, so this PR changes to allowed URL. There's also a couple of fixes to old tests in there to make them all green.

2022-05-11 16:10 UTC, pukkandan requested changes

2022-05-11 16:10 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +from .common import InfoExtractor
move this back above aes

2022-05-12 13:52 UTC, vertan commented
Thanks for the input @pukkandan, I have fixed your comments

2022-05-12 18:08 UTC, pukkandan requested changes
the warnings are an indication of an issue in the code. You don't need to fix it rn, but simply suppressing it is not good idea

2022-05-12 18:08 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +        'expected_warnings': ['Ignoring subtitle tracks found in the HLS manifest']
```suggestion
```

2022-05-12 18:08 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +        'expected_warnings': ['Ignoring subtitle tracks found in the HLS manifest'],
```suggestion
```

2022-05-12 18:09 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +            'id': "urn:dr:mu:programcard:6265cb2571401424d0360113",
```suggestion
            'id': 'urn:dr:mu:programcard:6265cb2571401424d0360113',
```

2022-05-12 18:09 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +            'season_id': "urn:dr:mu:bundle:5afc03ad6187a4065ca5fd35",
```suggestion
            'season_id': 'urn:dr:mu:bundle:5afc03ad6187a4065ca5fd35',
```

2022-05-12 18:10 UTC, pukkandan commented on yt_dlp/extractor/drtv.py
> +            'series': "Historien om Danmark"
```suggestion
            'season': 'Historien om Danmark',
            'series': 'Historien om Danmark',
```

2022-05-12 18:12 UTC, merged

2022-05-13 07:28 UTC, vertan commented
Thanks for the comments and fixes! First time committing to this repo, will try to think of that next time