[extractor/iwara:user] Strictly check pages
yt-dlp/yt-dlp pull request #3901
Opened 2022-05-29 08:13 UTC by Lesmiscore

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Iwara has some edge-cases that user profile page and video listing page varies. This PR fixes to work flawlessly with these cases.

Related: ytdl-patched/ytdl-patched#34

2022-05-30 17:19 UTC, pukkandan requested changes
the comments are useless. Otherwise lgtm

2022-05-30 17:19 UTC, pukkandan commented on yt_dlp/extractor/iwara.py
> +        videos_url = self._search_regex(r'<a href="(/users/[^/]+/videos)(?:\?[^"]*)?">', webpage, 'all videos url', default=None)
```suggestion
        videos_url = self._search_regex(r'<a href="(/users/[^/]+/videos)(?:\?[^"]*+)?">', webpage, 'all videos url', default=None)
```

2022-05-31 01:52 UTC, merged

2022-05-31 06:29 UTC, Lesmiscore commented on yt_dlp/extractor/iwara.py
> +        videos_url = self._search_regex(r'<a href="(/users/[^/]+/videos)(?:\?[^"]*)?">', webpage, 'all videos url', default=None)
👎 https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/yt_dlp/extractor/iwara.py#L182

2022-05-31 06:35 UTC, afterdelight commented on yt_dlp/extractor/iwara.py
> +        videos_url = self._search_regex(r'<a href="(/users/[^/]+/videos)(?:\?[^"]*)?">', webpage, 'all videos url', default=None)
what?