Fix Niconico Series extractor
yt-dlp/yt-dlp pull request #3935
Opened 2022-06-01 07:57 UTC by sqrtNOT

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)

---

Essentially, the niconico series page went from using relative references to using absolute references so the current regex wasn't finding any video urls on the test cases.

2022-06-01 23:50 UTC, gamer191 commented
NOTE: please ignore the failing commit test. It's due to an external bug (the external bug being that pytest is partially broken in python 3.11-dev)

2022-06-02 06:48 UTC, pukkandan requested changes

2022-06-02 06:48 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +        'playlist_mincount': 10,  # as of 2022/06/01
```suggestion
        'playlist_mincount': 10,
```

2022-06-02 06:48 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +        'playlist_mincount': 103,  # as of 2022/06/01
```suggestion
        'playlist_mincount': 103,
```

2022-06-02 06:49 UTC, pukkandan commented on yt_dlp/extractor/niconico.py
> +            for v_id in re.findall(r'data-href=[\'"](?:https://www\.nicovideo\.jp)?/watch/([a-z0-9]+)', webpage)]
Shouldn't we also look for the old pattern? Or are you sure all pages have transitioned?

2022-06-02 16:02 UTC, merged