[Go] Extract original airdate
yt-dlp/yt-dlp pull request #4186
Opened 2022-06-26 01:17 UTC by ischmidt20

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please **make sure the description explains the purpose and effect** of your *pull request* and is worded well enough to be understood. Provide as much **context and examples** as possible.

Extracts airdate from Go streams (particularly ABC). Not sure how to properly safely get the first element of the list of the list does not exist, my solution feels a little hacky so feel free to update for style. May also need to update previously existing code to remove compat code to pass tests

2022-06-26 01:32 UTC, pukkandan requested changes
add/fix tests

2022-06-26 01:32 UTC, pukkandan commented on yt_dlp/extractor/go.py
> +            'timestamp': timeconvert(video_data.get('airdates', {}).get('airdate', [None])[0]),
```suggestion
            'timestamp': unified_timestamp(traverse_obj(video_data, ('airdates', 'airdate', 0))),
```

2022-06-30 01:58 UTC, ischmidt20 commented
Done. I removed one test because it was for a playlist, and I got an error (full file path redacted). Not sure how to properly format it

```
Traceback (most recent call last):
  File "...../yt-dlp/test/test_download.py", line 276, in test_template
    getattr(self, f'test_{name}_{i}' if i else f'test_{name}')()
  File "...../yt-dlp/test/test_download.py", line 184, in test_template
    self.assertTrue(res_dict['_type'] in ['playlist', 'multi_video'])
KeyError: '_type'
```

2022-06-30 03:06 UTC, pukkandan commented
Something's broken then. I won't ask you to fix it, but add the test back. If we remove failing tests, then what's the point of tests?

2022-06-30 22:49 UTC, ischmidt20 commented
Sure, but in this case it looks like a problem with the testing mechanism, as opposed to the extractor itself, which is why I removed it

2022-07-01 00:39 UTC, pukkandan commented
>  but in this case it looks like a problem with the testing mechanism

How so? From the error message you provided, it appears the extractor is returning a single video when the test definition say that a playlist is expected

2022-07-01 00:51 UTC, ischmidt20 commented
Ah yes, that was my mistake for not interpreting the test output correctly. I have added the test back (after modifying it to reflect the fact the previous URL no longer exists). Perhaps I will try to fix it, but I have not tried to code anything up for playlists yet so I'll probably just leave it. Sorry about that!

2022-07-26 15:49 UTC, merged