Update tv5mondeplus.py to detect subtitles
yt-dlp/yt-dlp pull request #4209
Opened 2022-06-27 19:17 UTC by FrankZ85

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

---

### Description of your *pull request* and other information
Fixes #4205

This retrieves the subtitles as announced by the streaming site. The code to iterate over the subtitle definitions is taken from other extractors.

It would still be nice to try and detect the other, not announced, subtitles. Maybe by sending HEAD requests to the guessed URLs to get the HTTP status? For this entry, replacing the second "FRA" by "DEU", "ENG", "SPA" worked just fine.

2022-06-28 05:20 UTC, pukkandan requested changes

2022-06-28 05:20 UTC, pukkandan commented on yt_dlp/extractor/tv5mondeplus.py
> +                })
```suggestion
                lang = f.get('label') or 'fra'
                subtitles.setdefault(lang, []).append({'url': subtitle_url})
```

2022-06-28 05:20 UTC, pukkandan commented on yt_dlp/extractor/tv5mondeplus.py
> +            subtitles = self._extract_subtitles(captions)
```suggestion
        subtitles = self._extract_subtitles(self._parse_json(
            vpl_data.get('data-captions', '{}'), video_id, fatal=False))
```

2022-06-28 05:21 UTC, pukkandan commented
confirm evevrything's still working

2022-06-28 05:23 UTC, pukkandan commented on yt_dlp/extractor/tv5mondeplus.py
> +            vpl_data.get('data-captions', '{}'), video_id, fatal=False))
```suggestion
            vpl_data.get('data-captions', '{}'), display_id, fatal=False))
```

2023-11-04 03:22 UTC, seproDev commented
Can confirm still works

2023-11-15 22:19 UTC, bashonly approved these changes

2023-11-15 22:19 UTC, bashonly commented on yt_dlp/extractor/tv5mondeplus.py
> +            'subtitles': subtitles,
```suggestion
            'formats': formats,
            'subtitles': self._extract_subtitles(self._parse_json(
                traverse_obj(vpl_data, ('data-captions', {str}), default='{}'), display_id, fatal=False)),
            'series': series,
            'episode': episode,
```

2023-11-15 22:19 UTC, bashonly commented on yt_dlp/extractor/tv5mondeplus.py
> +
```suggestion
    @staticmethod
    def _extract_subtitles(data_captions):
        subtitles = {}
        for f in traverse_obj(data_captions, ('files', lambda _, v: url_or_none(v['file']))):
            subtitles.setdefault(f.get('label') or 'fra', []).append({'url': f['file']})
        return subtitles
```

2023-11-15 22:38 UTC, merged