[extractor/xfileshare] Add Referer in HTTP header
yt-dlp/yt-dlp pull request #4494
Opened 2022-07-30 12:30 UTC by Galiley

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

### Description of your *pull request* and other information

</details>

DESCRIPTION
Add Referer in HTTP header

2022-07-30 13:00 UTC, pukkandan commented
Why?

2022-07-30 13:23 UTC, Galiley commented
Uqload needs the referer http headers to be set in order to be able to download the video.
I should have restricted it to only Uqload...

2022-07-30 13:25 UTC, pukkandan commented
no open issue, no explanation, or even an example URL... how do you expect me to merge a PR like that?

Add a test case to the extractor. Or, if an existing test covers this already, tell mw which one

2022-07-31 22:27 UTC, pukkandan requested changes
Does this cause any issues?

```diff
        return {
            'id': video_id,
            'title': title,
            'thumbnail': thumbnail,
            'formats': formats,
+           'http_headers': {'Referer': url},
        }
```

2022-07-31 22:27 UTC, pukkandan commented on yt_dlp/extractor/xfileshare.py
> +    }, {
1. Use non-piracy link
2. Add md5
3. Use actual title
4. `http_headers` is not needed in test

2022-08-01 22:31 UTC, pukkandan commented on yt_dlp/extractor/xfileshare.py
> +                    formats.append({'url': video_url, 'format_id': 'sd'})
```suggestion
                    formats.append({
                        'url': video_url,
                        'format_id': 'sd',
                    })
```

2022-08-01 22:31 UTC, merged