[extractor/crackle] Adds support for channels, playlists, and series
yt-dlp/yt-dlp pull request #4734
Opened 2022-08-22 01:35 UTC by shloop

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Updates Crackle extractor to allow downloading of entire series and to support a wider variety of URLs. Previously, a specific video ID had to be provided in the URL, but this is often not included in the URL when browsing the site normally. This change allows a channel or playlist ID to be provided in the URL instead.

URLs in the following formats are now supported:
 - ### Channel 
   - Format: https://www.crackle.com/watch/CHANNEL_ID
   - Channel can be a movie or a series. Extractor will check the JSON object for the channel to determine the type and download accordingly.
 - ### Playlist
   - Format: https://www.crackle.com/watch/playlist/PLAYLIST_ID
   - This will probably not be used much if at all in practice since Crackle tends to use channel IDs and/or specific video IDs in their links, but if a playlist URL is provided then the extractor will download all videos in the playlist.
 - ### Video
   - Formats include but are not limited to the following:
     - https://www.crackle.com/watch/playlist/PLAYLIST_ID/VIDEO_ID
     - https://www.crackle.com/watch/CHANNEL_ID/VIDEO_ID
   - Any channel or playlist ID will be ignored if a video ID is included and only the specific video will be downloaded.
   - Note: Some URLs which include the name of a series with a video ID are still supported but will redirect to a URL with a channel ID in it. I am guessing this was an older convention and they keep a mapping to handle routing to the new scheme.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-08-22 01:37 UTC, pukkandan commented
I would suggest splitting this into 3 extractors. The common code can be inherited from a `CrackleBaseIE`

2022-08-22 01:48 UTC, shloop commented
> I would suggest splitting this into 3 extractors. The common code can be inherited from a `CrackleBaseIE`

Hmm, do you know of any other extractors that do that I could look to as an example? I was trying to mimic the logic flow of the PlutoTV one.

2022-08-31 05:49 UTC, shloop commented
@pukkandan Refactored into separate extractors as requested.

2022-09-30 15:13 UTC, pukkandan commented
My review on other PRs also apply here. Especially https://github.com/yt-dlp/yt-dlp/pull/4801#discussion_r962273141

2022-09-30 15:41 UTC, pukkandan requested changes

2022-09-30 15:41 UTC, pukkandan commented on yt_dlp/extractor/crackle.py
> +        EPISODE_INFO = {
Dont do this

2022-09-30 15:41 UTC, pukkandan commented on yt_dlp/extractor/crackle.py
> +        PLAYLIST = "playlist"
unnecessary. See my changes to similar abstraction below

2022-09-30 15:41 UTC, pukkandan commented on yt_dlp/extractor/crackle.py
> +        return self.playlist_result(videos, playlist_id, traverse_obj(playlist, ('Result', 'Name')))
Fix --flat-playlist by returning URLs here. Any metadata that requires additional network requests should not be returned here. core code will handle further extraction

2022-09-30 15:41 UTC, pukkandan commented on yt_dlp/extractor/crackle.py
> +                self._get_video_info(media['MediaInfo']['Id'], country)
same

2024-08-17 18:39 UTC, shloop commented
Abandoning this since it was never accepted and Crackle website has changed to the point that neither the main branch nor my changes appear to work at all. Entire site may be DRM protected now: https://github.com/yt-dlp/yt-dlp/issues/5118

2024-08-17 18:39 UTC, closed without merging