[Smotrim] Add extractor
yt-dlp/yt-dlp pull request #4789
Opened 2022-08-28 13:30 UTC by nikita-moor

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add new extractor for [smotrim.ru](https://smotrim.ru/).

</details>

This video hosting is not supported by the current version of yt-dlp. Perhaps, [rutv](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/rutv.py) was somehow related to smotrim.ru (old version of the website?), but now it cannot download video.

Fixes #4110

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-08-30 17:32 UTC, nikita-moor commented
> Read this again

Is it better now?

2022-08-31 02:20 UTC, pukkandan requested changes

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        if re.match(self._VALID_URL, url).group('type') == 'brand':
self._match_valid_url

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        m = re.search(
self._search_regex

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        meta = self._download_json(f'https://player.smotrim.ru/iframe/datavideo/id/{video_id}/sid/smotrim', None,)
video_id is not None

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        meta = traverse_obj(meta, ('data', 'playlist', 'medialist'))[0]
Is this meant to be fatal or not?

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        if meta.get('errors') == '':
```suggestion
        if not meta.get('errors'):
```

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +            for key in traverse_obj(meta, ('sources', 'http')):
again, despite traverse_obj, the code is actually fatal. Decide which one it should be

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                    print(f'Text: New resolution "{key}" in the video {url}.\n')
Use self._report_warning and bug_reports_message

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                        'format': 'unknown',
Use `key`

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                        'url': traverse_obj(meta, ('sources', 'http', key))
Why not use this when key is known too?

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +            print('Video isn\'t available in your region. Trying to identify accessible formats...')
self.to_screen or self._report_warning

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                print("success")
self._check_formats

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                })
Lot of repeated code. Can be refactored into a single block

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +            raise ExtractorError('Unknown error: ' + meta.get('errors'), expected=False)
Use fstring, not +

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        formats = sorted(formats, key=lambda item: int(item['resolution']))
self._sort_formats

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +                        'resolution': key,
resolution? or height?

2022-08-31 02:20 UTC, pukkandan commented on yt_dlp/extractor/smotrim.py
> +        # print('md5:' + hashlib.md5(meta.get('anons').encode('utf-8')).hexdigest())
?

2022-09-01 06:25 UTC, HobbyistDev commented on yt_dlp/extractor/smotrim.py
> +            r'"https://player.smotrim.ru/iframe/video/id/(?P<video_id>[0-9]+)/[^"]*?/\?acc_video_id=(?P<player_id>[0-9]+)"',
Use `\d`

2022-09-24 05:54 UTC, Lesmiscore commented
@nikita-moor Are you willing to continue on this PR? If not, I'll be refactoring it

2022-09-24 06:16 UTC, nikita-moor commented
> @nikita-moor Are you willing to continue on this PR? If not, I'll be refactoring it (If I don't get response in 12 hours I'll start working on it)

No, I'm not going to elaborate this PR, so you are free to refactor it.

2022-09-24 09:30 UTC, closed without merging