[VK] Fix playlist URLs
yt-dlp/yt-dlp pull request #4930
Opened 2022-09-15 01:32 UTC by the-marenga

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

VK changed their playlist URLs from 
`https://vk.com/videosPAGEID?section=album_PLAYLISTID` to 
`https://vk.com/video/playlist/PAGEID_PLAYLISTID`, 
which meant new URLs had to be rewritten to the old format by hand to work. 
a70b71e85ad61c5f7c85ef920d72f949fb767d53 then removed support for the old version by changing the regex to fix another URL related issue.

This PR now restores playlist downloads by correctly parsing the new URL and indirectly restores support for the old format via an automatic redirect to the new page.

Fixes #2825

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-10-03 13:13 UTC, pukkandan requested changes

2022-10-03 13:13 UTC, pukkandan commented on yt_dlp/extractor/vk.py
> +            raise ExtractorError("Invalid URL", expected=True)
use single quotes

2022-10-09 01:50 UTC, merged

2022-10-17 23:41 UTC, BrunoKrinski commented
I'm still having problem with vk playlists links. I tested with several playslistas like this https://vk.com/videos-28532279?section=album_55889438 and this http://vk.com/video/playlist/-174476437_2 and it returns this error: ERROR: Unsupported URL: https://vk.com/badbrowser.php

2022-10-18 11:05 UTC, BrunoKrinski commented
Hi, thanks for answering me. I installed with pip. The version installed is 2022.10.04. And Python 3.9. It seems that it don't recognize as a vk link. It fall on Generic extractor: [generic] -174476437_2: Downloading webpage and then this error: ERROR: Unsupported URL: https://vk.com/badbrowser.php.

2022-10-18 16:17 UTC, the-marenga commented
The current version (2022.10.04) does not include this fix here yet. You either have to wait (~2-3 weeks?) for the new version to include it, or build yt-dlp from source

2022-10-18 21:00 UTC, BrunoKrinski commented
ok. I'll wait then. Thanks

2023-01-31 00:39 UTC, BrunoKrinski commented
Hi, sorry to bother again. Now I'm having another problem when downloading vk playslists. I can't continue or start new download from a playlist. Tried different playlists and all have the same problem.

[vk:uservideos] Extracting URL: https://vk.com/video/playlist/261475876_2
[vk:uservideos] 261475876_2: Downloading webpage
[download] Downloading playlist: vk3
[vk:uservideos] 261475876: Downloading JSON metadata
ERROR: Unknown error
[vk:uservideos] Playlist vk3: Downloading 1 items of 0
[download] Finished downloading playlist: vk3

2023-01-31 02:22 UTC, the-marenga commented
Yeah, their API changed again. The fix is pretty simple, so it should probably not take long to get merged. 

In the meantime you should be able to somewhat fix it yourself by adding a `section=playlist_` before the last number in your url. 

https://vk.com/video/playlist/261475876_2

becomes 

https://vk.com/video/playlist/261475876_section=playlist_2

You playlist is private, so I cant test it, but it should work. If not, you have to just wait for the real fix: https://github.com/yt-dlp/yt-dlp/pull/6122