[extractor/odnoklassniki] Boosty.to support
yt-dlp/yt-dlp pull request #5105
Opened 2022-10-01 19:08 UTC by megapro17

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Fix for 1440p and 2160p quality sorting

Example: https://ok.ru/video/313203755634

Add boosty.to support, fix https://github.com/yt-dlp/yt-dlp/issues/4212

Thanks for help @Lesmiscore 

Example:
https://boosty.to/vitaly/posts/acd4db50-18a8-40a0-a0bc-3bdee2022dbe
https://ok.ru/videoembed/3696046058009

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-10-02 20:29 UTC, pukkandan commented
Add test

2022-10-05 23:24 UTC, megapro17 commented
well i need to remove that test or change regex?

2022-10-06 00:08 UTC, pukkandan commented
embed tests go under `_WEBPAGE_TESTS`, not `_TESTS`

2022-10-07 16:23 UTC, Murtaught commented
I've cloned @megapro17 's repo and it seems to work great.
I've managed to download paid videos from Boosty by asking **yt-dlp** to use cookies from my browser like so:

```
./yt-dlp.sh --cookies-from-browser firefox https://boosty.to/CREATOR/posts/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee?share=post_link
```

Click on "share" button under the video to get link.
Thank you very much! 👍🏻

2022-11-04 15:14 UTC, pukkandan requested changes

2022-11-04 15:14 UTC, pukkandan commented on yt_dlp/extractor/odnoklassniki.py
> +            return self._extract_desktop(smuggle_url(url, {'referrer': "https://boosty.to"}))
line too long
```suggestion
        if (error == 'The author of this video has not been found or is blocked'
                and not smuggled.get('referrer') and mode == 'videoembed'):
            return self._extract_desktop(smuggle_url(url, {'referrer': 'https://boosty.to'}))
```

2022-11-06 23:41 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +    _TESTS = [
can u please tell me how? i just ran flake8

2022-11-06 23:42 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        # https://ok.ru/video/62036049272859-0) thus we allow missing title
is there any reason to put http, it redirects to https anyway

2022-11-06 23:43 UTC, megapro17 commented on yt_dlp/utils.py
> +    return url
@Lesmiscore please help

2022-11-07 00:47 UTC, bashonly commented on yt_dlp/utils.py
> +    return url
`base_url(url)` returns the same as `scheme_host_only(url)`

and `base_url(url).rstrip('/')` == `scheme_host_only(url, origin=True)`

2022-11-07 01:35 UTC, pukkandan commented on yt_dlp/extractor/odnoklassniki.py
> +        'md5': '5d2b64756e2af296e3b383a0bc02a6aa',
Do u know why all the md5s changed?

2022-11-07 01:35 UTC, pukkandan commented on yt_dlp/extractor/odnoklassniki.py
> +    _TESTS = [
fixed. flake8 doesnt change files. Just disable whatever auto-formatter u r using

2022-11-07 02:43 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
It seems that it works without entire method, plain url and embedded

2022-11-07 02:43 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        'md5': '5d2b64756e2af296e3b383a0bc02a6aa',
Yes, they're all correct

2022-11-07 03:17 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
```
-    @classmethod
-    def _extract_embed_urls(cls, url, webpage):
-        for x in super()._extract_embed_urls(url, webpage):
-            yield smuggle_url(x, {'referrer': base_url(url)})
-
```
I've removed this method, and nothing changed, it still can extract. What it does?

2022-11-07 04:39 UTC, Lesmiscore commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
The method is used by GenericIE to find embeds in an another sites like blogs

2022-11-07 15:04 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
Isn't this site is not meant to be embedded except boosty page?

> doesnt referer=url work?

How to test this thing?

2022-11-07 15:41 UTC, pukkandan commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
I'm confused. You are asking us what code you wrote is doing??

2022-11-07 15:43 UTC, megapro17 commented on yt_dlp/extractor/odnoklassniki.py
> +        yield from (smuggle_url(x, {'referrer': scheme_host_only(url)}) for x in super()._extract_embed_urls(url, webpage))
I didn't wrote that part :)

2022-11-07 16:02 UTC, merged