[extractor/doostream] Fix download of not embedded video
yt-dlp/yt-dlp pull request #5251
Opened 2022-10-15 12:26 UTC by Galiley

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

When the doodstream's video URL is not an embedded video (eg in the form of `https://dood.wf/e/<video_id>`), yt-dlp failed to download it. This PR should fix that issue

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-10-16 08:58 UTC, pukkandan requested changes
Also add test

2022-10-16 08:58 UTC, pukkandan commented on yt_dlp/extractor/common.py
> +
unnecessary

2022-10-16 08:58 UTC, pukkandan commented on yt_dlp/extractor/doodstream.py
> +        if self._match_group(url, 'type') == 'd':
```suggestion
        video_id, type_ = self._match_valid_url(url).group('id', 'type')
        if type_ == 'd':
```

2022-10-16 08:59 UTC, pukkandan requested changes

2022-10-16 08:59 UTC, pukkandan commented on yt_dlp/extractor/doodstream.py
> +            webpage = self._download_webpage(url, None)
```suggestion
            webpage = self._download_webpage(url, video_id)
```

2022-10-16 08:59 UTC, pukkandan commented on yt_dlp/extractor/doodstream.py
> +            video_id = self._html_search_regex(r'<iframe src=\"/e/([a-z0-9]+)\"', webpage, 'video_id')
```suggestion
            video_id = self._html_search_regex(r'<iframe src="/e/(\w+)"', webpage, 'video id')
```

2022-10-16 12:21 UTC, Galiley commented
@pukkandan I've tried to add a new test case to catch that particular issue but i've failed. I didn't use the one that required that fix because it's a piracy URL. However, i can provide you it in order to test on your own

2022-10-16 14:13 UTC, pukkandan commented
If you cannot even give a non pirated example this should perhaps not be merged

2022-10-16 16:54 UTC, Galiley commented
> If you cannot even give a non pirated example this should perhaps not be merged

Well the bug still exist whether or not the example is pirated

2022-10-17 08:36 UTC, pukkandan commented on yt_dlp/extractor/doodstream.py
> +            ['og:description', 'description', 'twitter:description'], webpage, default=title)
why?

2022-10-17 08:36 UTC, pukkandan approved these changes

2022-10-17 09:04 UTC, pukkandan commented on yt_dlp/extractor/doodstream.py
> +            ['og:description', 'description', 'twitter:description'], webpage, default=title)
if there is no description it should be empty
```suggestion
            ['og:description', 'description', 'twitter:description'], webpage, default=None)
```

2022-11-09 16:32 UTC, closed without merging

2022-12-26 15:35 UTC, navid-zamani commented
The whole damn point of yt-dlp is to download videos from sites, which, according to the lies of the organized crime (aka pirates aka content mafia), is “piracy”.

yt-dlp literally exists, to circumvent the artificial scarcity and imaginary monopolism schemes of such criminals, especially when they are state-sponsored by rogue regimes that support them.

So what the hell is this??

This is like a VPN going “We’re blocking tianmen-square-trush.org, because China banned it”.
You might as well call the project dead by suicide after schizophrenia.