Fix dowload from zen.yandex.ru (deprecated) dzen.ru instead
yt-dlp/yt-dlp pull request #5268
Opened 2022-10-17 16:56 UTC by lksj

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Zen.yandex.ru is deprecated, redirect to dzen.ru.
This PR shold fix this issue.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-10-18 05:21 UTC, pukkandan requested changes

2022-10-18 05:21 UTC, pukkandan commented on yt_dlp/extractor/yandexvideo.py
> -        'url': 'https://zen.yandex.ru/video/watch/6002240ff8b1af50bb2da5e3',
This URL still works in browser, and so should continue to work in yt-dlp

2022-10-18 05:21 UTC, pukkandan commented on yt_dlp/extractor/yandexvideo.py
> +        webpage = self._download_webpage(url, id)
?

2022-10-18 05:21 UTC, pukkandan commented on yt_dlp/extractor/yandexvideo.py
> -        'url': 'https://zen.yandex.ru/id/606fd806cc13cb3c58c05cf5',
same

2022-10-18 05:21 UTC, pukkandan commented on yt_dlp/extractor/yandexvideo.py
>          webpage = self._download_webpage(url, id)
same

2022-10-18 06:26 UTC, lksj commented
Let me explain.
Now zen.yandex.ru redirect to sso.passport.yandex.ru and next redirect to dzen.ru.
Direct dzen.ru redirect to sso.passport.yandex.ru and redirect to dzen.ru again.
Therefore, the download page is not possible. yt-dlp stopped on sso.passport.yandex.ru.
Double redirect is probably temporary.
Why redirect to sso.passport.yandex.ru? Cookies.
I was not able to get and put cookies in a simple way.
Download page and download page again turned out to be the easiest solution.
Yes, my fix is dirty hack, but it work.
I'm ready to refactor the solution, but I need a hint.
What in this case best way for cookies and redirects?

2022-10-25 10:06 UTC, pukkandan commented
tests dont pass

2022-10-25 10:20 UTC, merged