New extractor for Qingting.fm(蜻蜓FM)
yt-dlp/yt-dlp pull request #5329
Opened 2022-10-22 14:20 UTC by changren-wcr

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

ADD DESCRIPTION HERE

Fixes #5323

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-10-27 23:01 UTC, bashonly requested changes
this needs some work. I've suggested changes to:
 - make the extractor adhere to yt-dlp coding conventions
 - bypass downloading the desktop webpage altogether
 - properly parse the mobile webpage's JSON and extract info

2022-10-28 13:51 UTC, pukkandan commented on yt_dlp/extractor/qingting.py
> +    }
```suggestion
    _TESTS = [{
        'url': 'https://www.qingting.fm/channels/378005/programs/22257411/',
        'md5': '47e6a94f4e621ed832c316fd1888fb3c',
        'info_dict': {
            'id': '22257411',
            'ext': 'mp3',
            'title': '用了十年才修改，谁在乎教科书？-睡前消息-蜻蜓FM听头条',
        }
    }]
```

2022-10-28 13:52 UTC, pukkandan commented on yt_dlp/extractor/qingting.py
> +            'ext': 'm4a',
```suggestion
            'vcodec': 'none',
            'acode': 'm4a',
            'ext': 'm4a',
```

2022-10-29 06:16 UTC, changren-wcr commented
@bashonly @pukkandan Thanks for your patience and kindness! All the problems have been solved.

2022-10-29 10:54 UTC, pukkandan approved these changes

2022-10-29 10:54 UTC, pukkandan commented on yt_dlp/extractor/qingting.py
> +        channel_id, pid = self._match_valid_url(url).groups()
```suggestion
        channel_id, pid = self._match_valid_url(url).group('channel', 'id')
```

2022-10-29 10:54 UTC, pukkandan commented on yt_dlp/extractor/qingting.py
> +        info = self._search_json(r'window\.__initStores\s*=', web_page, 'program info', pid)
```suggestion
        webpage = self._download_webpage(
            f'https://m.qtfm.cn/vchannels/{channel_id}/programs/{pid}/', pid)
        info = self._search_json(r'window\.__initStores\s*=', webpage, 'program info', pid)
```

2022-10-29 11:08 UTC, bashonly approved these changes

2022-10-29 11:08 UTC, bashonly commented on yt_dlp/extractor/qingting.py
> +            'podcaster': traverse_obj(info, ('ProgramStore', 'podcasterInfo', 'podcaster', 'nickname')),
```suggestion
            'channel': traverse_obj(info, ('ProgramStore', 'channelInfo', 'title')),
            'uploader': traverse_obj(info, ('ProgramStore', 'podcasterInfo', 'podcaster', 'nickname')),
```

2022-10-29 11:08 UTC, bashonly commented on yt_dlp/extractor/qingting.py
> +            'podcaster': '马督工',
```suggestion
            'channel': '睡前消息',
            'uploader': '马督工',
```

2022-10-29 11:08 UTC, bashonly commented on yt_dlp/extractor/qingting.py
> +            'podcaster': '马督工',
```suggestion
            'channel': '睡前消息',
            'uploader': '马督工',
```

2022-10-29 15:14 UTC, bashonly approved these changes

2022-11-06 18:11 UTC, merged