[extractor/stripchat] fix unbound formats variable
yt-dlp/yt-dlp pull request #5475
Opened 2022-11-07 18:42 UTC by freezboltz

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

ADD DESCRIPTION HERE
fixed unbound formats variable

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-11-07 23:03 UTC, bashonly requested changes
Revert all the formatting changes (indentation, double quotes)

The 2 suggestions I've made are the only necessary changes

2022-11-07 23:55 UTC, bashonly commented on yt_dlp/extractor/stripchat.py
> +        for host in traverse_obj(data or [], (
```suggestion
        for host in traverse_obj(data, (
```
unnecessary

2022-11-07 23:58 UTC, bashonly approved these changes

2022-11-08 06:44 UTC, merged

2022-11-13 14:59 UTC, pro-ject143 commented
Any update? Still not able to download.

2023-01-01 17:32 UTC, pro-ject143 commented
Disappointing. Downloading off Stripchat is as a dead as a dodo.