[extractor/airtv] Add extractor
yt-dlp/yt-dlp pull request #5533
Opened 2022-11-14 13:41 UTC by HobbyistDev

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

This PR add site support for www.air.tv. Some of video from this site is also streamed in popular video stream website (eg: youtube). This is extractor didn't add support in embed.air.tv

Fixes #5132

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-12-08 17:29 UTC, pukkandan requested changes

2022-12-08 17:29 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +                formats.append({'url': source.get('src'), 'ext': 'mp4'})
Not this?
```suggestion
                formats.append({'url': source.get('src'), 'ext': ext})
```

2022-12-08 17:29 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +        return {
```suggestion

        formats, subtitles = self._get_formats_and_subtitle(nextjs_json, display_id)
        return {
```

2022-12-08 17:29 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +            'thumbnails': [{'url': thumbnail} for thumbnail in nextjs_json.get('default_thumbnails')],
```suggestion
            'thumbnails': [{'url': thumbnail} for thumbnail in traverse_obj(nextjs_json, ('default_thumbnails', ...)],
```

2022-12-08 17:29 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +            'channel_id': nextjs_json.get('channel') or nextjs_json.get('channel_slug'),
```suggestion
            'channel_id': traverse_obj(nextjs_json, 'channel', 'channel_slug'),
```

2022-12-08 17:29 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +            'description': nextjs_json.get('description') if nextjs_json.get('description') else None,
```suggestion
            'description': nextjs_json.get('description') or None,
```

2022-12-08 17:33 UTC, pukkandan commented on yt_dlp/extractor/airtv.py
> +            'thumbnails': [{'url': thumbnail} for thumbnail in traverse_obj(nextjs_json, ('default_thumbnails', ...)],
```suggestion
            'thumbnails': [
                {'url': thumbnail}
                for thumbnail in traverse_obj(nextjs_json, ('default_thumbnails', ...))],
```

2022-12-10 02:40 UTC, HobbyistDev commented on yt_dlp/extractor/airtv.py
> +                formats.append({'url': source.get('src'), 'ext': 'mp4'})
Nevermind, i just got the soultion

2022-12-10 08:29 UTC, merged