Add album_artist metadata to BandcampIE extractor (#5536)
yt-dlp/yt-dlp pull request #5537
Opened 2022-11-14 18:36 UTC by stelcodes

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

This patch adds an `album_artist` metadata field in the `BandcampIE` extractor class by scraping the track's webpage for the name of the artist who owns the album. This makes it easier to download albums into an `artist/album/track.mp3` directory structure when downloading compilation albums (tracks of varying artists).

Fixes #5536 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-11-14 22:34 UTC, pukkandan requested changes

2022-11-14 22:34 UTC, pukkandan commented on yt_dlp/extractor/bandcamp.py
> +            r'<h3 class="albumTitle">[\s\S]*by\s*<span>\s*<a href=".*">\s*(.*)\s*</a>',
```suggestion
            r'<h3 class="albumTitle">[^>]*by\s*<span>\s*<a href="[^>]+">\s*([^>]+?)\s*</a>',
```

2022-11-14 22:34 UTC, pukkandan commented on yt_dlp/extractor/bandcamp.py
> +            webpage, "album artist", group=1, fatal=fatal)
```suggestion
            webpage, 'album artist', fatal=False)
```

2022-11-14 22:34 UTC, pukkandan commented on yt_dlp/extractor/bandcamp.py
> +            webpage, "album artist", group=1, fatal=fatal)
This does not need to be a function

2022-11-16 01:03 UTC, stelcodes commented on yt_dlp/extractor/bandcamp.py
> +            r'<h3 class="albumTitle">[\s\S]*by\s*<span>\s*<a href=".*">\s*(.*)\s*</a>',
Ah nice I like that better

2022-11-16 01:54 UTC, pukkandan commented
No. I will squash everything before merge. So commit messages don't really matter

2022-11-16 01:55 UTC, pukkandan commented on yt_dlp/extractor/bandcamp.py
> +            f.write(webpage)
?

2022-11-16 02:27 UTC, stelcodes commented
@pukkandan Oh jeez I committed the wrong bit. That's embarrassing. Fixed!

2022-11-16 02:32 UTC, stelcodes commented
Added myself to the contributors doc too if that's alright.

2022-11-26 03:30 UTC, stelcodes commented
@pukkandan ping - just letting you know PR is ready for review again

2022-11-26 07:37 UTC, pukkandan commented
Pls update tests

2022-12-31 04:42 UTC, stelcodes commented
Updated to include tests in the `BandcampIE` class. Running `python test/test_download.py TestDownload.test_Bandcamp` locally gave me errors for pretty much every other test in the `_TESTS` list.  Confusing but I just commented them out and wrote a test that covers a track with a differing artist/album_artist that passes.

2022-12-31 04:56 UTC, pukkandan commented
The test suite wasn't as strict till recently. So many of the tests are incomplete by current standards. It's expected to be fixed when we work on the extractor. Also, due to the nature of extractors, tests often break due to factors outside our control. In that case, we have to manually check and fix the test definitions.

2022-12-31 04:58 UTC, merged