[extractor/ciscowebex] Support password-protected videos
yt-dlp/yt-dlp pull request #5601
Opened 2022-11-20 00:17 UTC by damianoamatruda

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-11-20 01:00 UTC, pukkandan requested changes

2022-11-20 01:03 UTC, pukkandan commented on yt_dlp/extractor/ciscowebex.py
> +                method=cookies)
```suggestion
                method='cookies')
```

2022-11-20 10:03 UTC, damianoamatruda commented on yt_dlp/extractor/ciscowebex.py
> +            'uploader_id': stream.get('ownerUserName') or stream.get('ownerId'),
`ownerUserName` (e-mail address) _seems_ to be always available and is more informative, `ownerId` (ID corresponding to the e-mail address) is a backup value

2022-12-29 06:53 UTC, pukkandan commented on yt_dlp/extractor/ciscowebex.py
> +                self.raise_login_required(method='cookies')
```suggestion
                self.raise_login_required()
```

2022-12-29 06:53 UTC, pukkandan commented on yt_dlp/extractor/ciscowebex.py
> +                raise ExtractorError('Wrong password', expected=True)
```suggestion
                if password:
                    raise ExtractorError('Wrong password', expected=True)
                raise ExtractorError(
                    'This video is protected by a password, use the --video-password option', expected=True)
```

2022-12-29 06:54 UTC, merged