added the new url format for Gronkh and tests [Issue #5531]
yt-dlp/yt-dlp pull request #5628
Opened 2022-11-23 17:35 UTC by muddi900

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Gonkh.tv switched to a new url format. I have updated the regex to include both the new scheme and the old one. I have added new tests. However the tests will fail because `view_count` field is required and it is a dynamic value. I have tested it with the current accurate value and it works.

Fixes #5531

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-11-23 17:43 UTC, bashonly commented
Don't overwrite the old test, keep the old and add the new

> However the tests will fail because view_count field is required and it is a dynamic value

```py
'view_count': int,
```

2022-11-23 18:14 UTC, muddi900 commented
> Don't overwrite the old test case, keep the old and add the new. We want tests for both URL formats
> 
> > However the tests will fail because view_count field is required and it is a dynamic value
> 
> ```python
> 'view_count': int,
> ```

Thanks. The tests are passing

2022-11-23 22:03 UTC, bashonly requested changes

2022-11-23 22:03 UTC, bashonly commented on yt_dlp/extractor/gronkh.py
> +        {
this `only_matching` test case is redundant
```suggestion
```

2022-11-23 22:03 UTC, bashonly commented on yt_dlp/extractor/gronkh.py
> +    ]
```suggestion
    }]
```

2022-11-24 06:33 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +        {
```suggestion
    }, {
```

2022-11-24 06:33 UTC, pukkandan commented on yt_dlp/extractor/gronkh.py
> +    ]
```suggestion
    }]
```

2022-11-24 15:34 UTC, merged