[extractor/youtube] Retry manifest refresh to avoid ending download early when live stream is temporarily offline
yt-dlp/yt-dlp pull request #5670
Opened 2022-11-29 18:54 UTC by mzhou

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

</details>

Currently when downloading a YouTube live stream, if it goes offline (e.g. due to a problem on the uploader's end), yt-dlp prints a warning like:

```
WARNING: [youtube] Cannot find refreshed manifest for format 140; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Cannot find refreshed manifest for format 299; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

then considers the live stream over, proceeding to muxing.

This change makes the process of finding a refreshed manifest subject to `--extractor-retries` and `--retry-sleep extractor:`, so that downloading can continue without intervention as long as the live stream is back online within `extractor-retries * retry-sleep` seconds.

I tested this by starting a scheduled live stream, starting yt-dlp, then disconnecting the streaming software and confirming the retry messages from yt-dlp, and finally reconnecting the streaming software and observing that yt-dlp resumes downloading. I've also confirmed that the true end of the live stream is detected and yt-dlp proceeds to muxing fine.

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-11-30 00:55 UTC, pukkandan requested changes

2022-11-30 00:55 UTC, pukkandan commented on yt_dlp/extractor/youtube.py
> +                for retry in self.RetryManager():
```suggestion
                for retry in self.RetryManager(fatal=False):
```
Then remove the outer try

2022-11-30 00:55 UTC, pukkandan commented on yt_dlp/extractor/youtube.py
> +                        continue
No need to throw and catch error
```suggestion
                        if f:
                            return f['manifest_url'], f['manifest_stream_number'], is_live
                        elif is_live:
                            retry.error = f'Cannot find refreshed manifest for format {format_id}{bug_reports_message()}'
                        else:
                            retry.error = f'{video_id}: Video is no longer live'
```

2022-11-30 00:56 UTC, pukkandan commented
cc @Lesmiscore

2022-11-30 05:11 UTC, Lesmiscore approved these changes

2022-12-01 16:45 UTC, pukkandan commented on yt_dlp/extractor/youtube.py
>                  return None
unused try except

2022-12-01 16:45 UTC, pukkandan commented on yt_dlp/extractor/youtube.py
> +                    try:
?

2023-01-06 19:30 UTC, merged