[extractor/kick] Add extractor
yt-dlp/yt-dlp pull request #5736
Opened 2022-12-07 00:59 UTC by bashonly

kick.com is a twitch.tv clone currently in "beta"

Closes #5722

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

2022-12-21 00:42 UTC, bashonly commented
Update -- these pages actually exist now:
https://kick.com/privacy-policy
https://kick.com/terms-of-service

It appears the site does actually care about being legitimate

2022-12-29 07:52 UTC, pukkandan requested changes

2022-12-29 07:52 UTC, pukkandan commented on yt_dlp/extractor/kick.py
> +                self.write_debug('kick.com did not set XSRF-TOKEN cookie')
put this in `_real_initialize`

2022-12-29 16:57 UTC, pukkandan approved these changes

2022-12-29 16:57 UTC, pukkandan commented on yt_dlp/extractor/kick.py
> +            self.write_debug('kick.com did not set XSRF-TOKEN cookie')
```suggestion
    def _real_initialize(self):
        self._request_webpage(HEADRequest('https://kick.com/'), None, 'Setting up session')
        xsrf_token = self._get_cookies('https://kick.com/').get('XSRF-TOKEN')
        if not xsrf_token:
            self.write_debug('kick.com did not set XSRF-TOKEN cookie')
        KickBaseIE._API_HEADERS = {
            'Authorization': f'Bearer {xsrf_token.value}',
            'X-XSRF-TOKEN': xsrf_token.value,
        } if xsrf_token else {}
```

2022-12-29 17:31 UTC, merged

2023-01-06 07:05 UTC, camjac251 commented
Is this working still. I tried it out today with version `2023.01.02` and get this error
```
yt-dlp -U

Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)

yt-dlp https://kick.com/kmack710

[Kick] Setting up session
ERROR: [Kick] kmack710: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

```

2023-01-06 08:36 UTC, bashonly commented
@camjac251 I can't reproduce; it is still working for me. Can you open a site bug issue with a verbose log (the output of `yt-dlp -vU https://kick.com/kmack710`)?

2023-02-07 08:09 UTC, dragu commented
@bashonly 

```
$ ./yt-dlp https://kick.com/suspendas -vU
[debug] Command-line config: ['https://kick.com/suspendas', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, pyxattr-0.7.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1764 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[Kick] Setting up session
ERROR: [Kick] suspendas: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "./yt-dlp/yt_dlp/extractor/common.py", line 679, in extract
self.initialize()
File "./yt-dlp/yt_dlp/extractor/common.py", line 588, in initialize
self._real_initialize()
File "./yt-dlp/yt_dlp/extractor/kick.py", line 17, in _real_initialize
self._request_webpage(HEADRequest('https://kick.com/'), None, 'Setting up session')
File "./yt-dlp/yt_dlp/extractor/common.py", line 827, in _request_webpage
raise ExtractorError(errmsg, cause=err)

File "./yt-dlp/yt_dlp/extractor/common.py", line 809, in _request_webpage
return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3730, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/usr/lib/python3.9/urllib/request.py", line 523, in open
response = meth(req, response)
File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
response = self.parent.error(
File "/usr/lib/python3.9/urllib/request.py", line 561, in error
return self._call_chain(*args)
File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I contacted kick several times, they claimed to have added my IP address to the whitelist, and yet I also get a 403 error.

2023-02-07 10:32 UTC, bashonly commented
> I contacted kick several times, they claimed to have added my IP address to the whitelist, and yet I also get a 403 error.

Does kick.com load in your web browser?

2023-02-07 18:11 UTC, dragu commented
@bashonly I am running yt-dlp on the server, so I only checked in a text browser without JS, which is running cloudflare challange without success.

wget https://kick.com immediately gets 403