[extractor/DouyuTV]: Fix extractor and use new api
yt-dlp/yt-dlp pull request #6074
Opened 2023-01-22 06:33 UTC by hatienl0i261299

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

ADD DESCRIPTION HERE

Fixes #

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [ ] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [ ] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

I got some issue with old API like this:
![image](https://user-images.githubusercontent.com/36532499/213903664-97963cce-5f35-433e-9987-3bcf955e9cbe.png)

And i updated to new hash and API.

2023-01-22 10:56 UTC, pukkandan commented
Why should I spend time reviewing this when you are closing multiple PRs without addressing them?

2023-01-22 11:43 UTC, pukkandan requested changes

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +    _VALID_URL = r'https?://(?:www\.)?douyu(?:tv)?\.com/(topic/.*rid=|(?:[^/]+/))*(?P<id>[A-Za-z0-9]+)'
Don't use `.*`. The regex should not match any of these
```
https://www.douyu.com/topic/rid=6560603
https://www.douyu.com/topic/ydxc#rid=6560603
https://www.douyu.com/topic/ydxc?drid=6560603
```

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +            'ext': 'm3u8',
Wrong

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +            'description': str,
See other tests

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +            'is_live': True,
```suggestion
```

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +        auth = md5(f'room/{video_id}?aid=wp&client_sys=wp&time={tt}zNzMV1y4EMxOHS6I5WKm'.encode('utf-8')).hexdigest()
```suggestion
        auth = md5(f'room/{video_id}?aid=wp&client_sys=wp&time={tt}zNzMV1y4EMxOHS6I5WKm'.encode()).hexdigest()
```

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +        video_url = 'https://hls3-akm.douyucdn.cn/' + self._search_regex(r'(live/.*)', has_url, 'Extract has_url')
```suggestion
        video_url = url_join('https://hls3-akm.douyucdn.cn/',
                             self._search_regex(r'(live/.*)', room['hls_url'], 'URL')
```

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +                'time': tt,
duplicate code. Why not construct the query object first and use it to generate auth. Like this:
https://github.com/yt-dlp/yt-dlp/blob/074b2fae9076221faaa8697381428131ad968dc9/yt_dlp/extractor/kankanews.py#L29-L38

2023-01-22 11:43 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +from hashlib import md5
revert

2023-02-03 16:16 UTC, pukkandan commented on yt_dlp/extractor/douyutv.py
> +    _VALID_URL = r'https?://(?:www\.)?douyu(?:tv)?\.com/(topic/\w+\?rid=|(?:[^/]+/))*(?P<id>[A-Za-z0-9]+)/?$'
Why the `$`?

2023-02-05 13:00 UTC, hatienl0i261299 commented on yt_dlp/extractor/douyutv.py
> +    _VALID_URL = r'https?://(?:www\.)?douyu(?:tv)?\.com/(topic/\w+\?rid=|(?:[^/]+/))*(?P<id>[A-Za-z0-9]+)/?$'
Its not necessary, i removed it.

2023-02-08 20:41 UTC, merged

2023-05-11 07:25 UTC, suger520HT commented
How to modify douyutv.py to make "https://hls3-akm.douyucdn.cn/live/592541r8sShiTTrP/playlist.m3u8?wsSecret=76803a83bfa4d7281e33955d2dd201bb&wsTime=1683694929, 137 "Transformation" https://openhls-tct .douyucdn2.cn/ Live broadcast/16101rumZjzVOZu1.m3u8?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603", hla3a-akm cannot be used in Mainland China

2023-05-11 23:09 UTC, bashonly commented
@suger520HT
```diff
diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
index fa40844df..c138d6fb0 100644
--- a/yt_dlp/extractor/douyutv.py
+++ b/yt_dlp/extractor/douyutv.py
@@ -111,7 +111,7 @@ def _real_extract(self, url):
         if room.get('show_status') == '2':
             raise ExtractorError('Live stream is offline', expected=True)
 
-        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
+        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
         formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
 
         title = unescapeHTML(room['room_name'])
```

2023-05-12 02:05 UTC, suger520HT commented
Can you remove /playlist in "https://openhls-tct/ .douyucdn2.cn/ Live broadcast/16101rumZjzVOZu1/playlist.m3u8?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603"

2023-05-12 02:06 UTC, suger520HT commented
> @suger520HT
> 
> ```diff
> diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
> index fa40844df..c138d6fb0 100644
> --- a/yt_dlp/extractor/douyutv.py
> +++ b/yt_dlp/extractor/douyutv.py
> @@ -111,7 +111,7 @@ def _real_extract(self, url):
>          if room.get('show_status') == '2':
>              raise ExtractorError('Live stream is offline', expected=True)
>  
> -        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> +        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
>          formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
>  
>          title = unescapeHTML(room['room_name'])
> ```

Can you remove /playlist in "https://openhls-tct/ .douyucdn2.cn/ Live broadcast/16101rumZjzVOZu1/playlist.m3u8?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603"

2023-05-12 02:08 UTC, suger520HT commented
> @suger520HT
> 
> ```diff
> diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
> index fa40844df..c138d6fb0 100644
> --- a/yt_dlp/extractor/douyutv.py
> +++ b/yt_dlp/extractor/douyutv.py
> @@ -111,7 +111,7 @@ def _real_extract(self, url):
>          if room.get('show_status') == '2':
>              raise ExtractorError('Live stream is offline', expected=True)
>  
> -        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> +        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
>          formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
>  
>          title = unescapeHTML(room['room_name'])
> ```

Can you remove the /playlist in "https://openhls-tct/ .douyucdn2.cn/ Live /16101rumZjzVOZu1/playlist.m3u8?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603", only Can you remove /playlist in "https:// openhls- tct/ .douyucdn2.cn/ Live /16101rumZjzVOZu1.m3u8?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603" to play with /playlist will not play

2023-05-12 02:18 UTC, suger520HT commented
![image](https://github.com/yt-dlp/yt-dlp/assets/106970209/f4408892-8536-409a-af2d-60d6c7a67d86)
You need to delete the /playlist, and then replace hls3a-akm.douyucdn.cn with openhls-tct.douyucdn.cn to play it, otherwise the parsed link is /playlist.m3u8....it will not play

2023-05-12 02:29 UTC, bashonly commented
@suger520HT see edit

2023-05-12 02:30 UTC, suger520HT commented
thank you

2023-05-12 02:36 UTC, suger520HT commented
![image](https://github.com/yt-dlp/yt-dlp/assets/106970209/335133c3-78f8-40b5-83e9-610a06b78b8f)
Problem solved, thank you very much sir

2023-05-12 02:49 UTC, gamer191 commented
@bashonly do you think that patch should be merged into master?

2023-05-12 02:54 UTC, bashonly commented
I don't know enough about the site or the accessibility of these HLS URLs to make that call

2023-05-12 04:58 UTC, suger520HT commented
I don't know, I only know that hls3a-akm cannot use this domain name in mainland China

> 我对网站或这些HLS URL的可访问性不够了解，无法进行该调用

2023-05-12 05:01 UTC, suger520HT commented
> I don't know enough about the site or the accessibility of these HLS URLs to make that call

I don't know,
hls3a-akm breaks after a few seconds of playback in mainland China

2023-05-12 05:03 UTC, suger520HT commented
> I don't know enough about the site or the accessibility of these HLS URLs to make that call

Using a proxy and then using hls3a-akm will not interrupt the playback after a few seconds

2023-05-12 05:05 UTC, suger520HT commented
Can you set conditions for hls3a-akm? If it can’t play, switch to openhls-tct.douyucdn2.cn

2023-05-12 06:39 UTC, suger520HT commented
> @suger520HT
> 
> ```diff
> diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
> index fa40844df..79621a2ac 100644
> --- a/yt_dlp/extractor/douyutv.py
> +++ b/yt_dlp/extractor/douyutv.py
> @@ -111,8 +111,8 @@ def _real_extract(self, url):
>          if room.get('show_status') == '2':
>              raise ExtractorError('Live stream is offline', expected=True)
>  
> -        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> -        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
> +        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> +        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url.replace('/playlist.m3u8', '.m3u8'), room_id)
>  
>          title = unescapeHTML(room['room_name'])
>          description = room.get('show_details')
> ```

https:// openhls-tct/ .douyucdn2.cn/live/16101rumZjzVOZu1.flv?wsSecret=5ead1ab74a99de9f865906e94c50e14c&wsTime=1683787603 Change to output.flv? The effect is better m3u8 will eat and upload flv but not

2023-05-12 14:14 UTC, suger520HT commented
> @suger520HT
> 
> ```diff
> diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
> index fa40844df..79621a2ac 100644
> --- a/yt_dlp/extractor/douyutv.py
> +++ b/yt_dlp/extractor/douyutv.py
> @@ -111,8 +111,8 @@ def _real_extract(self, url):
>          if room.get('show_status') == '2':
>              raise ExtractorError('Live stream is offline', expected=True)
>  
> -        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> -        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
> +        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> +        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url.replace('/playlist.m3u8', '.m3u8'), room_id)
>  
>          title = unescapeHTML(room['room_name'])
>          description = room.get('show_details')
> ```
Ask if you can generate a streamlined link http://openhls-tct.douyucdn2.cn/live/252140rz7aIq14cx.flv?uuid=

2023-05-12 14:14 UTC, suger520HT commented
> @suger520HT
> 
> ```diff
> diff --git a/yt_dlp/extractor/douyutv.py b/yt_dlp/extractor/douyutv.py
> index fa40844df..79621a2ac 100644
> --- a/yt_dlp/extractor/douyutv.py
> +++ b/yt_dlp/extractor/douyutv.py
> @@ -111,8 +111,8 @@ def _real_extract(self, url):
>          if room.get('show_status') == '2':
>              raise ExtractorError('Live stream is offline', expected=True)
>  
> -        video_url = urljoin('https://hls3-akm.douyucdn.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> -        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url, room_id)
> +        video_url = urljoin('https://openhls-tct.douyucdn2.cn/', self._search_regex(r'(live/.*)', room['hls_url'], 'URL'))
> +        formats, subs = self._extract_m3u8_formats_and_subtitles(video_url.replace('/playlist.m3u8', '.m3u8'), room_id)
>  
>          title = unescapeHTML(room['room_name'])
>          description = room.get('show_details')
> ```

Ask if you can generate a streamlined link http://openhls-tct.douyucdn2.cn/live/252140rz7aIq14cx.flv?uuid=

2023-06-12 11:46 UTC, suger520HT commented
douyu的那个失效了 能修复一下吗

2023-06-12 12:21 UTC, suger520HT commented
http://openhls-tct.douyucdn2.cn/dyliveflv1a/5168755rYvNEHQvI.m3u8?txSecret=ed532144e99db67a9cb97d81f56d01e2&txTime=648725f3
现在的有效格式