[extractor/vocaroo] Add Vocaroo extractor
yt-dlp/yt-dlp pull request #6117
Opened 2023-01-30 09:18 UTC by qbnu

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

(Description from https://github.com/ytdl-org/youtube-dl/pull/29369)

Adds support for [Vocaroo](https://www.vocaroo.com/), "the premier voice recording service." The site lacks any sort of metadata for its uploads and all come down as MP3s, so much of this extractor is hardcoded, making it quite fast. While Vocaroo does allow you to easily download individual files from their site, youtube-dl support will allow users to extract Vocaroo embeds with the generic extractor and download many Vocaroo files at once.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-01-30 12:02 UTC, pukkandan requested changes

2023-01-30 12:02 UTC, pukkandan commented on yt_dlp/extractor/vocaroo.py
> +            'ext': 'mp3',
```suggestion
            'ext': 'mp3',
            'vcodec': 'none',
```

2023-01-30 12:02 UTC, pukkandan commented on yt_dlp/extractor/vocaroo.py
> +            'title': f'Vocaroo {audio_id}',
```suggestion
            'title': '',
```

2023-01-30 12:02 UTC, pukkandan commented on yt_dlp/extractor/vocaroo.py
> +    _VALID_URL = r'https?://(?:www\.)?(?:vocaroo\.com|voca\.ro)/(?:embed/)?(?P<id>[a-zA-Z0-9]{11,12})'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?(?:vocaroo\.com|voca\.ro)/(?:embed/)?(?P<id>\w+)'
```

2023-01-30 12:03 UTC, pukkandan commented
> youtube-dl support will allow users to extract Vocaroo embeds with the generic extractor and download many Vocaroo files at once.

The current extractor doesn't seem to support embeds. Provide example

2023-02-01 22:07 UTC, qbnu commented
There is an `x-bz-upload-timestamp` header in the response which has the UNIX timestamp of when each file was uploaded. Should this be used as the value for `timestamp`, and is there a way to do it without sending an extra request?

2023-02-04 15:15 UTC, dirkf commented
You can can make a `HEAD` request in the extractor (or `GET` if the site doesn't support it) and get the header value out of the response. Any other solution would be overkill.

Actually, sending the request might be a good thing. The extractor currently just guesses that an audio file exists with the given ID, whereas making at least one request will reveal whether the ID is valid (or perhaps that the extractor's guess is no longer valid).

In my test I found that a `media1....` URL redirected to `media....`.

2023-02-04 18:21 UTC, qbnu commented
I made the logic for the media subdomain match the logic of the site
```js
function (e) {
    if (e.length) {
        if (11 == e.length)
            return ControlConfig.mediaMp3FileUrl;
        if (12 == e.length && '1' == e[0])
            return ControlConfig.mediaMp3FileUrl1;
        if (10 == e.length)
            return ControlConfig.mediaMp3FileUrl1
    }
    return ControlConfig.mediaMp3FileUrl
}
```
> In my test I found that a `media1....` URL redirected to `media....`.

Can you give an example? I assumed they were mirrors.

2023-02-12 13:17 UTC, pukkandan requested changes

2023-02-12 13:17 UTC, pukkandan commented on yt_dlp/extractor/vocaroo.py
> +        resp = self._request_webpage(req, audio_id)
```suggestion
        resp = self._request_webpage(HEADRequest(url), audio_id, headers=http_headers)
```

2023-02-12 13:17 UTC, pukkandan commented on yt_dlp/extractor/vocaroo.py
> +            'http_headers': http_headers,
```suggestion
        return {
            'id': audio_id,
            'title': '',
            'url': url,
            'ext': 'mp3',
            'timestamp': float_or_none(resp.getheader('x-bz-upload-timestamp'), scale=1000),
            'vcodec': 'none',
            'http_headers': http_headers,
```

2023-02-17 03:18 UTC, merged

2023-06-22 03:51 UTC, SuperSonicHub1 commented
Hey! Looks like some more of my code made it into yt-dlp. I have no issue with my code being used without permission—it is public domain after all—but being mentioned would have been nice; would've been happy to help and would have closed the PR in youtube-dl. That's all; sorry for waking a sleeping thread.

2023-06-22 03:54 UTC, pukkandan commented
Darn it. I do mention usually, but I didn't notice for this since OP said:

> * [x]  I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

Too late to do anything about commit message now, but I'll add you to changelog

2023-06-22 03:55 UTC, pukkandan commented
@SuperSonicHub1 You are credited in commit message and changelog

2023-06-22 04:19 UTC, SuperSonicHub1 commented
Thanks, @pukkandan!