feat: add extractor for ebay video listings
yt-dlp/yt-dlp pull request #6170
Opened 2023-02-06 01:31 UTC by JChris246

### Description of your *pull request* and other information

This PR seeks to add an extractor for ebay video listings as described in issue #6134

Fixes #6134 

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-02-06 01:55 UTC, pukkandan requested changes

2023-02-06 01:55 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +        video_json = self._search_json(r'"video":\s*', webpage, "video_json", video_id)
```suggestion
        video_json = self._search_json(r'"video":', webpage, 'video json', video_id)
```

2023-02-06 01:55 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +                    playlist_map.get(key), video_id, fatal=False))
```suggestion
        formats = []
        for key, url in video_json['playlistMap'].items():
            if key == 'HLS':
                formats.extend(self._extract_m3u8_formats(url, video_id, fatal=False))
            elif key == 'DASH':
                formats.extend(self._extract_mpd_formats(url, video_id, fatal=False))
            else:
                # Add a warning here
```

2023-02-06 01:55 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +            'skip_download': True,
```suggestion
            'skip_download': 'm3u8'',
```

2023-02-08 05:30 UTC, pukkandan requested changes
Does a product only ever have a single video? If so, isn't it better to use the webpage's title instead of `video_json.title`?

2023-02-08 05:30 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +    }
```suggestion
    _TESTS = [{
        'url': 'https://www.ebay.com/itm/194509326719',
        'info_dict': {
            'id': '194509326719',
            'ext': 'mp4',
            'title': 'HELIX upload [AN_Master_A04B.mp4] - 1666069406072',
        },
        'params': {'skip_download': 'm3u8'}
    }]
```

2023-02-08 05:30 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +        video_json = self._search_json(r'"video":\s*', webpage, "video_json", video_id)
quotes unresolved

2023-02-08 05:30 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +                    playlist_map.get(key), video_id, fatal=False))
You only applied half of my suggestion. `if not playlist_map` isn't needed

2023-02-08 05:30 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +            'skip_download': True,
again, only applying half!

2023-02-08 23:22 UTC, JChris246 commented
> Does a product only ever have a single video? If so, isn't it better to use the webpage's title instead of `video_json.title`?

I wasn't able to find any where there was more than one video, so I supposed it's safe to assume it they all only have a single video. I made the change to use the html title instead 👍

2023-02-09 04:48 UTC, pukkandan approved these changes

2023-02-09 04:48 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +            'title': self._html_extract_title(webpage),
```suggestion
            'title': remove_end(self._html_extract_title(webpage), ' | eBay'),
```

2023-02-09 04:48 UTC, pukkandan commented on yt_dlp/extractor/ebay.py
> +                self.report_warning('unsupported format found: %s' % key, video_id)
```suggestion
                self.report_warning(f'Unsupported format {key}', video_id)
```

2023-02-17 03:14 UTC, merged