[eroprofile] Add album downloader
yt-dlp/yt-dlp pull request #658
Opened 2021-08-09 03:47 UTC by jhwgh1968

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] New extractor

---

### Description of your *pull request* and other information

This adds an album extractor to adult website EroProfile.

I don't think it needs to handle authentication, as each video should handle logging in on its own.

2021-08-09 22:21 UTC, pukkandan requested changes

2021-08-09 22:21 UTC, pukkandan commented on yt_dlp/extractor/eroprofile.py
> +    _NETRC_MACHINE = 'eroprofile'
```suggestion
```
since you aren't logging in

2021-08-09 22:21 UTC, pukkandan commented on yt_dlp/extractor/eroprofile.py
> +                            for uri in re.findall(r'href=".*?(/m/videos/view/[^"]+)"', webpage)]
Use `InAdvancePagedList` if the number of items in a page is known in advance, else yield the videos

See https://github.com/yt-dlp/yt-dlp/pull/657#discussion_r685516029

2021-08-10 03:42 UTC, jhwgh1968 commented
I believe I have fixed it, @pukkandan.

There is one odd thing with this: the output message order. Is this okay?
```
[debug] [EroProfile:album] Extracting URL: https://www.eroprofile.com/m/videos/album/....
[EroProfile:album] ...: Downloading playlist page 1
[download] Downloading playlist: ...
[EroProfile:album] ...: Downloading playlist page 2
[EroProfile:album] ...: Downloading playlist page 3
```

2021-08-10 13:47 UTC, pukkandan commented on yt_dlp/extractor/eroprofile.py
> +                                    playlist_title)
```suggestion
    def _extract_from_page(self, page):
        for url in re.findall(r'href=".*?(/m/videos/view/[^"]+)"', page):
            yield self.url_result(f'https://www.eroprofile.com{url}', EroProfileIE.ie_key())

    def _entries(self, playlist_id, first_page):
        yield from self._extract_from_page(first_page)

        page_urls = re.findall(rf'href=".*?(/m/videos/album/{playlist_id}\?pnum=(\d+))"', first_page)

        for url, n in page_urls[1:]:
            yield from self._extract_from_page(self._download_webpage(
                f'https://www.eroprofile.com{url}',
                playlist_id, note=f'Downloading playlist page {int(n) - 1}'))

    def _real_extract(self, url):
        playlist_id = self._match_id(url)
        first_page = self._download_webpage(url, playlist_id, note='Downloading playlist')
        playlist_title = self._search_regex(
            r'<title>Album: (.*) - EroProfile</title>', first_page, 'playlist_title')

        return self.playlist_result(self._entries(playlist_id, first_page), playlist_id, playlist_title)
```

2021-08-10 13:51 UTC, merged

2021-08-15 01:57 UTC, jhwgh1968 commented
@pukkandan it seems that the yield refactor caused it to skip over pages. Hopefully I will have a second PR to fix this soon.