[extractor/discogs] Add extractor
yt-dlp/yt-dlp pull request #6624
Opened 2023-03-24 22:00 UTC by rjy

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Add an extractor for the playlists embedded in Release and Master Release pages on discogs.com (an online music database). The generic extractor used to be able to read these, but that stopped working a long time ago.

Example URLs:

- https://www.discogs.com/release/1-The-Persuader-Stockholm
- https://www.discogs.com/master/113-Vince-Watson-Moments-In-Time

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-04-15 22:14 UTC, bashonly requested changes

2023-06-14 11:51 UTC, bashonly approved these changes

2023-06-14 11:51 UTC, bashonly commented on yt_dlp/extractor/discogs.py
> +from .common import InfoExtractor
```suggestion
from .common import InfoExtractor
from .youtube import YoutubeIE
```

2023-06-14 11:51 UTC, bashonly commented on yt_dlp/extractor/discogs.py
> +            for video in traverse_obj(response, ('videos', lambda _, v: v['uri']))]
```suggestion
        entries = [
            self.url_result(video['uri'], YoutubeIE, video_title=video.get('title'))
            for video in traverse_obj(response, ('videos', lambda _, v: YoutubeIE.suitable(v['uri'])))]
```

2023-06-14 13:46 UTC, pukkandan approved these changes

2023-06-14 13:46 UTC, pukkandan commented on yt_dlp/extractor/discogs.py
> +    _VALID_URL = r'https?://(?:www\.)?discogs\.com/(?P<type>(release|master))/(?P<id>\d+)'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?discogs\.com/(?P<type>release|master)/(?P<id>\d+)'
```

2023-06-14 18:40 UTC, merged