[extractor/cda] Fix age restriction
yt-dlp/yt-dlp pull request #6638
Opened 2023-03-25 22:09 UTC by Szpachlarz

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This pull request updates age confirmation to work with the new form. The code is as it was proposed by @emqi, the original poster of #5980.

Fixes #5980

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-03-26 09:00 UTC, pukkandan commented
Have you run the extractor download tests? Pls update test defenitions as needed

2023-03-26 22:31 UTC, Szpachlarz commented
I've fixed the tests and removed some dead code.

2023-04-18 12:53 UTC, selfisekai requested changes

2023-04-18 12:53 UTC, selfisekai commented on yt_dlp/extractor/cda.py
> -        'url': 'http://www.cda.pl/video/1273454c4',
both are piracy, replace with https://www.cda.pl/video/8753244c4/vfilm

2023-08-06 12:19 UTC, dirkf commented
A URL without `/vfilm` redirects to the `/vfilm` URL but the redirected URL doesn't pass the age confirmation because the extractor is still sending the original URL.
```diff
     def _web_extract(self, video_id, url):
         self._set_cookie('cda.pl', 'cda.player', 'html5')
         player_url = '{0}/video/{1}/vfilm'.format(self._BASE_URL, video_id)
-        webpage = self._download_webpage(player_url, video_id)
+        webpage, urlh = self._download_webpage_handle(player_url, video_id)
+        url = urlh.geturl()

```

2024-05-01 16:34 UTC, Lupenus commented
So is this thread dead or something?

2024-05-16 22:41 UTC, closed without merging