[extractor/sbs] Overhaul extractor for new APIs
yt-dlp/yt-dlp pull request #6839
Opened 2023-04-17 00:35 UTC by vidiot720

### Description of your *pull request* and other information

From dirkf's PR: Australian provider SBS has changed its hosting arrangements and APIs, breaking the existing extractor.

The PR is intended to deal with the new APIs.

Some specialisations of extractor methods are included:

-    `_download_webpage_handle()` detects geo-restriction
-    `_extract_m3u8_formats()` defaults to the native downloader.

That PR was developed for upstream, so adjusted for deprecations and other legacy compatibility inclusions. It also addresses issue with extracting and converting dxfp subtitles to other formats, since SBS deliver their UTF-8 encoded files with `encoding='UTF-16'`, in error. The workaround is included in utils.py. Note that it will *not* be triggered where a file actually encoded with UTF-16 is downloaded.

Fixes #6543. Adapt dirkf's PR [ytdl-org/youtube-dl#31880](https://github.com/ytdl-org/youtube-dl/pull/31880), with adjustments:
* Use media['name'] for title;
* Support urls including 'tv-program', and add a test url;
* Remove deprecated sort_formats() call;
* Support for capture and return of subtitles, with UTF-16 coding issue work-around when converting dfxp subs to srt.

See also [ytdl-org/youtube-dl#31841](https://github.com/ytdl-org/youtube-dl/issues/31841).

There are a few TODOs such as handling metadata for episode titles more nicely, and the downloaded subtitles (if not converted) will still have the wrong encoding. However these can be worked-around and don't cause exceptions during yt-dlp processing, so have raised this PR in order to get core extractor functions back ASAP.

<details open><summary>Boilerplate: bug fix, derived code, own tweaks.</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) See dirkf's release in [ytdl-org/youtube-dl#31880](https://github.com/ytdl-org/youtube-dl/pull/31880).

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-04-17 07:44 UTC, bashonly requested changes

2023-04-17 07:47 UTC, pukkandan commented on yt_dlp/utils.py
> +    # KLUDGE: confirm convert-subs works for dxfp with correct encoding. Note will not match actual UTF-16, given longer encoding.
Alo, wouldn't this potentially break other sites?

2023-04-17 08:35 UTC, pukkandan commented on yt_dlp/extractor/sbs.py
> +        media = traverse_obj(player_data, 'video_object', expected_type=dict) or {}
"potentially useful" doesn't mean anything unless you are actually using it. If you are, ofc put it in a variable. If not, don't.

2023-04-17 08:42 UTC, bashonly commented on yt_dlp/extractor/sbs.py
> +        media.update(self._call_api(video_id, 'mpx-media/' + video_id, fatal=not media))
`_PLAYER_API` makes sense to keep, I didn't suggest otherwise

I don't see the point of keeping the `_CATALOGUE_API` var though?

2023-04-17 12:53 UTC, pukkandan requested changes

2023-04-17 12:53 UTC, pukkandan commented on yt_dlp/extractor/sbs.py
> +
```suggestion
```

2023-04-17 12:53 UTC, pukkandan commented on yt_dlp/extractor/sbs.py
> +    _GEO_CHECK_URL = 'https://sbs-vod-prod-01.akamized.net/'
Single use. Inline

2023-04-17 12:53 UTC, pukkandan commented on yt_dlp/extractor/sbs.py
> +            media.update({'epName': epName})
```suggestion
        if traverse_obj(media, ('partOfSeries', {dict})):
            media['epName'] = traverse_obj(media, ('title', {str}))
```

2023-04-17 13:27 UTC, bashonly approved these changes

2023-04-17 13:27 UTC, bashonly commented on yt_dlp/extractor/sbs.py
> +                'duration': ('duration', ({float_or_none}, {parse_duration})),
for livestreams, `liveStream` is `True` in catalogue API JSON
```suggestion
                'duration': ('duration', ({float_or_none}, {parse_duration})),
                'is_live': ('liveStream', {bool}),
```

2023-04-17 13:27 UTC, bashonly commented on yt_dlp/extractor/sbs.py
> +    HEADRequest,
sort class above function
```suggestion
    HEADRequest,
    float_or_none,
```

2023-04-18 03:10 UTC, bashonly requested changes

2023-04-18 03:10 UTC, bashonly commented on yt_dlp/extractor/sbs.py
> +            self.raise_no_formats('No formats are available', video_id=video_id)
fixing my own code
```suggestion
            if urlh:
                error_reasons = urlh.headers.get_all('x-error-reason') or []
                if 'geo-blocked' in error_reasons:
                    self.raise_geo_restricted(countries=['AU'])
            self.raise_no_formats('No formats are available', video_id=video_id)
```

2023-04-18 03:14 UTC, bashonly approved these changes
I've tested my fixes to the geo-bypass/geo-restricted code and everything's working now

2023-04-18 13:39 UTC, pukkandan commented on yt_dlp/extractor/sbs.py
> +
No, I wasn't

2023-04-18 23:46 UTC, merged

2023-04-19 23:11 UTC, bossanova808 commented
Thank you very much for this, things working very well again.