[extractor/wevidi] Add support for WeVidi
yt-dlp/yt-dlp pull request #6868
Opened 2023-04-19 23:06 UTC by truedread

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

WeVidi is a YouTube alternative video-sharing site that started in early 2021.

The extractor currently supports ripping WeVidi videos in all available formats (144p - 1080p). WeVidi encodes all of its content with `avc1.42E01E` (H.264 Constrained Baseline Profile Level 3) and `mp4a.40.2` (AAC-LC), always in an MP4 container.

Fixes #6129

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-04-20 19:06 UTC, bashonly requested changes

2023-04-21 03:41 UTC, bashonly approved these changes

2023-04-21 04:09 UTC, pukkandan requested changes

2023-04-21 04:09 UTC, pukkandan commented on yt_dlp/extractor/wevidi.py
> +                'resolution': resolution_map.get(res),
Set `height` instead

2023-04-21 04:09 UTC, pukkandan commented on yt_dlp/extractor/wevidi.py
> +            formats.append({
```suggestion
            yield {
```
No need for init-loop-append-return. You can wrap it in a `list` in `_real_extract`

2023-04-22 00:11 UTC, merged