Ensure dir existence for thumbnails and subtitles
yt-dlp/yt-dlp pull request #7985
Opened 2023-08-29 09:42 UTC by Riteo

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Fixes output template `pl_thumbnail`.

Before this PR, trying to download a playlist with an output template of type `pl_thumbnail` pointing to a missing subdirectory doesn't create it, instead erroring out.

This problem went unnoticed while downloading videos because they're written into an already ensured dir, while playlists called the thumbnail writing method directly.

~~The subtitle change, while technically not required (playlists don't usually have subs) is done for consistency with all the other metadata writing methods. I can remove it if there's the need but it shouldn't hurt.~~

Also I'm not really sure of the expected order of conditions, like, whether I should've put the checks right at the beginning or somewhere else. Please tell me if you'd like them somewhere else, I can change them no problem.

Example of a fixed invocation (tested with commit 4b3a6ef1b3e235ba9a45142830b6edb357c71696):

`yt-dlp -vU --no-config --flat-playlist --write-thumbnail -o 'pl_thumbnail:test/%(id)s.%(ext)s' https://youtube.com/playlist?list=PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir`

<details><summary>verbose log before fix</summary>

```
[debug] Command-line config: ['-vU', '--no-config', '--flat-playlist', '--write-thumbnail', '-o', 'pl_thumbnail:test/%(id)s.%(ext)s', 'https://youtube.com/playlist?list=PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 4b3a6ef1b
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.4.10-x86_64-with-libc (OpenSSL 3.1.2 1 Aug 2023, libc)
[debug] exe versions: ffmpeg git-2023-07-24-5b11ee9 (setts), ffprobe git-2023-07-24-5b11ee9
[debug] Optional libraries: certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading webpage
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: ULTRAKILL
[info] Downloading playlist thumbnail 3 ...
[info] Writing playlist thumbnail 3 to: test/PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir.jpg
ERROR: [Errno 2] No such file or directory: 'test/PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir.jpg'
Traceback (most recent call last):
  File "/home/riteo/srg/yt-dlp/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riteo/srg/yt-dlp/yt_dlp/YoutubeDL.py", line 1731, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riteo/srg/yt-dlp/yt_dlp/YoutubeDL.py", line 1860, in process_ie_result
    return self.__process_playlist(ie_result, download)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riteo/srg/yt-dlp/yt_dlp/YoutubeDL.py", line 1958, in __process_playlist
    self._write_thumbnails('playlist', ie_result, self.prepare_filename(ie_copy, 'pl_thumbnail'))
  File "/home/riteo/srg/yt-dlp/yt_dlp/YoutubeDL.py", line 4265, in _write_thumbnails
    with open(encodeFilename(thumb_filename), 'wb') as thumbf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test/PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir.jpg'
```

</details>

<details><summary>verbose log after fix</summary>

```
[debug] Command-line config: ['-vU', '--no-config', '--flat-playlist', '--write-thumbnail', '-o', 'pl_thumbnail:test/%(id)s.%(ext)s', 'https://youtube.com/playlist?list=PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: a675ef135
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.4.10-x86_64-with-libc (OpenSSL 3.1.2 1 Aug 2023, libc)
[debug] exe versions: ffmpeg git-2023-07-24-5b11ee9 (setts), ffprobe git-2023-07-24-5b11ee9
[debug] Optional libraries: certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You cannot update when running from source code; Use git to pull the latest changes
[youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading API parameters API JSON
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Downloading API JSON
[youtube:tab] PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: ULTRAKILL
[info] Downloading playlist thumbnail 3 ...
[info] Writing playlist thumbnail 3 to: test/PLFG57rtsH8Jso3qfd5eO6egyBtW3nyvir.jpg
[youtube:tab] Playlist ULTRAKILL: Downloading 81 items of 81
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 81
[download] Downloading item 2 of 81
[download] Downloading item 3 of 81
[download] Downloading item 4 of 81
[download] Downloading item 5 of 81
[download] Downloading item 6 of 81
[download] Downloading item 7 of 81
[download] Downloading item 8 of 81
[download] Downloading item 9 of 81
[download] Downloading item 10 of 81
[download] Downloading item 11 of 81
[download] Downloading item 12 of 81
[download] Downloading item 13 of 81
[download] Downloading item 14 of 81
[download] Downloading item 15 of 81
[download]  [...]

2023-09-26 04:20 UTC, bashonly requested changes

2023-09-26 04:20 UTC, bashonly commented on yt_dlp/YoutubeDL.py
> +
This should be moved below the next block of code (just before the `for` loop), so that we don't make directories when thumb writing is skipped

2023-09-26 04:20 UTC, bashonly commented on yt_dlp/YoutubeDL.py
> +        ''' Write thumbnails to file and return list of (thumb_filename, final_thumb_filename) or None if error '''
just to keep consistent with the `_write_subtitles` docstring
```suggestion
        ''' Write thumbnails to file and return list of (thumb_filename, final_thumb_filename); or None if error '''
```

2023-09-26 04:20 UTC, bashonly commented on yt_dlp/YoutubeDL.py
> +
As you said in the PR description, this is redundant/unnecessary. I think it should be removed

2023-10-11 09:40 UTC, bashonly approved these changes
LGTM

In the future, please do not force push; all commits will be squashed upon merge anyways

2023-10-13 07:57 UTC, coletdjnz approved these changes
seems fine to me

2023-10-13 17:59 UTC, Grub4K approved these changes

2023-10-13 20:01 UTC, merged