[XHamster] fix: extract uploader_id
yt-dlp/yt-dlp pull request #844
Opened 2021-08-31 19:04 UTC by octotherp

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

2021-08-31 22:53 UTC, pukkandan commented
Why is uploader same as uploader_id? From the tests, it doesn't look like it is the ID that is being extracted as `uploader`

2021-09-01 00:03 UTC, octotherp commented
There is no uploader_id in tests and no uploader_id in previous version.
There is uploader_id in site pages but it is pretty much a meaningless internal int id, API works through `lowercase(uploader)`. 
This patch is mostly a workaround so `--output '%(extractor)s/%(uploader_id)s/%(title)s-%(id)s.%(ext)s'` would work uniformely on all extractors (that I use) as there no way to configure yt-dlp per extractor and no way to do `uploader_id?uploader_id:uploader` in output formatter and it is better than empty uploader_id.

2021-09-01 13:26 UTC, pukkandan requested changes

2021-09-01 13:26 UTC, pukkandan commented on yt_dlp/extractor/xhamster.py
> +            uploader = try_get(video, lambda x: x['author']['name'], compat_str)
```suggestion
            uploader_url = url_or_none(try_get(video, lambda x: x['author']['pageURL']))
```

2021-09-01 13:26 UTC, pukkandan commented on yt_dlp/extractor/xhamster.py
> +                'uploader_id': uploader,
```suggestion
                'uploader': try_get(
                    video, lambda x: x['author']['name'], compat_str),
                'uploader_url': uploader_url,
                'uploader_id': uploader_url.split('/')[-1] if uploader_url else None,
```

2021-09-01 13:26 UTC, pukkandan commented on yt_dlp/extractor/xhamster.py
> +            'uploader_id': uploader,
```suggestion
            'uploader_id': uploader.lower() if uploader else None,
```

2021-09-01 13:28 UTC, merged