Fix cnbc.py / add CNBCVideoIE extractor
yt-dlp/yt-dlp pull request #8741
Opened 2023-12-10 01:23 UTC by gonzalezjo

### Description of your *pull request* and other information

Fixes #8378 by rewriting the CNBC video extractor.

- Removes `CNBCIE`, which is an extractor for a CNBC video platform that no longer exists.
- Updates CNBCVideoIE
    - Adds tests
    - Supports author, channel, formats, ID (of course), upload date, URL (of course), title (of course), description, duration, timestamp, and thumbnails.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2023-12-10 01:27 UTC, gonzalezjo commented
CCing @Noor-5, @zhijinwuu, and @ruiminggu, who all worked on this (we split the work evenly0 and agreed to license their contributions under Unlicense.

2023-12-11 01:02 UTC, pukkandan commented
Pls avoid force-pushing. If you happen to do so while someone's reviewing, GH just throws away the comments on the old commit. You can use as many commits as needed. We squash before merge

2024-02-02 23:16 UTC, seproDev requested changes

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +            ('page', 'page', 'layout', 1, 'columns', 0, 'modules', 0, 'data', 'uploadDate'))
Just inline this along with other data below
```suggestion
```

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +        }
I would simplify this like so and also extract some other values:
```suggestion
        return {
            'id': display_id,
            'display_id': display_id,
            'formats': self._extract_akamai_formats(player_data['playbackURL'], display_id),
            **self._search_json_ld(webpage, display_id, fatal=False),
            **traverse_obj(player_data, {
                'id': ('id', {str_or_none}),
                'title': ('title', {str}),
                'description': ('description', {str}),
                'author': ('author', ..., 'name', {str}),
                'timestamp': ('datePublished', {parse_iso8601}),
                'release_timestamp': ('uploadDate', {parse_iso8601}),
                'modified_timestamp': ('dateLastPublished', {parse_iso8601}),
                'thumbnail': ('thumbnail', {url_or_none}),
                'duration': ('duration', {int_or_none}),
                'channel': ('section', 'title', {str}),
            }, get_all=False),
        }
```
I think it also makes sense to primarily return the actual video id but keep the display_id as a fallback.

Please update the tests acordingly.

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +                'description': 'McDonald\'s unveiled its new spinoff brand known as CosMc\'s this week, announcing that the new brand\'s first location will open in Bolingbrook, Illinois. CosMc\'s dr
Use the md5 for long fields such as the description

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +                ],
No need to specify thumbnails like this.

Just let the test data be generated by running the tests without the data. All missing fields will be displayed in the error message.

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +from ..utils import traverse_obj, unified_strdate, url_or_none
```suggestion
from ..utils import int_or_none, parse_iso8601, str_or_none, url_or_none
from ..utils.traversal import traverse_obj
```

2024-02-02 23:16 UTC, seproDev commented on yt_dlp/extractor/cnbc.py
> +import json
```suggestion
```

2024-02-23 14:49 UTC, bashonly approved these changes

2024-02-23 16:07 UTC, merged