[extractor/gotostage] Add GoToStage extractor
yt-dlp/yt-dlp pull request #883
Opened 2021-09-03 10:05 UTC by poschi3

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

GoToStage is platform for recordings of Webinars. I added an extractor to download a video.

There is a [page for all videos](https://www.gotostage.com/). I used a [specific video](https://www.gotostage.com/channel/8901680603948959494/recording/60bb55548d434f21b9ce4f0e225c4895/watch) for testing.

2021-09-04 00:09 UTC, pukkandan requested changes

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +    try_get)
```suggestion
from ..utils import (
    try_get,
    url_or_none,
)
```

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +            'productReferenceKey': try_get(metadata, lambda x: x[0]['productRefKey'], compat_str),
If `product` etc are not present, the extraction will fail anyway, right? If so, use normal `[]` instead of `try_get`

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +            headers={'x-registrantkey': try_get(registration_response, lambda x: x['registrationKey'], compat_str)},
same as above. If this field is a must have for basic extraction to work, dont use try_get

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +            errnote='Unable to download video metadata')
I see you are using metadata[0] everywhere. So why not just do this instead:
```suggestion
        metadata = self._download_json(
            'https://api.gotostage.com/contents?ids=%s' % video_id,
            video_id,
            note='Downloading video metadata',
            errnote='Unable to download video metadata')[0]
```

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +            'is_live': False}
```suggestion
            'is_live': False
        }
```

2021-09-04 00:09 UTC, pukkandan commented on yt_dlp/extractor/gotostage.py
> +            'email': 'foobar@example.com'}
```suggestion
            'email': 'foobar@example.com'
        }
```

2021-09-06 17:22 UTC, poschi3 commented
@pukkandan Thank you for your review. I fixed your findings. Please let me know if there is more to do for me :-)

2021-09-07 17:11 UTC, merged