[ie/Turbo] Fix turbo extractor
yt-dlp/yt-dlp pull request #8927
Opened 2024-01-04 02:34 UTC by nbr23

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

The Turbo site has changes, and the extractor is currently broken. This fixes it, and adds support for "playlists" (through their RSS feeds).

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-01-07 10:45 UTC, seproDev commented
I don't think the extractor should be changed like this to add playlist support. If you do want to add playlist support, that should be done in a dedicated extractor. However, I am not convinced that adding the RSS feeds like this is super useful, as most posts don't contain videos. In its current form, the code also seems broken? Do you have an example where parsing the RSS feeds would be useful?

Looking at the site, it may be worth to split viously.com in to its own embed extractor instead. That would also deal more easily with the case where a single page contains multiple videos. And as a added bonus, it would also work on other sites using that CDN.

2024-01-07 21:10 UTC, nbr23 commented
Thanks a bunch for the feedback @seproDev, it all makes perfect sense to me!
I've made this into a viously.com embed extractor (this actually solves the RSS feed thing by design, so I love it).

Removing the old Turbo extractor too since it's broken anyway.

2024-01-08 03:57 UTC, seproDev requested changes

2024-01-08 03:57 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +        viously_players = get_elements_html_by_class('viously-player', webpage) + get_elements_html_by_class('vsly-player', webpage)
I think we can just
```suggestion
        viously_players = (get_elements_html_by_class('viously-player', webpage)
                           + get_elements_html_by_class('vsly-player', webpage))
        if not viously_players:
            return

```

2024-01-08 03:57 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +            }
Here I would actually call their API to extract the metadata
```suggestion
        def custom_decode(text):
            STANDARD_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
            CUSTOM_ALPHABET = 'VIOUSLYABCDEFGHJKMNPQRTWXZviouslyabcdefghjkmnpqrtwxz9876543210+/='
            data = base64.b64decode(text.translate(str.maketrans(CUSTOM_ALPHABET, STANDARD_ALPHABET)))
            return data.decode('utf-8').strip('\x00')

        for video_id in traverse_obj(viously_players, (..., {extract_attributes}, 'id')):
            data = self._download_json(
                f'https://www.viously.com/export/json/{video_id}', video_id, transform_source=custom_decode)
            yield {
                'id': video_id,
                'formats': self._extract_m3u8_formats(f'https://www.viously.com/video/hls/{video_id}/index.m3u8', video_id),
                **traverse_obj(data, ('video', {
                    'title': 'title',
                    'description': 'description',
                    'duration': ('duration', {int_or_none}),
                    'timestamp': ('iso_date', {parse_iso8601}),
                    'categories': ('category', {lambda x: [x['name']]}),
                })),
            }
```
Tests will need to be updated.

2024-01-08 03:57 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +)
```suggestion
import base64

from .common import InfoExtractor
from ..utils import (
    extract_attributes,
    get_elements_html_by_class,
    int_or_none,
    parse_iso8601,
)
from ..utils.traversal import traverse_obj
```

2024-01-08 04:10 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +    _API_URL = 'https://www.viously.com/video/hls/{0:}/index.m3u8'
```suggestion
```

2024-01-08 05:21 UTC, seproDev requested changes
Please don't force push

2024-01-08 05:21 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +        viously_players = get_elements_html_by_class('viously-player', webpage) + get_elements_html_by_class('vsly-player', webpage)
Sorry, this should use `re.findall`. The `get_element_by ` functions can throw on malformed HTML, so they could throw on any generic webpage.
```suggestion
        viously_players = re.findall(r'<div[^>]*class="(?:[^"]*\s)?v(?:iou)?sly-player(?:\s[^"]*)?"[^>]*>', webpage)
```

2024-01-08 05:21 UTC, seproDev commented on yt_dlp/extractor/viously.py
> +            'timestamp': float,
```suggestion
            'title': 'Turbo du 07/09/2014\xa0: Renault Twingo 3, Bentley Continental GT Speed, CES, Guide Achat Dacia...',
            'description': 'Turbo du 07/09/2014\xa0: Renault Twingo 3, Bentley Continental GT Speed, CES, Guide Achat Dacia...',
            'age_limit': 0,
            'upload_date': '20230328',
            'timestamp': 1680037507,
            'duration': 3716,
            'categories': ['motors'],
```

2024-01-09 01:32 UTC, bashonly requested changes

2024-01-09 01:32 UTC, bashonly commented on yt_dlp/extractor/viously.py
> +                continue
we can still extract if we have formats w/o metadata
```suggestion
            formats = self._extract_m3u8_formats(
                f'https://www.viously.com/video/hls/{video_id}/index.m3u8', video_id, fatal=False)
            if not formats:
                continue
            data = self._download_json(
                f'https://www.viously.com/export/json/{video_id}', video_id,
                transform_source=custom_decode, fatal=False)
```

2024-01-09 01:32 UTC, bashonly commented on yt_dlp/extractor/viously.py
> +                    'categories': ('category', {lambda x: [x['name']]}),
```suggestion
                    'categories': ('category', 'name', {str}, {lambda x: [x] if x else None}),
```
or else we could get `[None]` and `['']` etc

2024-01-09 01:32 UTC, bashonly commented on yt_dlp/extractor/viously.py
> +                    'description': 'description',
```suggestion
                    'title': ('title', {str}),
                    'description': ('description', {str}),
```

2024-01-09 02:04 UTC, bashonly approved these changes

2024-01-09 02:55 UTC, seproDev approved these changes

2024-01-09 03:11 UTC, merged