[CapitalTVCy] Add Capital TV Cyprus extractor
yt-dlp/yt-dlp pull request #8948
Opened 2024-01-07 18:21 UTC by pompos02

### Description of your *pull request* and other information

This pull request adds a new extractor for Capital TV Cyprus (CapitalTVCy). The extractor handles the extraction of YouTube video URLs embedded in the web pages of Capital TV Cyprus. This implementation ensures that users can download videos hosted on capitaltv.cy, which are embedded from YouTube.

The extractor parses the webpage to find the YouTube URL in the data-settings attribute of the video element and then delegates the actual video downloading to the YouTube extractor.

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-01-14 16:07 UTC, seproDev requested changes

2024-01-14 16:07 UTC, seproDev commented on yt_dlp/extractor/elementorgeneral.py
> +class ElementorGeneralIE(InfoExtractor):
Change this to `ElementorEmbedIE`

2024-01-14 18:04 UTC, seproDev approved these changes

2024-01-16 00:57 UTC, seproDev commented
Nothing is needed from you right now. The PR looks good from my side, but to be merged, a maintainer will also need to review it. They may raise additional things, I didn't catch. This will happen as time permits.

2024-01-18 02:55 UTC, pukkandan approved these changes

2024-01-18 02:55 UTC, pukkandan commented on yt_dlp/extractor/elementorembed.py
> +                    yield self.url_result(vimeo_url, ie='Vimeo')
Import relevent extractors and do 
```suggestion
                    yield self.url_result(vimeo_url, ie=VimeoIE)
```

2024-01-19 02:55 UTC, bashonly approved these changes

2024-01-19 03:00 UTC, merged