[cleanup] Misc (for 2024.01 release)
yt-dlp/yt-dlp pull request #8968
Opened 2024-01-10 01:00 UTC by bashonly

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-02-25 05:07 UTC, bashonly commented on yt_dlp/extractor/npo.py
> +                    continue
I don't agree with this. I don't want this merged. And I definitely don't want this merged in a PR with my name on it
```suggestion
                continue
```

2024-03-09 15:00 UTC, Grub4K requested changes

2024-03-09 15:00 UTC, Grub4K commented on devscripts/__init__.py
> +# Empty file
This should be removed. Empty `__init__` files are common and a comment saying `Empty file` doesn't help at all.

2024-03-09 22:46 UTC, Grub4K approved these changes

2024-03-10 19:33 UTC, Grub4K commented
Pushed as https://github.com/yt-dlp/yt-dlp/compare/47ab66db0f083a76c7fba0f6e136b21dd5a93e3b...615a84447e8322720be77a0e64298d7f42848693

2024-03-10 19:33 UTC, closed without merging