[patreon] fix not being able to download embedded videos
yt-dlp/yt-dlp pull request #8993
Opened 2024-01-14 02:40 UTC by johnvictorfs

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

It seems the `post_file['name']` attribute no longer exists in the Patreon video attributes (at least in the posts I tested, but unsure if it may exist in some cases), so the check for the case of m3u8 downloads were being skipped, so I changed it to also check for `post_file['duration']` and assume it is a video in this case. Is this a good enough check for this case?

![image](https://github.com/yt-dlp/yt-dlp/assets/37747572/797a58c6-98c5-49d8-9985-c956aaee63df)

Fixes #8973

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-01-18 03:12 UTC, pukkandan commented
What about the other code path in L272?

2024-01-19 22:02 UTC, johnvictorfs commented
> What about the other code path in L272?

I haven't actually found any cases where `post_file['name']` is returned, so I'm not sure if that path would ever be executed. I initially didn't want to remove it, as Patreon accepts various methods for uploading videos, and I wasn't sure if there was a case where it would return a name.

2024-01-21 20:55 UTC, kevo885 commented
Sorry if this is dumb question but how do you use this 'fix". I am already on latest version of nightly

2024-01-21 22:29 UTC, bashonly requested changes

2024-01-21 22:29 UTC, bashonly commented on yt_dlp/extractor/patreon.py
> +            elif name == 'video' or post_file.get('duration'):
```suggestion
            elif name == 'video' or determine_ext(post_file.get('url')) == 'm3u8':
```

2024-01-21 22:36 UTC, merged

2024-01-21 22:45 UTC, bashonly commented
@kevo885 `yt-dlp --update-to master`