[ie/ilpost] Add extractor
yt-dlp/yt-dlp pull request #9001
Opened 2024-01-14 21:04 UTC by CapacitorSet

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Adds an extractor for podcasts from Italian online newspaper https://www.ilpost.it/.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-01-16 21:57 UTC, seproDev requested changes
You also need to add a import to `_extractors.py`

2024-01-16 21:57 UTC, seproDev commented on yt_dlp/extractor/ilpost.py
> +        post_data = f"action=checkpodcast&cookie={ajax_cookie}&post_id={episode_id}&podcast_id={podcast_id}"
Use `urlencode_postdata` from `..utils`

2024-01-16 21:57 UTC, seproDev commented on yt_dlp/extractor/ilpost.py
> +        endpoint_metadata = self._search_json(start_pattern='var ilpostpodcast = ', end_pattern=';', string=webpage, name='endpoint-metadata', video_id=podcast_display_id)
Line is too long. Please follow the style guidelines.

2024-01-17 23:41 UTC, seproDev approved these changes

2024-01-17 23:41 UTC, seproDev commented on yt_dlp/extractor/ilpost.py
> +        )
```suggestion
        endpoint_metadata = self._search_json(
            r'var\s+ilpostpodcast\s*=', webpage, 'metadata', podcast_display_id)
```

2024-01-17 23:41 UTC, seproDev commented on yt_dlp/extractor/ilpost.py
> +        }))
```suggestion
        podcast_metadata = self._download_json(
            endpoint_metadata['ajax_url'], podcast_display_id, data=urlencode_postdata({
                'action': 'checkpodcast',
                'cookie': endpoint_metadata['cookie'],
                'post_id': episode_id,
                'podcast_id': podcast_id,
            }))
```

2024-01-17 23:41 UTC, seproDev commented on yt_dlp/extractor/ilpost.py
> +                'description': 'description',
```suggestion
                'title': ('title', {str}),
                'description': ('description', {str}),
```

2024-01-17 23:41 UTC, seproDev commented
Also, for the future, please don't force push.

2024-01-19 02:41 UTC, bashonly requested changes

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +from ..utils.traversal import traverse_obj
```suggestion
import functools

from .common import InfoExtractor
from ..utils import (
    ExtractorError,
    float_or_none,
    int_or_none,
    url_or_none,
    urlencode_postdata,
)
from ..utils.traversal import traverse_obj
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +    _VALID_URL = r'https?://(?:www\.)?ilpost\.it/episodes/(?P<id>[^/?]+).*'
```suggestion
    _VALID_URL = r'https?://(?:www\.)?ilpost\.it/episodes/(?P<id>[^/?#]+)'
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +        podcast_display_id = self._match_id(url)
`display_id` is the convention, shorter, and more distinct from `podcast_id`
```suggestion
        display_id = self._match_id(url)
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +            'display_id': podcast_display_id,
```suggestion
            'display_id': display_id,
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +            endpoint_metadata['ajax_url'], podcast_display_id, data=urlencode_postdata({
```suggestion
            endpoint_metadata['ajax_url'], display_id, data=urlencode_postdata({
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +            r'var\s+ilpostpodcast\s*=', webpage, 'metadata', podcast_display_id)
```suggestion
            r'var\s+ilpostpodcast\s*=', webpage, 'metadata', display_id)
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/_extractors.py
> +from .ilpost import IlPostExtractorIE
`Extractor` is redundant
```suggestion
from .ilpost import IlPostIE
```

2024-01-19 02:41 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +class IlPostExtractorIE(InfoExtractor):
```suggestion
class IlPostIE(InfoExtractor):
```

2024-01-19 02:42 UTC, bashonly commented on yt_dlp/extractor/ilpost.py
> +        webpage = self._download_webpage(url, podcast_display_id)
```suggestion
        webpage = self._download_webpage(url, display_id)
```

2024-01-19 02:49 UTC, bashonly approved these changes

2024-01-19 02:51 UTC, merged