[ie/boosty] Add extractor
yt-dlp/yt-dlp pull request #9144
Opened 2024-02-05 15:41 UTC by un-def

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

This is a replacement for a stale PR #8704. The code is written from scratch but with some information/ideas from the aforementioned PR.

Key differences:
* Post data is fetched via API, not extracted from a HTML page. It seems more resilient to use a versioned API rather than relying on JS data embedded into HTML markup and extracted with the help of regular expressions.
* Added support for posts with multiple videos.
* Added support for `video` post entry type. In contrast to `oK_video`, this type of entry is for videos hosted on external platforms, e.g., YouTube.

Fixes #5900

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-02-08 01:06 UTC, seproDev requested changes

2024-02-08 01:06 UTC, seproDev commented on yt_dlp/extractor/boosty.py
> +from ..utils import ExtractorError, dict_get, qualities, traverse_obj
```suggestion
from .common import InfoExtractor
from .youtube import YoutubeIE
from ..utils import (
    ExtractorError,
    int_or_none,
    qualities,
    str_or_none,
    url_or_none,
)
from ..utils.traversal import traverse_obj
```

2024-02-08 10:05 UTC, un-def commented
@seproDev thanks to the review! I've applied suggested changes and fixed tests.

2024-02-08 10:23 UTC, seproDev approved these changes

2024-02-09 00:31 UTC, bashonly approved these changes

2024-02-09 00:31 UTC, bashonly commented on yt_dlp/extractor/boosty.py
> +                          or self._html_extract_title(webpage, fatal=True))
`title` doesn't need to be fatal (and shouldn't imo), and I don't think we need two warnings
```suggestion
            post_title = self._og_search_title(webpage, default=None) or self._html_extract_title(webpage)
```

2024-02-09 00:31 UTC, bashonly commented on yt_dlp/extractor/boosty.py
> +        mp4_types = ('tiny', 'lowest', 'low', 'medium', 'high', 'full_hd', 'quad_hd', 'ultra_hd')
could be a class constant

2024-02-09 15:34 UTC, merged