[extractor/Douyin] fix Douyin
yt-dlp/yt-dlp pull request #9239
Opened 2024-02-18 15:19 UTC by 114514ns

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

fix Douyin exactor 

Fixes #
https://github.com/yt-dlp/yt-dlp/issues/8139
https://github.com/yt-dlp/yt-dlp/issues/8090
https://github.com/yt-dlp/yt-dlp/issues/7854

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-02-18 23:21 UTC, TheAznCoderPro commented
How do you pull-request a pull-request? (to fix the linter warnings)

2024-02-18 23:25 UTC, bashonly commented
I would advise not doing anything with this code until the author finishes the PR checklist

2024-02-19 03:26 UTC, TheAznCoderPro commented
@114514ns make sure to complete the template (the box about the licences)

2024-02-27 12:36 UTC, yifeikong commented
Any updates?

2024-02-27 23:32 UTC, TheAznCoderPro commented
> Any updates?

PR seems like it should be good to merge

2024-02-28 00:56 UTC, bashonly requested changes

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +        render_data = self._parse_json(webpage, video_id, fatal=False)
```suggestion
        detail = traverse_obj(self._download_json(
            'https://www.douyin.com/aweme/v1/web/aweme/detail/', video_id,
            'Downloading web detail JSON', 'Failed to download web detail JSON',
            query={'aweme_id': video_id}, fatal=False), ('aweme_detail', {dict}))
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
>                  'Fresh cookies (not necessarily logged in) are needed', expected=expected)
```suggestion
        if not detail:
            # TODO: Run verification challenge code to generate signature cookies
            raise ExtractorError(
                'Fresh cookies (not necessarily logged in) are needed',
                expected=not self._get_cookies(self._WEBPAGE_HOST).get('s_v_web_id'))
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +        return self._parse_aweme_video_web(traverse_obj(render_data, 'aweme_detail'), url, video_id)
wrong method
```suggestion
        return self._parse_aweme_video_app(detail)
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +            # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
revert unnecessary/unrelated formatting change
```suggestion
            'device_id': ''.join(random.choices(string.digits, k=19)), # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +from ..compat import compat_urllib_parse_urlparse
revert unnecessary/unrelated formatting change
```suggestion
from ..compat import compat_urllib_parse_urlparse
from ..networking import HEADRequest
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                                    only_once=True)
revert unnecessary/unrelated formatting change
```suggestion
                self.report_warning('Only one of the two required version params are passed as extractor arguments', only_once=True)
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                        '%s. Retrying... (attempt %s of %s)' % (str(e.cause or e.msg), count, len(self._APP_VERSIONS)))
revert unnecessary/unrelated formatting change
```suggestion
                    self.report_warning('%s. Retrying... (attempt %s of %s)' % (str(e.cause or e.msg), count, len(self._APP_VERSIONS)))
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +            expected_type=dict)
revert unnecessary/unrelated formatting change
```suggestion
            aweme_detail, ('interaction_stickers', ..., 'auto_video_caption_info', 'auto_captions', ...), expected_type=dict)
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                # TODO: Check for "direct iOS" videos, like https://www.tiktok.com/@cookierun_dev/video/7039716639834656002
revert unnecessary/unrelated formatting change
```suggestion
                    video_info, 'is_bytevc1', 'is_h265') else 'h264', # TODO: Check for "direct iOS" videos, like https://www.tiktok.com/@cookierun_dev/video/7039716639834656002
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +            'title') == 'original sound - %s' % music_info.get('owner_handle')
revert unnecessary/unrelated formatting change
```suggestion
        is_generic_og_trackname = music_info.get('is_original_sound') and music_info.get('title') == 'original sound - %s' % music_info.get('owner_handle')
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                })
revert
```suggestion
        for play_url in traverse_obj(video_info, ('playAddr', ((..., 'src'), None), {url_or_none})):
            formats.append({
                'url': self._proto_relative_url(play_url),
                'ext': 'mp4',
                'width': width,
                'height': height,
            })
```

2024-02-28 00:56 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                })
revert
```suggestion
        for download_url in traverse_obj(video_info, (('downloadAddr', ('download', 'url')), {url_or_none})):
            formats.append({
                'format_id': 'download',
                'url': self._proto_relative_url(download_url),
                'ext': 'mp4',
                'width': width,
                'height': height,
            })
```

2024-02-28 00:58 UTC, bashonly requested changes

2024-02-28 00:58 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +                    video_info, 'is_bytevc1', 'is_h265') else 'h264', # TODO: Check for "direct iOS" videos, like https://www.tiktok.com/@cookierun_dev/video/7039716639834656002
```suggestion
                    video_info, 'is_bytevc1', 'is_h265') else 'h264',  # TODO: Check for "direct iOS" videos, like https://www.tiktok.com/@cookierun_dev/video/7039716639834656002
```

2024-02-28 00:58 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +            'device_id': ''.join(random.choices(string.digits, k=19)), # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
```suggestion
            'device_id': ''.join(random.choices(string.digits, k=19)),  # Some endpoints don't like randomized device_id, so it isn't directly set in _call_api.
```

2024-02-28 01:08 UTC, bashonly approved these changes

2024-02-28 02:09 UTC, bashonly commented on yt_dlp/extractor/tiktok.py
> +            download_height = self.RESOLUTION_MAP.get(download_width)
```suggestion
            download_height = self.RESOLUTION_MAP.get(download_width)  # download_addr['height'] is inaccurate
```

2024-02-28 02:30 UTC, merged