[murrtube] Fix extractor (#7500)
yt-dlp/yt-dlp pull request #9249
Opened 2024-02-19 21:00 UTC by DrakoCpp

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Fixes #7500 for murrtube extractor which previously was not working

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-04-21 19:47 UTC, DrakoCpp commented
Hello, any news on this pull?

2024-04-22 05:01 UTC, pukkandan requested changes

2024-05-12 21:43 UTC, DrakoCpp commented on yt_dlp/extractor/murrtube.py
> -            'tags': meta.get('tagList'),
Added view, like and comment. Tags are not available anymore.

2024-05-12 21:43 UTC, DrakoCpp commented on yt_dlp/extractor/murrtube.py
> -class MurrtubeUserIE(MurrtubeIE):  # XXX: Do not subclass from concrete IE
Added back

2024-05-12 22:17 UTC, DrakoCpp commented
@pukkandan it should be ready

2024-05-16 22:01 UTC, bashonly requested changes
I've made several review comments and Github has auto-hidden some of them, please make sure to read & address all of them

2024-05-27 19:13 UTC, DrakoCpp commented on yt_dlp/extractor/murrtube.py
> +    ]
If i revert this to `_TEST` i get the following error:

```
AssertionError: MurrtubeUserIE has _TEST and _TESTS
```

2024-05-27 19:14 UTC, DrakoCpp commented on yt_dlp/extractor/murrtube.py
> +                'id': 'ca885d8456b95de529b6723b158032e11115d',
No, they seem to not be available anymore after the site revamp

2024-05-27 19:38 UTC, DrakoCpp commented on yt_dlp/extractor/murrtube.py
> +        video_page = self._download_webpage(url, video_id)
So it's ok this way?

2024-07-02 15:20 UTC, bashonly approved these changes

2024-07-02 15:20 UTC, bashonly commented on yt_dlp/extractor/murrtube.py
> +        video_id = self._search_regex(r'/([^/?#]+)/index.m3u8', playlist, 'video id')
```suggestion
        video_id = self._search_regex(r'/([\da-f]+)/index.m3u8', playlist, 'video id')
```

2024-07-02 21:49 UTC, merged