[Dumpert] Broader url support
yt-dlp/yt-dlp pull request #9320
Opened 2024-02-29 03:07 UTC by rvsit

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Now supports any url with `?selectedId=` such as `https://www.dumpert.nl/toppers/dag?selectedId=100086074_f5cef3ac`

(Did not make issue because seem a fairly straightforward fix).
All tests run, see https://regex101.com/r/sXNP7f/1 to confirm that the regex still works properly for the other urls.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-03-01 09:48 UTC, pukkandan commented on yt_dlp/extractor/dumpert.py
> +            .*\?selectedId=
```suggestion
            [^#]+[?&]selectedId=
```

Isn't this more accurate?

2024-03-01 20:51 UTC, bashonly requested changes

2024-03-01 20:51 UTC, bashonly commented on yt_dlp/extractor/dumpert.py
>              /(?:mediabase|embed|item)/|
we should probably move the slash that trails the TLD out of the optional group so we don't accidentally match the wrong domain e.g. `dumpert.nlmaogetpwned.xyz?selectedId=123_abc`
```suggestion
        (?P<protocol>https?)://(?:(?:www|legacy)\.)?dumpert\.nl/(?:
            (?:mediabase|embed|item)/|
```

2024-03-01 20:51 UTC, bashonly commented on yt_dlp/extractor/dumpert.py
> +            [^#]+[?&]selectedId=
and if we apply my above suggestion then we'll need to do this too
```suggestion
            [^#]*[?&]selectedId=
```

2024-03-03 16:28 UTC, bashonly approved these changes

2024-03-03 23:12 UTC, merged