[networking] Add `ImpersonateResponse`
yt-dlp/yt-dlp pull request #9756
Opened 2024-04-21 18:17 UTC by bashonly

Adding a wrapper for impersonate responses will allow extractors to know if impersonation was used (and which impersonate target was used) for a given request. This can be useful during extractor error handling, [e.g. in the crunchyroll extractor](https://github.com/bashonly/yt-dlp/commit/3f17042578e8dfcdd08126b964e3c89e4beff759), where we want to expect the 403 error and a offer a cloudflare bypass hint if impersonation was not used, or else raise w/ a bug report message if impersonation was used.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Core bug fix/improvement

</details>

2024-04-21 19:00 UTC, coletdjnz requested changes

2024-04-21 19:00 UTC, coletdjnz commented on yt_dlp/networking/_curlcffi.py
> +        impersonate_target = self._get_request_target(request)
It should use the mapped target imo

2024-04-23 13:45 UTC, pukkandan commented
Pls explain motivation for https://github.com/yt-dlp/yt-dlp/pull/9756/commits/3b48105b8c2a6034f97d00d3bf876d90773218f4. I liked the first impl much better

2024-04-23 14:46 UTC, bashonly commented
@pukkandan 

hypothetically, the value of `impersonate` can be `None`:
https://github.com/yt-dlp/yt-dlp/blob/52f5be1f1e0dc45bb397ab950f564721976a39bf/yt_dlp/networking/impersonate.py#L61-L80

so if a response is an instance of `ImpersonateResponse`, then that is completely meaningless on its own. In order to determine if impersonation was used for a request, the extractor would also have to do check truthiness of the `impersonate` attribute, with the code looking like this:

```py
from ..networking.impersonate import ImpersonateResponse

try:
    ...
except ExtractorError as e:
    if isinstance(e.cause, HTTPError) and e.cause.status == 403:
        if isinstance(e.cause.response, ImpersonateResponse) and e.cause.response.impersonate is not None:
            target = str(e.cause.response.impersonate)
            # handling for impersonation
        # handling for no impersonation
```

vs. with new impl:

```py
try:
    ...
except ExtractorError as e:
    if isinstance(e.cause, HTTPError) and e.cause.status == 403:
        if target := e.cause.response.extras.get('impersonate'):
            # handling for impersonation
        # handling for no impersonation
```

2024-04-25 10:20 UTC, coletdjnz commented on yt_dlp/networking/common.py
> +        self.extensions = {}
I would also expose this as a parameter for Response, same as Request

+ add in docstring

2024-05-04 21:51 UTC, Grub4K approved these changes

2024-05-04 22:19 UTC, merged