Parse YT-EXT-AUDIO-CONTENT-ID for multiple language detection in YouTube HLS Manifests.
yt-dlp/yt-dlp pull request #9875
Opened 2024-05-06 13:47 UTC by clienthax

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Properly parse YT-EXT-AUDIO-CONTENT-ID when present in HLS manifests to determine correct audio streams.
Fixes ability to specify languages for YouTube when using hls manifests with the following arguments which would otherwise just fall back to the first entry.

```
yt-dlp -f mp4[height<=?1080][language=en]/best[height<=?1080][language=en] --verbose --list-formats --no-cache-dir --rm-cache-dir --get-url --impersonate safari https://www.youtube.com/watch?v=4ofJpOEXrZs

```

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [x] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-06-10 22:31 UTC, bashonly requested changes

2024-06-10 22:31 UTC, bashonly commented on yt_dlp/extractor/common.py
> +                        f['language'] = last_stream_inf.get('YT-EXT-AUDIO-CONTENT-ID').split('.')[0]
```suggestion
                    if yt_content_id := last_stream_inf.get('YT-EXT-AUDIO-CONTENT-ID'):
                        f['language'] = yt_content_id.split('.')[0]
                        if last_stream_inf.get('DEFAULT') == 'YES':
                            # Keep value in sync with yt_dlp.extractor.YoutubeIE._extract_formats_and_subtitles
                            f['language_preference'] = 10
```

2024-06-19 22:32 UTC, bashonly approved these changes
@clienthax please test my latest changes

2024-06-20 21:49 UTC, seproDev approved these changes

2024-06-20 21:54 UTC, merged