Add Digiview extractor
yt-dlp/yt-dlp pull request #9902
Opened 2024-05-10 14:04 UTC by lfavole

**IMPORTANT**: PRs without the template will be CLOSED

### Description of your *pull request* and other information

Added extractor for Digiview URLs (https://ladigitale.dev/digiview).
The extractor forwards the video ID to the YouTube extractor.

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Fix or improvement to an extractor (Make sure to add/update tests)
- [x] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2025-02-09 11:41 UTC, lfavole reviewed
It's been one year, now you should consider merging my pull request...

2025-02-09 14:18 UTC, seproDev requested changes
Review capacity is extremely limited. Probably due to needing significant changes, this fell off the radar. Sorry about that. I've left an initial review.

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +from yt_dlp.utils import int_or_none
Use relative imports

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +        )
I don't understand why you wrap this in a Request object. Can't you do
```suggestion
        video_data = self._download_json(
            'https://ladigitale.dev/digiview/inc/recuperer_video.php', video_id,
            data=urllib.parse.urlencode({'id': video_id}).encode())
```

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +        info = youtube_ie._real_extract(webpage_data['videoId'])
Don't extract inside extractor, but instead use url results

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +        return info
Instead of passing custom ffmep args, just return a `section_start` and `section_end` time. Something like this should work:
```suggestion
        clip_id = video_data['videoId']
        return {
            '_type': 'url_transparent',
            'url': f'https://www.youtube.com/watch?v={clip_id}',
            'ie_key': YoutubeIE.ie_key(),
            'id': clip_id,
            **traverse_obj(video_data, {
                'section_start': ('debut', {int_or_none}),
                'section_end': ('fin', {int_or_none}),
                'description': ('description', {clean_html}),
                'title': ('titre', {str}),
                'thumbnail': ('vignette', {url_or_none}),
                'view_count': ('vues', {int_or_none}),
            }),
        }
```

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +    IE_NAME = 'digiview'
imo. not needed if they are just repeats
```suggestion
```

2025-02-09 14:18 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +            # normal video
This video has since been removed from YouTube. Could you please update the tests?

2025-02-09 17:28 UTC, lfavole commented on yt_dlp/extractor/digiview.py
> +        )
I absolutely need to make a POST request, see https://codeberg.org/ladigitale/digiview/src/commit/b10f7348f7/inc/recuperer_video.php#L42.

2025-02-09 17:30 UTC, bashonly commented on yt_dlp/extractor/digiview.py
> +        )
if you pass any `data` value besides `None` to the `_download_json` helper method it will make it a POST request for you

2025-02-09 17:31 UTC, bashonly commented on yt_dlp/extractor/digiview.py
> +        )
I would use `urlencode_postdata` here though instead of `urllib.parse` (import from `utils`)

2025-02-09 17:34 UTC, lfavole commented on yt_dlp/extractor/digiview.py
> +        info = youtube_ie._real_extract(webpage_data['videoId'])
Could you explain better and write some example code?

2025-02-09 17:34 UTC, bashonly commented on yt_dlp/extractor/digiview.py
> +        )
edited, refresh the page

2025-02-09 17:36 UTC, bashonly commented on yt_dlp/extractor/digiview.py
> +        info = youtube_ie._real_extract(webpage_data['videoId'])
```suggestion
        return self.url_result(webpage_data['videoId'], YoutubeIE)
```

2025-02-09 17:52 UTC, lfavole commented on yt_dlp/extractor/digiview.py
> +    IE_NAME = 'digiview'
Do I need to remove them?

2025-02-09 17:55 UTC, bashonly commented on yt_dlp/extractor/digiview.py
> +    IE_NAME = 'digiview'
as-is they are redundant, so yeah

2025-02-09 18:44 UTC, seproDev requested changes

2025-02-09 18:44 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +class DigiviewIE(YoutubeIE):
Don't subclass from a concrete extractor
```suggestion
class DigiviewIE(InfoExtractor):
```
Needs `from .common import InfoExtractor` as well

2025-02-09 18:44 UTC, seproDev commented on yt_dlp/extractor/digiview.py
> +                'title': 'Big Buck Bunny 60fps 4K - Official Blender Foundation Short Film',
These tests are incomplete. Please actually run them.
You should also merge master in to your branch.

2025-02-11 09:27 UTC, lfavole commented
Hello, I have updated the PR. Can you take a look at it and maybe merge it?

2025-02-11 19:54 UTC, seproDev approved these changes

2025-02-11 20:00 UTC, bashonly approved these changes

2025-02-11 20:04 UTC, merged