[damtomo] add suppoort for Damtomo service
yt-dlp/yt-dlp pull request #992
Opened 2021-09-16 14:28 UTC by nao20010128nao

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Damtomo is a service to expose users' singing scenes.

example video url: https://www.clubdam.com/app/damtomo/karaokeMovie/StreamingDkm.do?karaokeMovieId=2414316
example record url: https://www.clubdam.com/app/damtomo/karaokePost/StreamingKrk.do?karaokeContributeId=27376862

2021-09-16 19:14 UTC, pukkandan requested changes

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +        data_dict = {k: re.sub(r'\s+', ' ', v) for k, v in data_dict.items() if v}
```suggestion
        data_dict = {
            mobj.group('class'): re.sub(r'\s+', ' ', clean_html(mobj.group('value')))
            for mobj in re.finditer(r'(?s)<(p|div)\s+class="(?P<class>[^" ]+?)">(?P<value>.+?)</\1>', webpage)}
```

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +        # NOTE: there are excessive amount of spaces and line breaks, so ignore spaces around these part
```suggestion
```
using /s* everywhere is already recommended practice

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            'url': m3u8_url,
dont pass m3u8 url directly. parse and sort the formats

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            'artist': data_dict['song_artist'],
.get

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            'uploader': data_dict['user_name'],
.get

2021-09-16 19:14 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            'upload_date': try_get(data_dict, lambda x: self._search_regex(r'(\d\d\d\d/\d\d/\d\d)', x['date'], 'upload_date', default=None).replace('/', ''), compat_str),
use unified_strdate

2021-09-17 20:35 UTC, pukkandan approved these changes
just a few tiny changes. then it can be merged

2021-09-17 20:35 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            'upload_date': unified_strdate(self._search_regex(r'(\d\d\d\d/\d\d/\d\d)', data_dict.get('date'), 'upload_date', default=None)),
```suggestion
            'upload_date': unified_strdate(self._search_regex(r'(\d{4}/\d{2}/\d{2})', data_dict.get('date'), 'upload_date', default=None)),
```

2021-09-17 20:35 UTC, pukkandan commented on yt_dlp/extractor/damtomo.py
> +            m3u8_url, video_id, ext='mp4')
```suggestion
        formats = self._extract_m3u8_formats(m3u8_url, video_id, ext='mp4')
```

2021-09-18 04:17 UTC, nao20010128nao commented on yt_dlp/extractor/damtomo.py
> +            m3u8_url, video_id, ext='mp4')
All of them done

2021-09-18 05:55 UTC, merged