Update hearthisat URL regexp to allow downloading of private tracks
yt-dlp/yt-dlp pull request #9949
Opened 2024-05-17 22:32 UTC by bohwaz

### Description of your *pull request* and other information

This updates the HearThis.at URL regexp to allow for private tracks, which contain a last part:

Private track URL: `https://hearthis.at/tindalos/0001-tindalos-gnrique/eQd/`
Public track URL: `https://hearthis.at/moofi/dr-kreep`

<details open><summary>Template</summary> 

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions) including [yt-dlp coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions)
- [x] [Searched](https://github.com/yt-dlp/yt-dlp/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8) and [ran relevant tests](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)

### In order to be accepted and merged into yt-dlp each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check all of the following options that apply:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Fix or improvement to an extractor (Make sure to add/update tests)
- [ ] New extractor ([Piracy websites will not be accepted](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy))
- [ ] Core bug fix/improvement
- [ ] New feature (It is strongly [recommended to open an issue first](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes))

</details>

2024-05-18 00:04 UTC, bashonly requested changes
Can you add a test for a private track URL?

2024-05-22 22:17 UTC, Grub4K approved these changes

2024-05-22 22:27 UTC, bashonly approved these changes

2024-05-22 22:27 UTC, bashonly commented on yt_dlp/extractor/hearthisat.py
>          }
```suggestion
            'genres': ['Experimental'],
        },
```

2024-05-23 04:30 UTC, merged